/*global app */
/*jslint browser, white, fudge */

app.timelines.push(
  {timeline: "Asian American", prefix: "A",
   credit: "Compiled by: Karen L. Suyemoto, Ph.D. – UMass (Boston) Psychology and Asian American Studies. Updated 2005/2006 by Claudia Fox Page 1 Tree and Elli Stern for EMI Empowering Multicultural Initiatives. Updated 2014 by Emily Davis, for K. Suyemoto.",
   resources: [
       "The Asian American Almanac: A reference work on Asians in the United States. Susan Gall, ed.; Gale Research: Detroit, 1995",
       "Strangers from a Different Shore: A History of Asian Americans. Ronald Takaki. Little Brown and Company, 1998",
       "The Chinese in America: A Narrative History. Iris Chang. Penguin Books, 2003",
       "BRIDGE: Building a Race and Immigration Dialogue in the Global Economy. Eunice Hyunhye Cho, Miriam Ching Yoon Louie & Sasha Khokha. National Network for immigrant an refugee rights, Oakland, CA, 2004 (BRIDGE)",
       "Open Minds to Equality. Nancy Schniedewind & Ellen Davidsosn. Allyn & Bacon: Boston, 1998 (OME) Asian American Sexualities: Dimensions of the Gay and Lesbian Experience. Russell Leong, ed. NY: Routledge, 1996 (AA Sexualities)",
       "Completely Queer, Steve Hogan & Lee Hudson. New York: Henry Holt & Company, Inc. Gay & Lesbian Almanac, Edited by Neil Schlager. Detroit, MI: St. James Press, Boston Globe, 1998 (CQ)",
       "Race and Mixed Race, Naomi Zack. Philadelphia, PA: Temple University Press, 1993 (R&MR)",
       "Racially Mixed People in America. Maria P. P. Root (ed.). CA: Sage Publications, Inc., 1992 (RMP)",
       "The Multiracial Experience. Maria P. P. Root (ed.). CA: Sage Publications, Inc., 1996 (ME) Chinese in Boston. Wing-kai To. SC: Arcadia Publishing, 2008 (CB)",
       "http://www.cetel.org/timeline.html Ancestors in the Americas: Asian American History Timeline",
       "http://www.askasia.org The Asian American Experience in the United States",
       "http://www.apalc.org Asian Pacific American Legal Center",
       "http://www.army.mil/asianpacificsoldiers/wars/civilwar.html U.S. Army Website www.oah.org/pubs/magazine/family/cruz-berson.html \"The American Melting Pot? Miscegenation Laws in the United States\" by Barbara C. Cruz and Michael J. Berson, Organization of American Historians",
       "http://www.asian-nation.org/14-statistics.shtml Asian-Nation demographics and statistics page",
       "http://www.angryasianman.com Website with information on current Asian American news and popular culture",
       "http://www.asianlawcaucus.org/altruesite/files/alc_dev/Q%20%20A%20Vietnamese%20Repatriation.pdf FAQ on Vietnam/U.S. deportation agreement"],
   entries: [
    {date: "1763",
     desc: "Filipinos impressed into the Manila Galleon Trade (1565-1815) between Mexico and the Philippines settle in Louisiana after jumping ship"},
    {date: "1790",
     desc: "First U.S. Naturalization Act allows only “free white persons” to become American citizens First recorded arrival of Asian Indians in the U.S."},
    {date: "1830",
     desc: "First U.S. census notation of Chinese in America—the count is 3."},
    {date: "1847",
     desc: "Three Chinese boys enrolled at Monson Academy in SW Massachusetts. One of them, Yung Wing, went to Yale and became the first Chinese grad of a major college in 1854."},
    {date: "1848",
     desc: "Discovery of gold in California.  Chinese begin to arrive, some as indentured servants, during the CA Gold Rush. The bulk of these immigrants later become a source of cheap labor for railroads, mines, fisheries, farms, etc."},
    {date: "1850",
     desc: "San Francisco’s Chinatown was established and began to grow. The number of Chinese in California grows from 3 in 1848 to 3000 in 1850."},
    {date: "1850",
     desc: "A Japanese man, Hikozo Hamada (Joseph Heco) is rescued at sea by an American sailing ship. He studies in Baltimore, MD, and becomes the first Japanese naturalized as an American citizen"},
    {date: "1852",
     desc: "California imposes a Foreign Miner’s License Tax, collecting $3 a month from every foreign miner who was not a citizen (Chinese were prohibited from citizenship by law). The purpose of this tax was to reduce the number of Chinese immigrating to California as well as to discourage Chinese from mining for gold."},
    {date: "1854",
     desc: "People vs. Hall forbids Chinese from testifying in court against whites, depriving Chinese of legal protection and subjecting them to repeated acts of violence."},
    {date: "1859",
     desc: "Chinese are excluded from public schools in San Francisco"},
    {date: "1860",
     desc: "First Japanese delegation visits Washington, D.C."},
    {date: "1862",
     desc: "Congress enacts a law that allows “any alien” honorably discharged from U.S. military service to apply for naturalization.  Private Joseph L. Pierce, born in Canton, China, enlists in the 14th Connecticut Infantry in August 1862 to fight against the Confederacy in the U.S. Civil War.  Another Chinese American, Edward Day Cohota, from Shanghai, China and raised in Gloucester, MA, joins the 23rd Massachusetts Infantry to fight in the U.S. Civil War."},
     {date: "1863",
      desc: "Recruiting begins for Chinese laborers for the Central Pacific Railroad. Chinese workers were essential to the completion of the transcontinental railroad but excluded from the final ceremonies."},
     {date: "1868",
      desc: "About 149 Japanese contract workers arrive in HI to work the sugar plantations"},
     {date: "1868",
      desc: "The U.S. ratifies the Burlingame Treaty with China, recognizing the right of Chinese to immigrate for “purpose of curiosity, trade, or permanent residence,” but expressly restricts the right of naturalization."},
     {date: "1869",
      desc: "Southern plantation owners bring around 2,000 Chinese to replace slave labor."},
     {date: "1870",
      desc: "Naturalization Act” excludes Chinese from citizenship and prohibits entry of wives of laborers (1910). Nationwide recession causes West Coast labor problems. Mobs destroy Chinese communities in many areas of CA and other states."},
     {date: "1870",
      desc: "63,199 Chinese in continental U.S., 99.4% in western states/territories, 78% in California."},
     {date: "1870",
      desc: "Owner of North Adams, MA factory is the first to bring Chinese laborers to break a strike."},
     {date: "1870",
      desc: "Middle-class White Protestant women set up rescue homes for Chinese women who had been brought to California and forced to work as prostitutes."},
     {date: "1870",
      desc: "Publication of the poem “The Heathen Chinese” highlighted tensions between Irish and Chinese, and the reality of racism."},
     {date: "1875",
      desc: "Page Law prohibits entry of Chinese, Japanese, and “Mongolian” prostitutes. The law requires proof of “good character” for entry and is widely applied to all Chinese women, contributing to a gender imbalance that reaches a ratio of 27 Chinese men to every one Chinese woman in the U.S. by 1890."},
     {date: "1876+",
      desc: "Economic collapse in U.S. leads to anti-Chinese violence in California."},
     {date: "1879",
      desc: "Hong Far Low Restaurant, believed to be first in Boston, is established."},
     {date: "1879",
      desc: "The second Constitution of California adopted this year contains many discriminatory provisions against Chinese: (1) Chinese immigrants are denied naturalization; (2) corporations are not allowed to hire Chinese; (3) Chinese are forbidden to be employed in public works except as punishment for crimes; (4) recruitment of Chinese laborers is considered as coolie trade and made illegal; (5) State Legislature is to assist the removal of Chinese to regions beyond the limits of cities and towns."},
     {date: "1879",
      desc: "Congress passes law to limit ships to carry no more than 15 Chinese passengers each."},
     {date: "1880",
      desc: "Treaty between U.S. and Chinese gives the U.S. the right to limit Chinese immigration. New York City’s Chinatown is established."},
     {date: "1881-1892",
      desc: "Four female Chinese students obtain medical degrees from U.S. universities"},
     {date: "1882",
      desc: "The Chinese Exclusion Act prohibits entrance of Chinese laborers, and prohibits courts from issuing citizenship. It was intended to last for only 10 years but was later extended until 1902 and again extended indefinitely in various forms under various names until it was negated in 1943."},
     {date: "1882",
      desc: "The “Chinese Must Go” movement gains momentum: Chinese immigration to the U.S. declined from 39,500 in 1882 to only 10 in 1887."},
     {date: "1885",
      desc: "Following the Chinese Exclusion Act, large numbers of young Japanese laborers, together with smaller numbers of Koreans and Indians began arriving on the West Coast where they replace the Chinese as cheap labor in building railroads, farming and fishing."},
     {date: "1882",
      desc: "San Francisco builds new segregated \"Oriental School.\""},
     {date: "1882",
      desc: "Major violent attacks on Chinese communities in Wyoming"},
     {date: "1885",
      desc: "Major violent attacks on Chinese communities in Washington"},
     {date: "1887",
      desc: "Major violent attacks on Chinese communities in Oregon"},
     {date: "1886",
      desc: "In Yick Wo v. Hopkins the U.S. Supreme Court rules that a law that was seemingly race neutral, if applied in a prejudicial way, is against the Equal Protection Clause of the 14th amendment, even if those affected are not U.S. citizens. Chinese immigrants, who were ineligible for citizenship are still protected by Constitutional Rights under the Fourteenth Amendment: “The guarantee of protection contained in the Fourteenth Amendment to the Constitution extend to all persons within the territorial jurisdiction of the United States, without regard to differences of race, or color, or of nationality.”"},
     {date: "1888",
      desc: "Congress passes the Scott Act, which bars the re-entry of Chinese laborers who have left the U.S. for temporary visits to China (permitted under the Exclusion Act). Over 20,000 Chinese laborers with re-entry permits are denied return to the U.S."},
     {date: "1889",
      desc: "In Chae Chan Ping v. U.S., the Supreme Court decides that despite the treaty of 1867, the U.S. may freely exclude Chinese under the Chinese Exclusion Act"},
     {date: "1892",
      desc: "Geary Act extends the 1882 Chinese Exclusion Act, denies bail and writ of habeas corpus, and requires Chinese living in the U.S. to carry certificates of residence."},
     {date: "1893",
      desc: "The Chinese community organizes to challenge the constitutionality of the Geary Act before the Supreme Court. In upholding the act, the Supreme Court decides in the case of Fong Yue Ting v. United States, that the Congress has the right to legislate expulsion of Chinese through the order of executive officers."},
     {date: "1894",
      desc: "Saito, a Japanese man, applies for U.S. citizenship. Courts refuse because he is neither white nor black."},
     {date: "1898",
      desc: "The treaty of Paris, which negotiates the end of the Spanish American War, cedes the Philippines and Guam to the U.S.."},
     {date: "1898",
      desc: "Hawaii is annexed by force to the U.S."},
     {date: "1900",
      desc: "1% of the U.S. population is considered Asian/Pacific Islander – 87.9% is considered white"},
     {date: "1900",
      desc: "Japanese Association of American is founded in San Francisco to counter racial discrimination. Executive order 589 commonly referred to as President Theodore Roosevelt issues the “Gentleman’s Agreement”. The Japanese government refuses to issue passports for laborers immigrating to the U.S. mainland, but agrees to allow departures for HI."},
     {date: "1900",
      desc: "Several Japanese become naturalized citizens of HI, but the U.S. territorial government refuses to recognize them."},
     {date: "1900",
      desc: "HI is incorporated as a territory of the U.S. but Chinese living in Hawaii is forbidden to travel to the U.S. mainland."},
     {date: "1901",
      desc: "Dr. Jokichi Takamine isolates pure epinephrine (adrenalin) at John Hopkins University. A long time resident of the U.S., Dr. Takamine declines honorary citizenship until all immigrants of Japanese ancestry are allowed the right to become citizens."},
     {date: "1901",
      desc: "California’s anti-miscegenation law is amended to include marriages between whites and “Mongolians.” This law remains in effect until 1948."},
     {date: "1902",
      desc: "Chinese exclusions extended."},
     {date: "1903",
      desc: "About 2,000 Japanese and Mexican sugar beet workers go on strike in CA and form the first successful farm workers union. The American Federation of Labor refuses to recognize a non-white union"},
     {date: "1903-10-11",
      desc: "Boston police carry out an immigration raid during a funeral for a Chinese murder victim. 300 men arrested and 50 deported."},
     {date: "1904",
      desc: "7,000 Korean immigrants come to Hawaii and then mainland U.S. following the 1904-1905 Russo-Japanese War and Japan’s occupation of Korea. Brought in as strikebreakers, railroad builders and agricultural workers, Korean immigrants faced not only racist exclusion in the U.S. but Japanese colonization at home."},
     {date: "1904",
      desc: "South Asian Indian immigrants enter the U.S. as laborers, following Chinese exclusion."},
     {date: "1905",
      desc: "The Asiatic Exclusion League, a group made up of representatives of 67-labor organization, is established in San Francisco. Eventually, more than 200 labor unions joined the league to restrict Asian immigration through the courts, through propaganda, and through violence."},
     {date: "1905",
      desc: "China launches a nationwide boycott against U.S. goods to protest U.S. discrimination and prejudice against Chinese."},
     {date: "1905",
      desc: "The San Francisco School Board establishes a segregated Primary School for Chinese Children to attend, including those who are American born."},
     {date: "1906",
      desc: "The San Francisco School Board creates an international incident when it orders children of Chinese, Japanese, and Korean residents to attend the segregated Oriental Public School. In November, the School Board removes 93 children of Japanese ancestry (25 U.S. citizens) to the segregated school. Major earthquake in San Francisco destroys all municipal records and opens the way for a new wave of Chinese immigrants. Immigrants (men in particular) could now claim they are U.S. citizens and have the right to bring wives and children to America (“paper sons”)."},
     {date: "1907",
      desc: "President Roosevelt intervenes and forces the San Francisco School Board to rescind the segregation order. Later this year he signs a bill that further restricts Japanese immigration and issues an Executive Order that bars Japanese from entering the mainland via HI, Mexico, or Canada. In exchange for the intervention in the school segregation case, Japan does not protest the Executive Order."},
     {date: "1908",
      desc: "President Theodore Roosevelt enters into “Gentlemen’s Agreement” with Japan to limit Japanese immigration to the mainland and Hawaii. (A provision allows family members including wives of Japanese to immigrate, thus allowing the Japanese to begin families and build their community.) This is a prelude to a Japanese Exclusion Act by Congress. It also includes a ban on further Korean immigration to the United States as laborers, thus opening up farming jobs in Hawaii for Filipinos."},
     {date: "1908",
      desc: "Buntaro Kumahi, honorably discharged from the U.S. Army, is denied naturalization on the grounds that the words “any alien” in the 1862 act means those who are “free white persons or those of African descent.”"},
     {date: "1910",
      desc: "Japanese picture brides arrive in the U.S., continuing until 1921, when U.S. convinces Japanese government to stop issuing passports."},
     {date: "1910",
      desc: "Angel Island is set up as a detention center for non-laboring Asian immigrants. Between 1910 and 1940, hopeful Chinese immigrants were detained at Angel island where they were required to undergo medical examinations and detailed interrogations. Failed answers were grounds for continued detainment and eventual deportation back to China. Some detainees commit suicide."},
     {date: "1910",
      desc: "Japan declares Korea its colony"},
     {date: "1910",
      desc: "Syngman Rhee returns to Korea, the first Korean to receive a PhD from a U.S. University (Princeton) "},
     {date: "1910",
      desc: "The Supreme Court broadens the 1870 Naturalization Act, excluding other Asians from citizenship. "},
     {date: "1910",
      desc: "Arthur K. Ozawa, HI-born graduate of the Univ. of Michigan Law School is admitted to the bar in MI and HI—believed to the first Japanese American lawyer."},
     {date: "1912",
      desc: "Native Hawaiian Duke Kahanamoku, ties the world record in a qualifying heat for the 100-meter freestyle and goes on to win the Olympic gold metal."},
     {date: "1913",
      desc: "The Alien Land Act in CA is signed into law, forbidding a person who is ineligible for citizenship from purchasing land for agricultural purposes and restricting land leases to “aliens” to no more than 3 years. Similar laws passed in WA, OR, ID, MN, AZ, NM, NB, TX, KS, LO, MO, MI"},
     {date: "1914",
      desc: "Edith Maude Eaton, also known as Sui Sin Far, dies. The daughter of a Chinese mother and British father, she was a writer who created stories (during the early 1900s) sympathetic to the Chinese and multi-racial Chinese in the U.S."},
     {date: "1916",
      desc: "Eugenicist, Madison Grant writes The Passing of the Great Race. According to Grant, the result of white and non-white racial mixing will always be a race reverting to the \"lower race\" in evolutionary specialization. Therefore, Grant reasoned, the mix of a white man and an Indian was an Indian; a white man and a Negro, a Negro; a white man and a Hindu, a Hindu; and any European race and a Jew, a Jew."},
     {date: "1917",
      desc: "President Wilson vetoes the Asiatic Barred Zone Act, but is overridden by Congress. The Act precludes immigration from all of Asia and India."},
     {date: "1917",
      desc: "29,000 Issei (immigrant Japanese) and some Nisei (first generation of American-born Japanese) register for Selective Service in HI during WWI"},
     {date: "1918",
      desc: "Servicemen of Asian ancestry who had served in World War I receive right of naturalization."},
     {date: "1920",
      desc: "CA Alien Land Act amended to prohibit Asian immigrant parents from serving as guardians of property for minor American-born citizen children, and prohibiting any leasing of land."},
     {date: "1920",
      desc: "An act against Chinese women denies them automatic citizenship if they marry a U.S. citizen"},
     {date: "1920",
      desc: "Ladies Agreement” ends the arrival of Japanese and Korean picture brides. European women are also affected-they were banned from entry if they could not show that either a man or a job was available."},
     {date: "1922",
      desc: "Congress passes the Cable Act, which revokes the U.S. citizenship of any citizen woman marrying an alien ineligible for U.S. citizenship"},
     {date: "1922",
      desc: "Ozawa ruling. Japanese immigrant, Takao Ozawa, challenges the Supreme Court saying he qualifies for citizenship. His case is denied because he is not “Caucasian.”"},
     {date: "1923",
      desc: "In U.S. v. Bhagat Singh Thind, the Supreme Court declares Asian Indians ineligible for citizenship, while Asian Indians might be “Caucasian,” they are not white, and therefore not eligible for citizenship. Frick v. Webb forbids aliens “ineligible to citizenship” from owning stocks in corporations formed for farming."},
     {date: "1924",
      desc: "President Coolidge signs the Immigration Act of 1924, also known as the Quota Immigration of National Origins Act. With the exception of Filipino “nationals”, all Asian immigrants, including Chinese, Japanese, Koreans and Indians were fully excluded by law, denied citizenship and naturalization, and prevented from marrying Caucasians or owning land."},
     {date: "1925",
      desc: "Legislative act makes Filipinos ineligible for U.S. citizenship unless they served 3 years in the U.S. Navy"},
     {date: "1929",
      desc: "Ruby Foo’s Den opened in Boston Chinatown. Foo was one of the earliest female Chinese restaurants owners in U.S."},
     {date: "1930",
      desc: "Los Angeles Superior Court rules that Filipinos are members of the “Mongolian” race, opening the way to invalidate more than 100 interracial marriages performed since 1921."},
     {date: "1930",
      desc: "Films based on Charlie Chan novels produced – the inscrutable Chinese detective who spoke in Confucian proverbs."},
     {date: "1931",
      desc: "The Cable Act is amended, allowing U.S. women to retain the citizenship after marriage to aliens ineligible for citizenship through the naturalization process. The Act is finally repealed in 1936."},
     {date: "1932",
      desc: "Congress passes the Hares-Hawes-Cutting Act, which bars Filipino migration to the U.S. because they have been ruled ineligible for U.S. citizenship."},
     {date: "1934",
      desc: "Tydings-McDuffie Act spells out procedure for eventual Philippine independence and reduces Filipino immigration to 50 persons per year."},
     {date: "1940",
      desc: "Leaders of the JACL (Japanese American Citizens League) meet with officials of the Army and Navy Intelligence Service and pledge loyalty and cooperation."},
     {date: "1941",
      desc: "The Munson report is submitted to the president and secretary of state, certifying that Japanese Americans possess an extraordinary degree of loyalty to the U.S. and that immigrant Japanese are of no danger to the U.S. Years of secret surveillance by the FBI and office of Naval Intelligence corroborate the report."},
     {date: "1941",
      desc: "Japan invades the Philippines. A third of the Filipino men in the United States sign up to fight in the U.S. military."},
     {date: "1941-12-7",
      desc: "Japanese planes attack Pearl Harbor, Hawaii. HI governor places the islands under martial law with restrictions applying to everyone, but 160 Hawaiian Issei community leaders are sent to the Sand Island detention camp."},
     {date: "1941",
      desc: "U.S. declares war on Japan. Germany and Italy declare war on U.S. and U.S. reciprocates in kind. Secretary of the Navy Frank Knox declares that “the most effective fifth-column work of the entire war was done in Hawaii,” implicating Japanese Americans as saboteurs. The statement was based largely on rumors, and later found to be false."},
     {date: "1941",
      desc: "General Emmons named new commander of the army and rejects a suggestion made by the Joint Chiefs of Staff in Washington to intern all persons of Japanese ancestry residing in HI at either the former Hansen’s disease (leprosy) colony site on Molokai or in mainland detention camps."},
     {date: "1941",
      desc: "General DeWitt, head of the Western Defense Command, rejects interning Japanese Americans by stating: “An American citizen, after all, is an American citizen.” He later changes his mind (see 1943) . Massive voluntary enlistment of Asian Americans into U.S. armed forces begins"},
     {date: "1942-02",
      desc: "Franklin D. Roosevelt signs executive order 9066 authorizing the Secretary of War to prescribe certain areas as military zones, clearing the way for internment of Japanese Americans."},
     {date: "1942-06",
      desc: "The Battle of Midway results in U.S. Naval Intelligence reports that the Japanese naval fleet is virtually destroyed, eliminating the threat of a West Coast invasion. In spite of the fact that the rationale for the internment is gone, the evacuation and incarceration continues: At this time only 17,000 Japanese are in detention camps, 120,000 will eventually be held."},
     {date: "1942",
      desc: "Hirota Isomura and Toshio Obata are shot and killed by guards at the Kordsburg, NM internment camp. Both victims were invalids, Obata was a hospital patient."},
     {date: "1942",
      desc: "Filipinos are reclassified as U.S. citizens, making it possible for them to register for the military"},
     {date: "1942",
      desc: "The 100th Infantry battalion of Nisei (2nd generation Japanese-Americans) volunteers was formed in May, 1942. By September, 1943, they were sent to Italy where they saw fierce combat and came to be known as the “Purple Heart Battalion” because of their high casualty rate."},
     {date: "1943",
      desc: "A loyalty questionnaire is administered at all detention camps to men and women over age 17. One question asks if the respondent will renounce all loyalty to Japan and the emperor, essentially requiring Issei to renounce their only possible citizenship as they are still ineligible for U.S. citizenship."},
     {date: "1943",
      desc: "DeWitt testifies that: “A Jap’s a Jap. You can’t change him by giving him a piece of paper”"},
     {date: "1943",
      desc: "Magnuson Act” finally repeals the Chinese Exclusion Act of 1882. This was a direct result of the alliance between the United States and China during World War II. A quota of 105 per year set for Chinese immigration (based on a formula set at one-sixth the total population of that ancestry in the 1920 census)."},
     {date: "1944-01",
      desc: "The draft is reinstated in January, 1944 for Nisei in the detention camps to bolster the ranks of the segregated 442nd Regimental Combat Team."},
     {date: "1944",
      desc: "106 Nisei soldiers at Fort McClellan refuse combat training to protest the incarceration of their families. 21 are court-martialed and sentenced to prison. Other Nisei refuse to report for the draft and 267 are eventually convicted of draft resistance."},
     {date: "1944-06",
      desc: "The 442nd lands in Italy, suffers 93% official casualty rate (314% informal casualty rate dividing number of Purple Hearts over in-theater personnel) and becomes the most decorated unit for its size and length of service."},
     {date: "1944-10",
      desc: "The 442nd rescues 211 soldiers of the Texas “Lost Battalion” after 5 days of fighting. The 442nd suffers over 800 casualties, including 184 dead."},

     {date: "1944-12",
      desc: "The War dept. revokes the West Coast exclusion order against Japanese Americans."},
     {date: "1945",
      desc: "Hiroshima and Nagasaki are bombed. Japan surrenders."},
     {date: "1945",
      desc: "Japanese Americans are released and allowed to return to the West Coast."},
     {date: "1945",
      desc: "The War Brides Act allows foreign-born wives of U.S. citizens who had served in the U.S. armed forces to enter the U.S."},
     {date: "1945",
      desc: "African American, Mexican, and Asian veterans of World War II return to face racism and segregation."},
     {date: "1945",
      desc: "6,000 Chinese women to enter United States as brides of American soldiers."},
     {date: "1946",
      desc: "The Luce-Celler Bill is signed into law granting right of naturalization and small immigration quotas to Asian Indian and Filipinos (100 a year)"},
     {date: "1946",
      desc: "All American internment camps for Japanese Americans are closed."},
     {date: "1946",
      desc: "Philippines gains independence from the U.S. Citizenship is offered to all Filipinos living in the U.S., not just servicemen."},
     {date: "1947",
      desc: "President Truman pardons all 267 Japanese American draft resisters"},
     {date: "1947",
      desc: "Amendment to 1945 War Brides Act allows Chinese American veterans to bring brides into the U.S. "},
     {date: "1947",
      desc: "Wataru \"Wat\" Misaka is drafted by the New York Knicks in the first round. He is the first person of color to play in the NBA."},
     {date: "1948",
      desc: "Alien Land Act repealed. In The People v. Oyama, the Supreme Court rules CA escheat action—where the state had tried to seize lands belonging to Japanese Americans—unconstitutional."},
     {date: "1948",
      desc: "Evacuation Claims Act authorizes payment of settlements to people of Japanese ancestry who suffered economic losses from internment: 10 cents is returned for every $1 lost."},
     {date: "1949",
      desc: "U.S. breaks off diplomatic ties with newly formed People’s Republic of China."},
     {date: "1949",
      desc: "5,000 highly educated Chinese in the U.S. granted refugee status after China institutes a Communist government."},
     {date: "1950",
      desc: "U.S. joins forces with UN on the side of the Republic of Korea (South). The Korean War begins, bringing many Korean war brides and orphans to the U.S."},
     {date: "1950",
      desc: "The McCurran Internal Security Act is passed. Its Title II provision, citing the incarceration of the Japanese Americans as a precedent, authorizes the President to incarcerate any person on mere suspicion without evidence."},
     {date: "1950",
      desc: "Anti-miscegenation legislation now includes not only unions between blacks and whites but also Mongolians, Malayans, Mulattos and Native Americans."},
     {date: "1951",
      desc: "United Refugee Convention is signed, defining rights of refugees, including protections for employment and welfare, on the issue of identity paper and travel documents. This Convention is amended in 1967 to apply to all people who become refugees after 1951"},
     {date: "1952",
      desc: "The California Supreme Court rules that alien land laws are racially discriminatory, violating the 14th amendment. The laws are repealed in 1956"},
     {date: "1952",
      desc: "The McCarren-Walter Immigration & Nationality Act goes into effect, repealing the National Origins Act of 1924 and allowing immigration quotas to Japan and other Asian countries, conferring rights of naturalization and eventual citizenship for immigrant Asians. The McCarren-Walter Act eliminates racial barriers to citizenship, but also tightens quotas for immigrants and allows deportation of immigrant for “subversive activities.”"},
     {date: "1952",
      desc: "The armistice ending the Korean War is signed."},
     {date: "1960-1975",
      desc: "U.S. military involvement in Vietnam, Laos, Cambodia"},
     {date: "1960",
      desc: "5.1% of all U.S. immigrants are from Asia – 75% are from Europe. 0.5% of the population is considered Asian/Pacific Islander – 88.6% is considered white (BRIDGE)"},
     {date: "1964",
      desc: "Congress authorizes President Johnson to take military action against North Vietnam. From 1964-1975, more than 500,000 U.S. soldiers are sent to Vietnam, Laos, Cambodia and Thailand. Two to three million Vietnamese are killed. The first wave of refugees move towards the U.S. through refugee camps."},
     {date: "1965",
      desc: "Although minor reforms in immigration law, due to changing international relations, allowed for limited numbers of Asians to enter the U.S. following the World War II era, U.S. immigration laws remained discriminatory toward Asians until 1965 when in response to the civil rights movement, non-restrictive annual quotas of 20,000 immigrants per country were established. For the first time in U.S. history, large numbers of Asians were able to come to the U.S. as families. “Family” is based on strictly heterosexual and nuclear ties. Law explicitly defines lesbians and gay as “sexual deviates.”"},
     {date: "1965",
      desc: "Korean immigration drastically increases in the wake of declining conditions in Korea."},
     {date: "1969",
      desc: "Student protests since 1968 lead to Asian American studies programs being established at some colleges. The U.S. secretly invades Cambodia as a strategy to destroy Viet Cong hideouts and supports. Over the next four years, literally tons of U.S. bombs are dropped on Cambodian villages and cities along the South Vietnam-Cambodia border, killing and injuring civilians with no formal declaration of war against Cambodia."},
     {date: "1969",
      desc: "Yoko Ono marries John Lennon"},
     {date: "1971",
      desc: "Title II of the McCurran Internal Security Act of 1950, which would have legalized detention camps, is repealed."},
     {date: "1971",
      desc: "South Vietnam surrenders to the Communist forces of the North."},
     {date: "1974",
      desc: "In Lau v. Nichols, the Supreme Court rules that failure to provide adequate education for non-English speaking students violates the Equal Protection Clause of the Constitution"},
     {date: "1975",
      desc: "The fall of Vietnam and Cambodia begins large-scale immigration of Vietnamese, Laotian, and Cambodian refugees to the U.S. More than 130,000 refugees enter the U.S. Boats are frequently attacked by pirates, who loot, beat and rape the refugees. Most refugees spend years in refugee camps and transit centers prior to arriving in the U.S."},
     {date: "1975",
      desc: "The end of the Vietnam war leaves approximately 30,000 American children in Vietnam. In contrast to the French response in 1954 after the end of the first Indochina war (France allowed repatriation of all Eurasians ~25,000, providing repatriation travel, educational opportunities and citizenship at age 18), the U.S. lacked policies to deal with the Amerasians fathered by U.S. serviceman and demonstrated no intention of recognizing these children. From the 1950s-1980s, Amerasian children endure severe trauma and persecution in Asian home countries."},
     {date: "1976",
      desc: "Executive order 9066 (signed in 1942) is officially rescinded."},
     {date: "1978",
      desc: "National convention of the Japanese American Citizens League adopts resolution calling for redress and reparations for the internment of Japanese Americans."},
     {date: "1979",
      desc: "A national Asian/Pacific American movement to unify all Asian Americans begins."},
     {date: "1979",
      desc: "Establishment of diplomatic relations between the People’s Republic of China and the U.S. reunites members of long-separated Chinese American families."},
     {date: "1979",
      desc: "The First Third World Lesbian and Gay Conference are held in Washington, DC in conjunction with the First March on Washington for Gay and Lesbian rights. The Conference has an Asian contingent “made up of lesbians and gay men of Chinese, Japanese, Indonesian, Indian, Malaysian, and Filipino backgrounds from North America, Asian, and the Caribbean.”"},
     {date: "1980",
      desc: "Jimmy Carter signs the refugee Act of 1980 into law; it enables greater numbers of refugees to enter the U.S.  19.3% of all U.S. immigrants are from Asia – 39% are from Europe.  1.5% of the U.S. population is considered Asian/Pacific Islander – 79.6 is considered white Not Hispanic."},
     {date: "1980",
      desc: "INS announces new policy on homosexuality: If an immigrant admitted that s/he was homosexual to an INS inspector, s/he is excluded from entering the U.S. If a homosexual person denied that s/he was homosexual, but was later found out, s/he could be deported for perjury."},
     {date: "1981",
      desc: "Taiwan is granted a separate immigration quota to facilitate family reunifications."},
     {date: "1981",
      desc: "The KKK of Texas burns boats symbolizing their opposition to Vietnamese refugee resettlement programs."},
     {date: "1982",
      desc: "Vincent Chin, a 27-year-old Chinese American in Detroit, is bludgeoned to death by 2 unemployed autoworkers, Robert Ebens and his stepson Michael Nitz, who blamed layoffs on the Japanese and mistook Chin as Japanese. The 2 men receive probation at their trial in 1983. This prompted Chinese Americans to organize politically. Later in 1987, the case was heard in civil court and Ebens was acquitted and the civil suit was settled out of court for $1.5 millions."},
     {date: "1982",
      desc: "Chinese American architect and sculptor, Maya Lin’s design selected for the Vietnam Veteran’s Memorial"},
     {date: "1982",
      desc: "The Amerasian Act offers top-priority U.S. immigration to children in Korea, Vietnam, Laos, Cambodia, or Thailand who were known to have been fathered by U.S. citizens."},
     {date: "1982",
      desc: "Boston Chinatown Gate dedicated."},
     {date: "1983",
      desc: "The report of the Commission of Wartime Relocation and Internment of Civilians, a committee investigating the WWII internment, is released. It concludes that exclusion, expulsion, and incarceration were not justified by military necessity and that the decision was based on race prejudice, war hysteria, and a failure of political leadership."},
     {date: "1984",
      desc: "Thong Hy Huynh is stabbed to death at Davis (CA) High School by 2 white students who had been taunting her and 3 other Vietnamese students with racial epithets for weeks."},
     {date: "1984",
      desc: "President Reagan endorses a plan for acceptance for admission of all Amerasians, qualifying mothers, and siblings over the next 3 years through the Orderly Departure Program (ODP). Between 1982 and 1988, 4,500 Amerasian children and 7,000 accompanying relatives are brought to the U.S."},
     {date: "1985",
      desc: "A Vietnamese restaurant owner in Boston, MA, is beaten by two Caucasian youths. The words “Gook sucks” were scratched into the restaurant window."},
     {date: "1986",
      desc: "The Immigration Reform & Control Act of 1985 is passed by the House of Representatives on October 17, 1987, and signed by the President on November 6, 1987. It raises the Hong Kong quota from 600 to 5,000 a year; and allows aliens who can prove that they were in the U.S. prior to January 1, 1982 to apply for temporary status and become U.S. citizens after seven years from the time of application. There are no changes in the preference system which allows for family reunification."},
     {date: "1987",
      desc: "A group of youths attack and kills Navroze Mody, an Indian man in Jersey City, NJ. The youths are allegedly affiliated with the “Dotbusters,” referring to the “dot” worn on the forehead of many Indian women."},
     {date: "1987",
      desc: "First formal signing of the Proclamation of Asian Pacific American Heritage Week by White House. "},
     {date: "1987",
      desc: "TIME Magazine publishes cover article entitled “The New Whiz Kids.” Many Chinese Americans express concern about a “model minority” stereotype."},
     {date: "1988",
      desc: "The U.S. Senate votes 69-27 to support redress for Japanese Americans, creating the Civil Liberties Act of 1988. President Reagan signs the Act that gives each surviving internee a tax-free compensatory payment of $20,000 and a letter of apology to each of the approximately 60,000 surviving persons."},
     {date: "1988",
      desc: "The Amerasian Homecoming Act allowed Amerasians born between 1962 and 1977 to immigrate to the U.S. Initially a 2-year plan allowing 30,000 Amerasians and immediate family members to immigrate, it was extended twice until all Amerasians who wished to immigrate could do so. The act gave immigrant status to Amerasians (as Vietnam had stopped ODP processing, because of objections to refugee status on the basis that refugees were persecuted by their country of origin) but granted refugee benefits including 6 months of language and culture orientation. The current law allows Amerasians to bring mothers, siblings, spouses, and children."},
     {date: "1989",
      desc: "U.S. reaches agreement with Vietnam to allow political prisoners to emigrate to the U.S."},
     {date: "1989",
      desc: "Patrick Purdy fires 105 rounds from an assault rifle at children in an elementary schoolyard in Stockton CA., killing five Southeast Asian children and then himself."},
     {date: "1990",
      desc: "President George Bush signs a proclamation declaring May as Asian/Pacific American Heritage Month. "},
     {date: "1990",
      desc: "The Immigration Act of 1990 thoroughly revamped the INA making allocation of visas more even among foreign nations, eliminating archaic rules, and increasing the level of worldwide immigration. This act welcomed skilled workers but limited their stay to 6 years. The act removed homosexuality as a reason to disqualify foreigners from immigration, or even visiting, the U.S."},
     {date: "1990-04-23",
      desc: "The Hate Crime Statistics Act is signed into law by President George Bush. The act requires the Department of Justice to collect and publish statistics for five years on hate crime motivated by prejudice based on race, religion, sexual orientation or ethnic origin. It is the first law to extend federal recognition to gay men and lesbians. (CQ)"},
     {date: "1992",
      desc: "An economic downturn in the U.S. causes a wave of Japan bashing"},
     {date: "1992",
      desc: "Korean businesses are looted and burned in riots in Los Angeles stemming from outrage over the Rodney King verdict."},
     {date: "1992",
      desc: "U.S. Bureau of the Census states: There were 39% more Japanese/white births than monoracial Japanese American births"},
     {date: "1994",
      desc: "Korean American comedian Margaret Cho is the first Asian American to star in her own television show: “All American Girl”."},
     {date: "1994",
      desc: "A joint resolution is passed by Congress to acknowledge the 100th anniversary of the overthrow of the Kingdom of Hawaii and to formally apologize to the Native Hawaiians for depriving them of their rights."},
     {date: "1996",
      desc: "Dr. David Ho is named TIME Magazine Man of the Year for his research into HIV/Aids"},
     {date: "1996",
      desc: "Clinton administration and Democratic National Committee involved in scandal because of alleged plan by China to influence the U.S. government through campaign donations."},
     {date: "1997",
      desc: "An estimated 6000+ international, transracial adoptees from Asian countries"},
     {date: "1997",
      desc: "Steven Chu, a Chinese American researcher at Stanford University, wins the Nobel Prize for Physics."},
     {date: "1998",
      desc: "Headline “American beats Kwan” when American-born-and-raised Chinese American skater Michelle Kwan comes in second after American-born-and raised White European American Tara Lipinski."},
     {date: "1998",
      desc: "The median net worth for Hispanic, African American, Asian and other minority families was $16,400. That was less than one-fifth the $94,900 median net worth for non-Hispanic white families"},
     {date: "1999",
      desc: "Taiwanese American scientist, Wen Ho Lee is unjustly accused of espionage, and imprisoned for three years before being cleared of all but minor charges."},
     {date: "1999",
      desc: "Dat Nguyen is drafted by Dallas Cowboys in 3rd round of NFL draft."},
     {date: "1999",
      desc: "Disney releases cartoon Mulan, who became the first Asian Disney princess. The issue with Mulan’s character illustrates Disney’s version of the stereotype “yellow peril” which is common in Hollywood stereotypes surrounding the Asian American community. While Mulan is depicted as a strong woman character, she is a whitewashed version of an Asian girl, growing up in Ancient China. Since the movie is the only example of an Asian princess, it leaves young girls confused about having this one limited “role model” to look up to."},
     {date: "2000",
      desc: "25.5% of all U.S. immigrants are from Asia – 15.3% are from Europe. 2 of the 3 countries sending the most immigrants to the U.S. are China with 45,652 and the Philippines with 42,474 (Mexico sent 173,914, India was a close fourth with 42,046)  3.6% of the U.S. population is considered Asian, 1% is considered Pacific Islander/Native Hawaiian – 75.1 is considered white Not Hispanic"},
     {date: "2001",
      desc: "Elaine Chao is appointed secretary of Labor by George Bush –the first Chinese American in the Cabinet. "},
     {date: "2001",
      desc: "An elderly Lao man, Thung Phetakoune, is murdered by a White man who called him Vietnamese and blamed him for the Vietnam war."},
     {date: "1985- 2002",
      desc: "Americans adopted more that 33,000 infants from the People’s Republic of China."},
     {date: "2001",
      desc: "Events of the Sept. 11 attacks in NYC set the stage for “national security” based immigration policy. Congress passes the PATRIOT Act, which gives the federal government broad powers to detain suspected “terrorists” for unlimited periods of time without access to legal representation. Over 1,2000 Arab, Muslim, and South Asian men are detained in secret"},
     {date: "2001",
      desc: "U.S. enters into deportation agreement with Cambodia."},
     {date: "2002",
      desc: "U.S. government demands “special registration” for men from 25 Arab, Muslim, and South Asian countries. Men who refuse to register face deportation. "},
     {date: "2002",
      desc: "Border Security and Visa Reform Act increases number of border patrol agents, and creates a centralized database for immigration and law enforcement. "},
     {date: "2002-04",
      desc: "A new line of T-shirts depicting stereotypes of Asians triggers an email and phone campaign to boycott Abercrombie & Fitch. Abercrombie said the shirts were supposed to be funny and cater to Asian customers. The company said it would pull the shirts from their 311 stores in 50 states. Slogans such as, \"Two Wongs can make it White\" or \"Get your Buddha on the Floor,\" partnered with stereotypical portrayals of Asian laundrymen wearing rice paddy straw hats and Asian woman with passive demeanor. "},
     {date: "2002",
      desc: "UCLA professor and Asian American activist, Yuji Ichioka dies. He is credited with coining the term “Asian American.”"},
     {date: "2003",
      desc: "Gary Locke inaugurated as governor of Washington – the first Chinese American governor in the United States."},
     {date: "2003",
      desc: "Chinese customers of Wondries Toyota bring a lawsuit against the dealership. Customers dealt with Wondries’ Chinese-speaking sales staff and signed contracts with terms that differed significantly from what they had negotiated, including exorbitant interest rates, excessive hidden charges, and signing lease contracts which they believed to be purchase contracts and vice versa. This lawsuit resulted in a new law in California which requires translation of particular contracts in Spanish, Chinese, Korean, Tagalog, and Vietnamese."},
     {date: "2003",
      desc: "Dept. of Homeland Security takes over responsibility for all immigration enforcement and security"},
     {date: "2005",
      desc: "Hurricane Katrina causes severe destruction, injuries, and death in U.S. Gulf Coast area affecting the large Vietnamese and Vietnamese American population there."},
     {date: "2005",
      desc: "Japanese American activist Yuri Kochiyama is nominated for Nobel Peace Prize."},
     {date: "2006",
      desc: "In Quincy, MA, four Chinese Americans (the “Quincy 4”) accuse officers of using excessive force during their arrest."},
     {date: "2007",
      desc: "Boston Chinese Immigrant Memorial completed in Mount Hope Cemetery in Mattapan."},
     {date: "2007",
      desc: "Ming Sun is first Chinese immigrant within U.S. forces killed in Iraq War. His parents are presented with a Bronze Star, a Purple Heart and papers granting him citizenship. (LA Times 1/28/07)"},
     {date: "2007",
      desc: "Gene Luen Yang wins Michael L. Printz Award for his graphic novel \"American Born Chinese.\" It is the first time the award is given to a graphic novel."},
     {date: "2007",
      desc: "Seung-Hui Cho, a Korean American student at Virginia Tech, shoots and kills 32 people, wounds many others, and commits suicide."},
     {date: "2007",
      desc: "Asian Indian American, Piyush \"Bobby\" Jindal is elected governor of Louisiana. He is the first non- white governor of LA since Reconstruction and the first Asian Indian governor."},
     {date: "2007",
      desc: "1.5 Million businesses are owned by Asian Americans. This is up 40% since 2002."},
     {date: "2008",
      desc: "CA Supreme Court overturns gay marriage ban—on June 17th, Asian American activist and Journalist, Helen Zia marries partner, Lia Shigemura, in San Francisco"},
     {date: "2008",
      desc: "Asian American Population Statistics: <ul><li>2.5 million people (age 5 and older) speak Chinese at home. “After Spanish, Chinese is the most widely spoken non-English language in the country. Tagalog and Vietnamese also have more than 1 million speakers.” <li>The projected percentage increase between 2000 and 2050 in the population of people who identify themselves as Asian is 213%. <li>33.4 million U.S. residents are projected to identify as Asian in 2050. That would be 8% of U.S. population.</ul>"},
     {date: "2008",
      desc: "Asian Americans participate in Summer Olympics in Beijing: Brian Clay (gold in decathlon), Jenny Lang Ping (coach of silver medal winning women’s indoor volleyball team), Liang Chow (coach of medal winning female gymnast Shawn Johnson), Raj Bhavsar and Kai Wen Tan (bronze medal winning male gymnasts)."},
     {date: "2008-01-22",
      desc: "The U.S. announces deportation agreement with Vietnam. Under the agreement, a Vietnamese citizen who arrived in the U.S. on or after July 12, 1995 who is determined to be deportable can be deported. Previous to the agreement, deportable Vietnamese citizens were allowed to stay in the U.S."},
     {date: "2009",
      desc: "Princeton University conducted a survey that found Asian Americans needed to score 140 points higher than whites for admission to top universities. This plays into the “model minority” myth that Asian Americans are portrayed as being more successful than their white counterparts in academic settings."},
     {date: "2009",
      desc: "Lou Dobbs, known as an anti-immigrant CNN anchor, resigned from his position thanks to the pressure instilled on him by organizations like “Present.org” and their “BastaDobbs” online campaign."},
     {date: "2009",
      desc: "Due to an increase in profiling and discrimination against Muslims and South Asian people, The Proteus Fund created the Security and Rights Collaborative. Their goal was to build national security as well as support the human rights of the community affected."},
     {date: "2009",
      desc: "5.2 million Asian Americans make up the total civilian labor force. Only 3% hold government jobs. According to the EEOC data, that’s 156,000 Asian American workers out of 3 million federal employees."},
     {date: "2010",
      desc: "Marriage statistics in the US showed the lowest rates of intermarriage for Asian males compared to Asian females. This is thought to be due to social dynamics such as racial preferences/discrimination, and the depiction that Asian American men are asexual. This is reinforced by TV shows, movies, and Hollywood standards that force women to view Asian American men as undesirable out of all ethnicities. "},
     {date: "2010",
      desc: "Steven Yuen, a South Korean American, stars in the AMC’s TV show, “The Walking Dead”. Yuen’s character is one of the few American mainstream characters that break the stereotypical Asian American roles such as model minority, perpetual foreigner, and martial arts, as well as gendered roles. His love interest is a White woman."},
     {date: "2010",
      desc: "President Obama appointed Peter M. Rouse as interim chief of staff, the first Asian American to hold this position."},
     {date: "2011",
      desc: "Alexandra Wallace, a White UCLA student posted a video to YouTube, ranting about Asian American students lack of “American manners”. The video went viral, and lead to other White students across the country to post other videos targeting the Asian American community."},
     {date: "2011",
      desc: "18.9 Million U.S. residents identify as Asian or Asian with a combination of another race. This composes 5.6% of the total population."},
     {date: "2011",
      desc: "Mazie Hirono, from Hawaii becomes the first Asian American female senator and the first female senator from Hawaii."},
     {date: "2012",
      desc: "Senate Candidate Pete Hoekstra releases an anti-Chinese, stereotypical and xenophobic Super Bowl ad. Lisa Chan, the actress in the ad, apologized for the stereotypical role she played. Hoekstra did not offer a direct or clear apology.."},
     {date: "2012",
      desc: "US Born NBA player Jeremy Lin becomes one of the few Asian American players represented in the NBA. Although he led the New York Knicks through a ten game winning streak off the bench, and started the movement of “Linsanity”, he was still patronizing as being a perpetual foreigner, openly stereotyped and patronized through mass media. Some of the names he was called were “two inch penis”, “fortune cookie”, “yellow mumba” FOB “and” kung fu grip."},
     {date: "2012",
      desc: "13% is the poverty level for Asian Americans. This went up from 10% in 2007."},
     {date: "2013",
      desc: "California’s KTVU broadcasted a segment on fake names of the pilots following the crash of Asian flight 214. These names were “Sum Ting Wong” “Wi Tu Lo” “Ho Lee Fuk” and “Bang Ding Ow”. To add insult to injury, the flight’s name was dubbed Fright 214 in media coverage. Turning this tragedy into a comedy funded by racial slurs, and offensive jokes, was disheartening to people affected by the plane crash."},
     {date: "2013",
      desc: "Los Angeles band, Day Above Ground, debuted their new song Asian Girlz. The video and lyrics were highly derogatory. The band claims that the song celebrated Asian women, but the overly sexualized actress in the video, Levy Tran, as well as the use of multiple stereotypes in the lyrics told another story. "},
     {date: "2013",
      desc: "ABC’s Jimmy Kimmel Live aired a new segment on Kid’s Table, where the concept was to kill everyone in China in order to alleviate the $1.3 trillion dollars the U.S. owes China. Kimmel apologized but did not admit he was in the wrong. This segment leads to boycotting of the Jimmy Kimmel show. A Chinese video went viral explaining why everyone in America shouldn’t kill everyone in China. The video was called “Undying Chinese” and highlighted the perseverance of the Chinese people."},
     {date: "2014",
      desc: "Avril Lavigne releases Hello Kitty, a music video featuring stereotyped Japanese girls as accessories and backdrops to Lavigne as she belts out words such as “kawaii” and “arigato”."},
     {date: "2014",
      desc: "Maj. Kurt Chew-Een Lee, the first Asian American U.S. marine officer dies at the age of 88. He was a decorated Korean War Veteran whose awards included the Navy Cross, the Silver Star, and two Purple Hearts."},
     {date: "2015",
      desc: "The First Asian American sitcom in 20 years debuted. “Fresh off the Boat” premiered February 4, 2015 on ABC. The series is based off of Eddie Huang’s life growing up, which is a chef and food personality. The show received mixed reviews, but, Huang felt that the pain he endured was washed over with lies and cheap comedy."},
     {date: "2015",
      desc: "Jeb Bush, Republican candidate for President “defends” his use of the offensive term “anchor baby” by saying that he had not meant to refer to or offend “Hispanics” and that \"anchor babies\" were \"frankly more related to Asian people.\""}]});

