/*global app */
/*jslint browser, white, fudge */

app.timelines.push(
  {timeline: "Latino/as", prefix: "L",
   credit: "Compiled by: Karen L. Suyemoto, Ph.D. – UMass (Boston) Psychology and Asian American Studies. Updated 2005/2006 by Claudia Fox Tree and Elli Stern for EMI Empowering Multicultural Initiatives. Updated 2014 by Emily Davis, for K. Suyemoto.",
   resources: [
       "The Hispanic-American Almanac: A reference work on Hispanics in the United States. Nicolas Kanellos, ed. Gale Research: Detroit, 1993",
       "Hispanic-American Almanac. Gale, 1997",
       "BRIDGE: Building a Race and Immigration Dialogue in the Global Economy. Eunice Hyunhye Cho, Miriam Ching Yoon Louie & Sasha Khokha. National Network for immigrant an refugee rights, Oakland, CA, 2004 (BRIDGE)",
       "Open Minds to Equality. Nancy Schniedewind & Ellen Davidsosn. Allyn & Bacon: Boston, 1998 (OME)",
       "http://www.college.emory.edu/culpeper/BAKEWELL/chronology.html Colonial Latin America Chronology",
       "http://www.wsu.edu/%7Edee/CIVAMRCA/TIMELINE.HTM Civilizations in America",
       "http://www.tolerance.org/teach/activities/activity.jsp?ar=708 Teaching Tolerance Timeline"],
  entries: [
    {date: "1200 BCE",
     desc: "The earliest civilization in Central America—and possibly the earliest civilization in the Americas—was the Olmec civilization which arose sometime between 1200 and 1000 BCE. They originally lived in the Gulf Coast region of southern Mexico, but soon expanded into Guatemala."},
    {date: "1000 BCE",
     desc: "Mayan civilization flourishes in the Yucatan peninsula and Guatemala. At its peak, Teotihuacán was a city of over one hundred thousand people, one of the largest cities in the entire ancient world. This civilization would dominate the culture of the valley of Mexico for almost a millenium and stands as the most significant cultural influence throughout the history of Central American civilizations."},
    {date: "1000 BCE",
     desc: "The earliest urban culture on the South American continent was the Chavín culture, so-called because its major site was found in the area of Chavín de Huantar. The Chavín culture arose in the highlands of northern Peru around 1000 BCE—about the same time as the Olmecs in Central America and thrived until 500 BCE. We know almost nothing about the Chavín; like the Olmecs, they worshipped a jaguar-man god which suggests there might have been some kind of cultural contact between the two."},
    {date: "600",
     desc: "After the decline of the Chavín civilization in northern Peru, the Andean regions were dominated by local urban cultures. In the Middle Horizon period (600-1000 AD), a new culture, the Huari-Tiahuanaco dominated the region and enforced cultural conformity. Scholars believe that the architecture and the social and political structure of the Incas ultimately derive from Huari-Tiahuanaco."},
    {date: "700",
     desc: "Teotihuacán is conquered by northern tribes/Nations and begins to rapidly decline in its influence over the Mexican peoples. For two hundred years following the decline of Teotihuacán, the region had no centralized culture or political control."},
    {date: "1000-1400",
     desc: "After the decline of the Huari-Tiahuanaco culture, the northern area of Peru was dominated by the Chimmu empire during the Late Intermediate period. The Chimmu produced many innovations in South American urban life: irrgation systems, canals, and highways, all of which would be adopted by the Incas when they ascended to regional dominance in the sixteenth century."},
    {date: "1320-1350",
     desc: "Tenochtitlan-Tlatelolco, the Aztec capital, begins to rise. The term, Aztec, is a startlingly imprecise term to describe the culture that dominated the Valley of Mexico in the fifteenth and sixteenth centuries. Properly speaking, all the Nahua-speaking peoples in the Valley of Mexico were Aztecs, while the culture that dominated the area was a tribe of the Mexica (pronounced \"me-shee-ka\") called the Tenochca (\"te-noch-ka\"). At the time of the European conquest, they called themselves either \"Tenochca\" or \"Toltec\", which was the name assumed by the bearers of the Classic Mesoamerican culture. The earliest we know about the Mexica is that they migrated from the north into the Valley of Mexico as early as the twelfth century AD, well after the close of the Classic Period in Mesoamerica."},
    {date: "1426-1428",
     desc: "Formation of the Triple Alliance, the basis of Aztec imperial expansion."},
    {date: "1440's",
     desc: "Start of Inca imperial expansion. The Incas were a distinct people with a distinct language living in a highland center, Cuzco. By the early sixteenth century, they exercised control over more territory than any other people had done in South American history. The empire consisted of over one million individuals, spanning a territory stretching from Ecuador to northern Chile.\nUnlike the military empires in Central America, the Incas ruled by proxy, incorporating local rulers into their imperial system after conquests."},
    {date: "1492",
     desc: "Columbus sails (see Native American chronology)"},
    {date: "1501-1502",
     desc: "East coast of South America surveyed by Amerigo Vespucci.. Portuguese exploration of Brazilian coast."},
    {date: "1508",
     desc: "From Hispaniola, Juan Ponce de León takes Puerto Rico."},
    {date: "1509",
     desc: "From Hispaniola, Juan de Esquivel takes Jamaica, and Alonso de Hojeda leads an expedition to the Venezuelan and Colombian coast."},
    {date: "1511",
     desc: "First Spanish town on the American mainland: Santa María la Antigua de Darién. Conquest of Cuba, from Hispaniola."},
    {date: "1511",
     desc: "Real Audiencia de Santo Domingo (the Royal Audiencia of Santo Domingo, first court of the Spanish crown in America) is established by decree of Ferdinand V of Castile."},
    {date: "1511",
     desc: "Sermon of Antonio de Montesinos, O.P., in Santo Domingo, criticizing colonists' treatment of Indians."},
    {date: "1512",
     desc: "Arrival of first bishop (of Caparra, Hispaniola) in America. "},
    {date: "1512",
     desc: "Laws of Burgos, the first code regulating Spanish treatment of Native People."},
    {date: "1512",
     desc: "The Jeronymite Fathers in La Espanola decide to save the decimated Arawak population by gathering them into missions. Soon, missions spread like wildfire throughout the Spanish Empire."},
    {date: "1513",
     desc: "Juan Ponce de León “claims” Florida for Spain. "},
    {date: "1513",
     desc: "Vasco Núñez de Balboa crosses the Isthmus of Panama to the Pacific."},
    {date: "1510",
     desc: "Diego Velazquez de Cuellar departs with more than three hundred men to conquer Cuba, and lands at Puerto Escondido. He is successful in defeating Arawak chieftain Hatuey’s guerilla raids"},
    {date: "1580's",
     desc: "Diseases have all but wiped out the Indians of Puerto Rico."},
    {date: "1630-1654",
     desc: "Dutch occupation of north-east Brazil."},
    {date: "1640",
     desc: "Beginning of large-scale sugar planting in non-Spanish Caribbean islands"},
    {date: "1760",
     desc: "After the Seven Years’ War, which united France and Spain against Britain, France ceded claims to all lands west of the Mississippi in order not to give them to the victorious British. Overnight, New Spain’s territory expands dramatically"},
    {date: "1766",
     desc: "The presidio of San Francisco is founded, becoming Spain’s northernmost frontier outpost."},
    {date: "1776",
     desc: "Declaration of Independence in the United States."},
    {date: "1800's",
     desc: "Cuban and Puerto Rican tabaqueros work in Boston in the 19th century as shop owners, factory, or farm workers. The South End Latino community is largely a bachelor society."},
    {date: "1803",
     desc: "France acquires the Louisiana Territory from Spain, which was ceded during the Seven Years’ War. Napoleon sells the vast territory to the U.S., expanding the borders of the infant nation to connect directly with New Spain"},
    {date: "1819",
     desc: "When Andrew Jackson leads a U.S. military force into FL, capturing 2 Spanish forts, Spain sells FL to the U.S. for $5 million."},
    {date: "1821",
     desc: "New Spain acquires independence from Spain, naming their nation the Republic of Mexico. By this time, Spanish colonies exist in coastal CA, southern AZ, south TX, and in most of NM and southern CO. Soon after Mexico gains independence, Anglo-American settlers begin to move into the Mexican territories of the present day U.S. Southwest, especially Texas"},
    {date: "1829",
     desc: "Slavery in Mexico is abolished"},
    {date: "1836",
     desc: "The Anglo settlers declare the Republic of Texas independent of Mexico. The Texas constitution stipulates that all residents living in TX at the time of the rebellion will acquire the rights of citizens of the new republic, but if they had been disloyal, these rights are forfeited. Numerically superior Anglos force Mexicans off their property and many cross over the border to Mexico"},
    {date: "1845",
     desc: "TX is officially annexed to the U.S."},
    {date: "1846",
     desc: "The U.S. invades Mexico under the banner of Manifest Destiny. The treaty of Guadalupe Hidalgo ends the Mexican War that same year. Under the treaty, half the land of Mexico is transferred to the U.S., including TX, CA, most of AZ and NM and parts of CO, UT and NV. The treaty gives Mexican nationals one year to choose U.S. or Mexican citizenship. 75,000 Hispanic people choose to remain in the U.S. and become citizens by conquest."},
    {date: "1853",
     desc: "General Santa Anna returns to power as president of Mexico and sells to the U.S. the region from Yuma (AZ) along the Gila River to the Mesilla Valley (NM)"},
    {date: "1855",
     desc: "Vagrancy laws and so-called “greaser laws” prohibiting bear-baiting, bullfights, and cockfights are passed, clearly aimed at prohibiting the presence and customs of Californios"},
    {date: "1857",
     desc: "Anglos businessmen attempt to run off Mexican teamsters in south Texas, violating the guarantees offered by the treaty of Guadelupe Hidalgo"},
    {date: "1862",
     desc: "Homestead Act is passed in Congress, allowing squatters in the West to settle and claim vacant lands, often those owned by Mexicans"},
    {date: "1868",
     desc: "Cubans leave for Europe and the U.S. in sizable numbers during Cuba’s first major attempt at independence"},
    {date: "1868",
     desc: "14th Amendment is adopted, declaring all people of Hispanic origin born in the U.S. as U.S. citizens"},
    {date: "1868",
     desc: "A decree in Puerto Rico frees all children born of slaves after this date. "},
    {date: "1870",
     desc: "All slaves who are state property are freed, as are various other classes of slaves."},
    {date: "1878",
     desc: "The Ten Years’ War, in which Spanish attempts to evict rebels from the eastern half of Cuba were unsuccessful, comes to an end with signing of the Pact of El Zajon, promising amnesty for the insurgents and home rule, and provides freedom for the slaves that fought on the side of the rebels"},
    {date: "1897",
     desc: "Spain grants Cuba and Puerto Rico autonomy and home rule"},
    {date: "1898",
     desc: "The U.S.S. Maine mysteriously blows up and President McKinley declares war against Spain. The U.S. military invades San Juan in pursuit of Spaniards and is welcomed by the cheering crowds, longing for independence."},
    {date: "1898",
     desc: "Spanish-American War. U.S. invades and occupies Cuba, the Philippines, Puerto Rico, and other Spanish colonies in the Pacific Islands. Hawaii is also annexed by force."},
    {date: "1898",
     desc: "Spain signs the Treaty of Paris, transferring Cuba, Puerto Rico, and the Philippines to the U.S."},
    {date: "1900",
     desc: "11.4% of all U.S. immigrants are from Northern American, including Mexico – 86% are from Europe"},
    {date: "1900s",
     desc: "Brutality against Mexican Americans in the Southwest is commonplace. Lynching and murders of Mexican Americans become so common in CA and TX that, in 1912, the Mexican ambassador formally protests the mistreatment and cites several brutal incidents that had recently taken place."},
    {date: "1900",
     desc: "The Foraker Act establishes a civilian government in Puerto Rico under U.S. dominance. The law allows for islanders to elect their own House of Representatives, but does not allow Puerto Rico a vote in Washington."},
    {date: "1902",
     desc: "The Reclamation Act is passed, dispossessing many Hispanic Americans of their land. Cuba declares its independence from the U.S."},
    {date: "1903",
     desc: "In Oxnard, Calif., more than 1,200 Mexican and Japanese farm workers organize the first farm worker union, the Japanese-Mexican Labor Association (JMLA). Later, it will be the first union to win a strike against the California agricultural industry, which already has become a powerful force."},
    {date: "1901",
     desc: "The Platt Amendment: the Cuban constitution allows the U.S. to set up military installations"},
    {date: "1904",
     desc: "The U.S. establishes the first border patrol as a way to keep Asian laborers from entering the country by way of Mexico and introducing the distinction between “legal” and “illegal” immigrants for the first time."},
    {date: "1910",
     desc: "The Mexican Revolution begins, with hundreds of thousands fleeing north from Mexico and settling in the Southwest."},
    {date: "1914",
     desc: "The Colorado militia attacks striking coal miners in what becomes known as the Ludlow Massacre. More than 50 people are killed, mostly Mexican Americans, including 11 children and three women."},
    {date: "1916",
     desc: "New Mexico enters the union as an officially bilingual state, authorizing funds for voting in both Spanish and English, as well as for bilingual education. Article XII of the state constitution also prohibits segregation for children of \"Spanish descent\". At the state's constitutional convention six years earlier, Mexican American delegates mandated Spanish and English be used for all state business."},
    {date: "1917",
     desc: "President Woodrow Wilson imposes US citizenship on Puerto Ricans to increase the pool of inductees for World War I."},
    {date: "1917",
     desc: "The Jones Act is passed, extending U.S. citizenship to all Puerto Ricans and creating 2 Puerto Rican houses of legislature whose representatives are elected by the people. English is decreed the official language of Puerto Rico"},
    {date: "1917",
     desc: "U.S. Congress passes the Immigration Act, imposing a literacy requirement on all immigrants, aimed initally at curbing the influx from southern and eastern Europe, but ultimately inhibiting immigration from Mexico"},
    {date: "1917",
     desc: "The Selective Service Act becomes law, obligating non-citizen Mexicans in the U.S. to register, even though they are not eligible for the draft"},
    {date: "1921",
     desc: "As the first of 2 national origin quota acts designed to curtail immigration from eastern and southern Europe and Asia is passed, Mexico and Puerto Rico become major sources of workers"},
    {date: "1917",
     desc: "The Confederación de Uniones Obreras Mexicanas (Federation of Mexican Workers Union-CUOM) in Los Angeles is formed, the first large-scale effort to organize and consolidate Mexican workers."},
    {date: "1929",
     desc: "With the onset of the Great Depression, Mexican immigration to the U.S. virtually ceases and return migration increases sharply"},
    {date: "1929",
     desc: "The League of United Latin American Citizens (LULAC) is founded in TX by frustrated Mexican Americans who find avenues for opportunity in the U.S. blocked. LULAC is the largest and longest-lasting Latino civil rights group in the U.S."},
    {date: "1929-1939",
     desc: "In the Great Depression, many Mexican workers are displaced by the dominant southern whites and blacks of the migrant agricultural labor force. U.S. government deports thousands of Mexicans, including many U.S. citizens, to Mexico."},
    {date: "1930",
     desc: "The U.S. controls 44% of the cultivated land in Puerto Rico, U.S. capitalists control 60% of the banks and public services, and all of the maritime lines"},
    {date: "1930-1934",
     desc: "Approx. 20% of the Puerto Ricans living in the U.S. return to the island."},
    {date: "1933",
     desc: "The Roosevelt Administration reverses the policy of English as the official language in Puerto Rico"},
    {date: "1933",
     desc: "Latino unions in California lead The El Monte Strike is organized by Latino unions in the Cannery and Agricultural Workers’ International Union to protest low wages for strawberry workers. Growers agree later that year to increase wages from 9 cents to 20 cents an hour."},
    {date: "1934",
     desc: "The Platt Amendment is annulled"},
    {date: "1940s-1950s",
     desc: "Unionization among Hispanic workers in the U.S. increases rapidly, as Hispanic workers and union sympathizers struggle for reform."},
    {date: "1941",
     desc: "WWII: Hispanics throughout the country enthusiastically respond to the war effort"},
    {date: "1941",
     desc: "The Fair Employment Practices Committee is created by the U.S. government to handle cases of employment discrimination. More than one-third of all complaints from the Southwest are from Latino workers"},
    {date: "1943-1964",
     desc: "On August 4, 1942, the U.S. and the Mexican governments instituted the Bracero program. Thousands of impoverished Mexican farm workers abandoned their rural communities and headed north to the southwestern part of the U.S. to work the fields once harvested by Americans who were off to war. The Bracero could return to their native lands in case of an emergency, only with written permission from their boss. When their contract expired, the Bracero were required to turn in their permits and return to Mexico. The Bracero Program brought in over 5 million temporary workers from Mexico, mostly to fill an agricultural labor shortage during World War II, but they also brought farming techniques and knowledge. The Bracero suffered harassment and oppression from extremist groups and racist authorities. The program ended in 1964."},
    {date: "1943",
     desc: "The “zoot-suit” riots are the worst race riots in Los Angeles to date and continue for 10 nights. American sailors target young Mexican Americans dressed in baggy paints and long-tailed coats (zoot-suiters), tearing off their clothes and beating them."},
    {date: "1944",
     desc: "On March 14, 1944, President Roosevelt agreed to accept the participation of one or two Mexican air squadrons. This event marked the first time the Mexican troops were trained for combat. Although only in the Philippines for six months, the squadron actively participated in 59 combat missions totaling over 1,290 hours of flight. They successfully participated in the Allied effort to bomb Luzon and Formosa in an attempt to push the Japanese out of the islands. Assigned to the 58th Fighter group of the U.S. 5th Air Force, the “Aztec Eagles” were also used as ground support after the aerial threat from Japan weakened."},
    {date: "1945",
     desc: "The War Brides Act allows foreign-born wives of U.S. citizens who had served in the U.S. armed forces to enter the U.S. African American, Mexican, and Asian veterans of World War II return to face racism and segregation."},
    {date: "1945",
     desc: "The US government encourages migration of Puerto Ricans to the US after World War II. In an effort to re-domesticate women who had joined the workforce during the war, Puerto Rican laborers were sought after to take their place."},
    {date: "1945",
     desc: "Mexican-American parents sue several California school districts, challenging the segregation of Latino students in separate schools. The California Supreme Court rules in the parents' favor in Mendez v. Westminster, arguing segregation violates children's constitutional rights. The case is an important precedent for Brown v. Board of Education in 1954."},
    {date: "1950",
     desc: "U.S. Congress upgrades Puerto Rico’s political status from protectorate to commonwealth"},
    {date: "1950s",
     desc: "Segregation is abolished in TX, AZ and other regions, largely through the efforts of LULAC and the Alianza Hispano Americana"},
    {date: "1950s",
     desc: "Immigration from Mexico doubles from 5.9% to 11.9%"},
    {date: "1950s-1960s",
     desc: "As more and more Puerto Ricans commit to remaining on the U.S. mainland, they encounter a great deal of rejection, but at the same time demonstrate a growing concern for social and economic mobility."},
    {date: "1952",
     desc: "McCarren Walter Act eliminates racial barriers to citizenship, but also tightens quotas for immigrants and allows deportation of immigrant for “subversive activities.”"},
    {date: "1953-1958",
     desc: "Operation Wetback deports 3.8 million persons of Mexican descent. Only a small fraction of that amount are allowed deportation hearings. Many U.S. citizens are deported unfairly, arrested, or detained."},
    {date: "1954",
     desc: "In the landmark case of Hernandez v. Texas, the nation’s highest court acknowledges that Hispanic Americans are not being treated as equal to Whites. The Supreme Court recognizes Hispanics as suffering profound discrimination, paving the way for Hispanic Americans to use legal means to attack all types of discrimination throughout the U.S. It is also the first U.S. Supreme Court case to be argued and briefed by Mexican-American attorneys."},
    {date: "1959",
     desc: "The Cuban Revolution succeeds, Dictator Fulgencio Batista flees Cuba as Fidel Castro takes power, leading to mass emigration to the US."},
    {date: "1960",
     desc: "9.4% of all U.S. immigrants are from Latin America and 9.8% of all U.S. immigrants are from Northern America, including Mexico - 75% are from Europe"},
    {date: "1961",
     desc: "Aspira is founded to promote the education of Hispanic youth by raising public and private sector funds. U.S. invades Cuba in Bay of Pigs."},
    {date: "1962",
     desc: "César Chavez founds the National Farm Workers Association (NFWA), to organize impoverished migrant farm laborers in CA"},
    {date: "1963",
     desc: "Miami's Coral Way Elementary School offers the nation's first bilingual education program in public schools with funding from the Ford Foundation."},
    {date: "1964",
     desc: "Civil Rights Act of 1964: establishes affirmative action programs and prohibits discrimination on basis of gender, creed, race, or ethnic background in employment."},
    {date: "1960s-1970s",
     desc: "Young Mexican Americans seek a new identity while struggling for civil rights objectives. This struggle becomes known as the Chicano movement."},
    {date: "1965",
     desc: "The mostly Filipino American members of the AFL-CIO-affiliated Agricultural Workers Organizing Committee (AWOC), walk out on strike against Delano-area grape growers. They ask Chavez’s largely Latino NFWA to join the walkouts. On Sept. 16, Mexican Independence Day, the NFWA, with 1,200- member families, votes to join a strike. Thus begins the five-year Delano Grape Strike."},
    {date: "1965",
     desc: "US invasion of Santo Domingo marks the beginning of a massive migration to the US."},
    {date: "1965",
     desc: "Members of the Boston Demophil Center join demonstrators at the United Nations building in NY to picket against Cuba's persecution of homosexuals."},
    {date: "1965-10-10",
     desc: "Cuban Refugees Airlift begins. Cubans admitted under special quotas."},
    {date: "1965",
     desc: "Immigration and Nationality Act repeals the national origins quota system that favors European migration, leading to increased immigration from Latin America, Asia, and other regions."},
    {date: "1966",
     desc: "NFWA and the Filipino American AWOC merge to form the United Farm Workers and the union affiliates with the AFL-CIO, the national labor federation."},
    {date: "1966",
     desc: "Hundreds of Chicago Puerto Rican youths riot. Ostensibly, the riots are in response to an incident of police brutality, but the underlying causes are broader, linked to the urban blight that characterizes their life in Chicago"},
    {date: "1966",
     desc: "More than 250,000 Cubans are airlifted to the U.S. Congress passes the Cuban American Adjustment Act allowing Cubans who lived in America for at least one year to become permanent residents."},
    {date: "1968",
     desc: "Chavez and United Farm Workers organize a grape boycott in support of the striking grape workers. An estimated 17 million American consumers went without grapes in support of the farm workers bargaining position. The boycott is ultimately successful in forcing growers to accept the union and address their demands."},
    {date: "1968",
     desc: "Chavez engages in a 25-day fast to protest the violence associated with the grape workers strike (violence from both sides)."},
    {date: "1968",
     desc: "In Los Angeles, Latino high school student organize city-wide walkouts. Previously, Latino students were not allowed to use the bathroom during lunch, discouraged from applying to college, and punished for speaking Spanish on school property. Police respond with brutality: 13 students are arrested. The walkouts impact school reform and increased college enrollment in Latinos."},
    {date: "1968",
     desc: "The Mexican American Legal Defense and Education Fund, the first legal fund dedicated to the civil rights of Mexican Americans, opens."},
    {date: "1969",
     desc: "Puerto Rican youth in Chicago form the Young Lords Organization. Modeled after the Black Panthers, and an outgrowth from the Young Lords street gang, the organization uses direct action and education to focus public attention on Latino issues such as slums, poor schools, and unemployment. The YLO becomes an active community organization providing multiple services including free breakfast for children and health clinics and later spreads to New York City."},
    {date: "1970",
     desc: "Brutality against Mexican Americans continues. In Lopez v. Harlow, a police officer shoots and kills Lopez, allegedly in self-defense because he thought Lopez was going to throw a dish at him."},
    {date: "1970",
     desc: "Chavez calls for a nationwide boycott of non-union lettuce. Later this year, he is jailed in Salinas, Calif. for refusing to obey a court order to stop the boycott against Bud Antle lettuce."},
    {date: "1972",
     desc: "Ramona Acosta Banuelos become the first Hispanic treasurer of the United States."},
    {date: "1972",
     desc: "The Massachusetts Commissioner of Public Welfare appoints Orlando Del Valle as the Liaison to the Latino community. As Liaison, he serves on the boards of La Alianza Hispana, HOPE, Travelers Aid Society, and the Puerto Rican Entering and Settling Services."},
    {date: "1972",
     desc: "Chavez fasts for 25 days in Phoenix over a just-passed Arizona law essentially banning the right of farm workers to strike, boycott or organize. The fast and resulting UFW-sponsored grass roots campaigns transform politics in the heavily Latino state where Chavez was born, leading to the election of Latino governors."},
    {date: "1973",
     desc: "The right of Puerto Rican people to decide their own future as a nation is approved by the United Nations. In 1978, the United Nations recognizes Puerto Rico as a colony of the United States."},
    {date: "1973",
     desc: "The Labor Council of Latin American Advancement (LCLAA) forms to promote the interests of Hispanics within organized labor."},
    {date: "1974",
     desc: "Equal Educational Opportunity Act is passed and makes bilingual education available to Hispanic youth. According to the framers of the act, equal education means more than equal facilities and equal access to teachers. Students who have trouble with the English language must be given programs to help them learn English."},
    {date: "1975",
     desc: "The Voting Rights Act Amendment of 1875 makes permanent the national ban on literacy tests and makes bilingual ballots a requirement in certain areas."},
    {date: "1975",
     desc: "To educate farm workers about their newly-won rights, Chavez embarks upon his longest, and least known, march, a 1,000-mile 59-day trek from the Mexican border at San Ysidro north along the coast to Salinas and then from Sacramento south down the Central Valley to the UFW's La Paz headquarters at Keene, southeast of Bakersfield. Tens of thousands of farm workers march and attend evening rallies to hear Chavez and organize their ranches."},
    {date: "1978",
     desc: "The median income of Hispanic families below the poverty level falls from $7,238 in 1978 to $6,557 in 1987, controlling for inflation. The proportion of Hispanic children living in poverty rises by more than 45%."},
    {date: "1978-1988",
     desc: "Hispanic female participation in the work force more than doubles, to 3.6 million and 56.6% of Hispanic women"},
    {date: "1979",
     desc: "Political upheaval and civil wars in Nicaragua, El Salvador and Guatemala contribute to large migrations of refugees to the United States."},
    {date: "1980",
     desc: "6.4% of the U.S. population is considered Hispanic"},
    {date: "1980-1989",
     desc: "U.S. military intervention in El Salvador, Guatemala, Nicaragua, Grenada, Lebanon, Libya, Iran, and Panama"},
    {date: "1980s",
     desc: "The rates of immigration approach the levels of the early 1990’s: legal immigration during the first decade of the century reached 8.8 million, while during the 1980’s, 6.3 million immigrants are granted permanent residence. The immigrants are overwhelmingly young and in search of employment, and Hispanic immigrants continue to account for more than 30% of the total. 33.1% of all U.S. immigrants are from Latin America - 39% are from Europe"},
    {date: "1980s",
     desc: "Programs to apprehend undocumented immigrants are implemented, and reports of violations of civil rights are reported."},
    {date: "1980",
     desc: "The Refugee Act of 1980 removes the definition of refugee as one who flees from a Communist regime, thus allowing thousands of others to enter the United States as refugees."},
    {date: "1982",
     desc: "More than 250 churches provide “sanctuary” to Salvadoran and Guatemalan refugees"},
    {date: "1986",
     desc: "Congress enacts the Immigration Reform and Control Act, creating an alien legalization program. The program beings legal status to a large number of undocumented Hispanics (amnesty to 3 million undocumented residents), and makes it illegal for employers to hire undocumented workers."},
    {date: "1986",
     desc: "Chavez kicks off the \"Wrath of Grapes\" campaign to draw public attention to the pesticide poisoning of grape workers and their children."},
    {date: "1988",
     desc: "President Ronald Reagan appoints the first Hispanic Secretary of Education: Lauro F. Cavazos."},
    {date: "1988",
     desc: "At age 61, Chavez conducts his last, and longest, public fast of 36 days in Delano to call attention to farm workers and their children stricken by pesticides."},
    {date: "1989",
     desc: "Immigration from the Americas rises from 44.3% in 1964 to 61.4%. Of the major countries, Mexico accounts for 37.1% of total documented immigration, the next highest number of immigrants being from El Salvador, 5.4%"},
    {date: "1989",
     desc: "Median family income for whites is $35,210; for blacks, $20,210; and for Hispanics, $23,450. Per capita income is $14,060 for whites, $8,750 for blacks, and $8,390 for Hispanics. 38% of Hispanic children living in poverty."},
    {date: "1989",
     desc: "Miami's Ileana Ros-Lehtinen, a Cuban American, becomes the first Latino woman elected to the U.S. House of Representatives."},
    {date: "1990",
     desc: "George Bush appoints the first woman and first Hispanic surgeon general of the U.S.: Antonia Novello"},
    {date: "1991",
     desc: "Unemployment among U.S. Hispanics reaches 10.3%, roughly double the rate for whites."},
    {date: "1991",
     desc: "The proposed North American Free Trade Agreement between Mexico, the United States and Canada expands even further the maquiladora concept, offering potentially greater tax abatements for U.S. businesses. A maquilladora is a manufacturing operation where a factory imports raw material and equipment on a tariff-free and duty-free basis, then exports the product, sometimes back to the country of origin."},
    {date: "1991",
     desc: "Despite the U.S. Congress’ refusal to consider the statehood of Puerto Rico, a referendum is held on the island, clearly showing that the population is in favor of statehood."},
    {date: "1991",
     desc: "AIDS Action Committee conducts an outreach campaign on Boston’s public transit system to Latino men who have sex with men."},
    {date: "1993",
     desc: "President Bill Clinton names Federico Pena to the position of Secretary of Transportation and names Henry Cisneros to the cabinet position of Secretary of Housing and Urban Development; They are the first Latinos to hold those posts. He also appoints Norma Cantu, to the position of Assistant Secretary for Civil Rights, Department of Education. The president also appoints 25 Hispanics to positions that need confirmation by the Senate."},
    {date: "1993",
     desc: "The U.S. government implements a blockade strategy along the U.S. Mexico border, forcing migrants to cross through the desert: Operation Gatekeeper (CA), Operation Safeguard (AZ), and Operation Blockade/Hold The Line (TX). By 2003, over 3,000 people have died while trying to cross the border"},
    {date: "1993",
     desc: "César Chavez dies."},
    {date: "1994",
     desc: "Californians pass Proposition 187 with 59% of the vote. The initiative bans undocumented immigrants from receiving public education and public benefits such as welfare and subsidized health care, except in emergency circumstances; makes it a felony to manufacture, distribute, sell or use false citizenship or residence documents; and requires teachers, doctors and other city, county, and state officials to report suspected and apparent illegal aliens to the California attorney general and the INS."},
    {date: "1994",
     desc: "Governor Pete Wilson issues an executive order for state officials to begin following the initiative by cutting off services to undocumented pregnant women and nursing home patients."},
    {date: "1994",
     desc: "California, Federal District Court Judge William Mathew Byrne Jr., temporarily blocks the enforcement of Proposition 187, stating that it raises serious constitutional issues. He exempts the provisions that increase penalties for manufacturing or using false immigration documents."},
    {date: "1994",
     desc: "President Bill Clinton posthumously presents the Medal of Freedom, America's highest civilian honor, to César Chavez."},
    {date: "1995",
     desc: "A nationwide boycott of ABC-TV by Hispanic Americans is held in Los Angeles, New York, Chicago, Houston, San Francisco and Fresno, in protest of the network’s failure to provide Latino themed programming in its 1994 line-up."},
    {date: "1995",
     desc: "Federal Judge Mariana Pfaelzer rules that Proposition 187 is unconstitutional."},
    {date: "1995",
     desc: "Spic Out, Theater Offensive's Latino theater festival is featured on the WGBH show La Plaza. In this show, La Plaza explores the individual experiences of the artists and presents selected excerpts from each performance."},
    {date: "1996",
     desc: "Proposition 209, introduced as a ballot initiative, is passed by the California voters. The initiative bars preferential treatment based on race or gender, virtually eliminating affirmative action in state hiring, public contracts, and education. Although challenged in the court, the U.S. Supreme Court refused to hear the appeal, and Proposition 209 eventually takes effect in California."},
    {date: "1996",
     desc: "Luiz Villalona-Perez files a petition in Massachusetts for political asylum from the Dominican Republic on the grounds that he would be imprisoned or killed there for his homosexuality. He is backed by human rights groups."},
    {date: "1997",
     desc: "Nicaraguan Adjustment and Central American Relief Act (NACARA) allows Nicaraguans and Cubans who have been in the U.S. since Dec. 1, 1995 to apply for permanent residence. Salvadorans, and Guatemalans can legalize if they have been in the U.S., since 1990 and could prove extreme hardship if deported."},
    {date: "1997",
     desc: "A U.S. District Court judge overturns California's Prop 187, ruling it unconstitutional."},
    {date: "1998",
     desc: "California voters pass Proposition 227, which bans bilingual classroom education and English as a second language programs, replacing them with a one-year intensive English immersion program. A federal judge denies challenges to the proposal and Proposition 227 goes into effect in California schools."},
    {date: "1998",
     desc: "The median net worth for Hispanic, African American, Asian and other minority families was $16,400. That was less than one-fifth the $94,900 median net worth for non-Hispanic white families."},
    {date: "1999",
     desc: "Hispanic groups join the NAACP protesting the lack of minority roles in prime-time shows in the fall line-up and urging viewers to participate in a national brownout of ABC, CBS, FOX and NBC the week of September 12, to coincide with Hispanic heritage Week. Increased hiring of minority actors for add-on roles in fall shows is noted."},
    {date: "1999",
     desc: "After 60 years of U.S. Navy exercise-bombings on the Puerto Rican island of Vieques, the accidental death of a Puerto Rican naval base employee catalyzes Puerto Rican residents to protest live ammunition exercises on the island, environmental destruction, and health problems related to bombing exercises. Over 180 protesters are arrested. The protests lead to lawsuits and the Navy promises to stop bombing by 2003."},
    {date: "2000",
     desc: "California makes Cesar Chavez Day a full, paid holiday for state employees. Texas currently has the holiday on a “volunteer” status."},
    {date: "2000",
     desc: "51% of all U.S. immigrants are from Latin America – 15.3% are from Europe. 12.5% of the U.S. population is considered Hispanic. Top countries sending immigrants to the U.S. are Mexico (173,914) China (45,652), the Philippines (42,474) and India (42,046)"},
    {date: "2000",
     desc: "Hispanic web presence grows. Spanish-language web sites are expected to grow exponentially over the next few years."},
    {date: "2000",
     desc: "Arizona passes a new English immersion law similar to California’s Proposition 227"},
    {date: "2001",
     desc: "The attacks on the World Trade Center on 9/11 results in increasing fears about border security. Some politicians call for building a wall between the United States and Mexico."},
    {date: "2002",
     desc: "Massachusetts passes a new English immersion law similar to California’s Proposition 227. Massachusetts is the third state in the nation where voters adopted such a law."},
    {date: "2002",
     desc: "Border Security and Via Reform Act increases number of border patrol agents, and creates a centralized database for immigration and law enforcement (src BRIDGE)"},
    {date: "2003",
     desc: "Dept. of Homeland Security takes over responsibility for all immigration enforcement and security. "},
    {date: "2003",
     desc: "Latinos are pronounced the nation's largest minority group --- surpassing African Americans --- after new Census figures show the U.S. Latino population at 37.1 million. The number is expected to triple by the year 2050."},
    {date: "2006",
     desc: "The “Day without immigrants” protest is organized and hundreds of thousands of Latino immigrants and supporters boycott work, school, and shopping to illustrate the necessity of the contributions of immigrants."},
    {date: "2006",
     desc: "Congress debates legislation to criminalize undocumented immigrants."},
    {date: "2006+",
     desc: "Immigration raids and deportation cases significantly increase, affecting Latino individual, families, and communities across the United States."},
    {date: "2006-12",
     desc: "The US government, Homeland Security, and the Immigration Customs Enforcement (ICE) raided and kidnapped migrants across the states of Colorado, Nebraska, Texas, Utah, Iowa, and Minnesota. 1,282 workers were arrested at various Swift Corporation worksites."},
    {date: "2007-01 ",
     desc: "Federal officials announced the arrest of 761 undocumented migrants in the Los Angeles metropolitan area and 24 in Baltimore, Maryland."},
    {date: "2007-02",
     desc: "In a nationwide sweep across 17 states and the District of Columbia, immigration officials arrested close to 200 undocumented migrants working for a janitorial company."},
    {date: "2007-03",
     desc: "Immigration raid in New Bedford, MA devastates the community with over 361 workers facing deportation at the end of the day and an estimated 100-200 children separated from parents with no warning or recourse. 90 workers are moved to Texas before being able to be interviewed by DSS about their status as parents."},
    {date: "2008-08",
     desc: "ICE conducts the largest single-workplace immigration raid in U.S. history in Laurel, Miss. The raid caused panic among Hispanic families in the area after federal agents detained at least 600 workers. Workers were taken to immigration detention facility in nearly 200 miles from their homes and family, and only some parents were released to return to their children with monitoring devices. The ACLU received reports that workers were segregated by race or ethnicity and interrogated, denied counsel, and that family members and lawyers were not informed about where the workers were being held. The ACLU begins investigating the ICE’s conduct."},
    {date: "2009",
     desc: "A research project funded by the Southern Poverty Law Center interviewed low income Latino families from Georgia, Charlotte, New Orleans, and Alabama found horrific personal stories about violation of human rights and racial discrimination. One new mother was arrested and jailed for asking for a paycheck from a cheese factory, a 13-year-old girl’s rapist went free because she was undocumented, and a man’s life savings was seized by the police during a traffic stop. These happened in Tennessee, Georgia, and Alabama, respectively."},
    {date: "2009",
     desc: "Sonia Sotomayor is appointed to the US Supreme Court, the first justice of “Hispanic” heritage and the third female justice."},
    {date: "2010",
     desc: "Arizona passes a law that allows police officers to check immigration status of any Latino that they suspect may be illegal. Supporters of the law claim that the law allows regulation of illegal immigration, yet human rights advocates express that the law is just allowing police officers to racial/ethnically profile Hispanics. The law creates tension between Hispanics and local law enforcement."},
    {date: "2010",
     desc: "Arizona Legislature passes law HB 2281 that targeted Mexican American classes, essentially outlawing ethnic studies. Governor Jan Brewer banned classes that “promote the overthrow of the United States government” or “promote resentment towards a race or class of people” which includes classes that are “designed for pupils of a particular ethnic group” that “advocates ethnic solidary instead of treatment of pupils as individuals”. In January, the Tuscan School District cut funds for any Mexican American school program."},
    {date: "2011",
     desc: "The number of “Hispanics” aged 18-24 enrolled in college exceeded 2 million for the first time, setting a record high 16.5% of college enrollments."},
    {date: "2012",
     desc: "After 2012 polls, the Latino population vote grew, and the need for immigration reform solely relies on GOP improvement in Latino and Asian American populations. The impreMedia/Latino Decisions’ elections poll found that 57% of Latino voters were “less enthusiastic” about Romeny’s opinions on immigration, and made support for the governor dwindle."},
    {date: "2012",
     desc: "Canyon County high school in Orange County was investigated after claims of “Senores and Senoritas” day is offensive. Students come dressed as stereotypical Latino roles, which include gang members, gardeners/housekeeping staff, and border patrol who “went around campus and arrested Mexican Students.”"},
    {date: "2013",
     desc: "Marc Anthony, the top selling salsa artist, sang “God Bless America” at the MLB All Star games. This sparked Twitter rants with racial epithets claiming that Anthony was not actually an American, despite the fact he was born and raised in New York."},
    {date: "2013",
     desc: "Hispanic’s are the largest minority group in the U. S. and is among the fastest growing population. The population was 53 million, which made up 17% of the U. S. Population."},
    {date: "2014-11-19",
     desc: "Obama made action on Immigration Reform. This contained three different sub-parts that included more accessible resources for immigrants, the president will make the citizenship process easier and faster for graduates, high skilled immigrants, and entrepreneurs and finally, to deal with the documentation of immigrants who already live in the country. Obama received negative feedback from the Republican party about giving aid to undocumented immigrants."}]});
