/*global app */
/*jslint browser, white, fudge */

app.timelines.push(
  {timeline: "Middle East and North Africa", prefix: "M",
   over: "MENA, Middle East and North Africa is a new group and countries that are included are Algeria, Bahrain, Egypt, Iran, Iraq, Jordan, Kuwait, Lebanon, Yemen, United Arab Emirates, Libya, Morocco, Oman, Palestine, Israel, Qatar, Saudi Arabia, Syria, Tunisia and sometimes Afghanistan, Armenia, Azerbaijan, Cyprus, Djibouti, Georgia, Mauritania, Somalia, Sudan and Turkey.\nMENA people are commonly associated with Arab Americans and Muslims although MENA is not exclusively made up of these associated groups. MENA is not a synonym for Arab Americans and/or Muslims. According to the American Arab Discrimination Committee (ADC), “Arab is a cultural and linguistic term. It refers to those who speak Arabic as their first language. Arabs are united by culture and by history. Arabs are not a race. Some have blue eyes and red hair; others are dark skinned; many are somewhere in between. Most Arabs are Muslims but there are also millions of Christian Arabs and thousands of Jewish Arabs, just as there are Muslim, Christian, and Jewish Americans” (2009). Muslims are a group united by religious identity, practices, and affiliation. MENA is an emerging racialized group, a group that shares experiences of categorization and discrimination based on the ways that they are being perceived by others. This timeline therefore includes diversity experiences of many groups of people that may or may not originally or currently self-identity specifically or primarily as MENA, but who are aggregated into this racialized group category.",
   credit: "",
   resources: [
       "http://cis.org/MiddleEasternImmigrantsProfile",
       "Bakalian & Bozorgmehr 2009",
       "Haiek, 2010",
       "http://www.biography.com/people/michael-debakey-9269009#synopsis",
       "https://www.stjude.org/about-st-jude/history.html",
       "https://www.accesscommunity.org/",
       "http://hds.harvard.edu/people/leila-ahmed",
       "Human Rights Watch: Crimes against Arabs, Muslims, and Those Perceived to be Arab or Muslim after 9/11, 2002",
       "http://www.sikhcoalition.org/images/documents/post_9.11_fact_sheet_revised.pdf",
       "http://www.asjournal.org/52-2008/challenges-facing-the-arab-american-community-from-a-legal-perspective/",
       "Nguyen, 2005",
       "https://www.aclu.org/infographic/guantanamo-numbers",
       "http://thejusticecampaign.org/?page_id=273",
       "http://ccrjustice.org/home/get-involved/tools-resources/fact-sheets-and-faqs/guant-namo-numbers",
       "http://www.imdb.com/name/nm0001724/bio?ref_=nm_ov_bio_sm",
       "http://www.arabamericanmuseum.org/",
       "https://en.wikipedia.org/wiki/Zaha_H",
       "https://www.brennancenter.org/sites/default/files/analysis/Boston%20Organizational%20Letter%20re%20CVE%20Concerns.pdf",
       "https://jacl.org/about/history/",
       "https://www.whitehouse.gov/the-press-office/2015/02/18/fact-sheet-white-house-summit-countering-violent-extremism",
       "http://www.aaiusa.org/2020census",
       "http://www.pbs.org/newshour/rundown/u-s-governors-dont-have-power-to-refuse-refugees-access-to-their-states/",
       "http://www.cityofboston.gov/news/default.aspx?id=20520"],
  entries: [
    {date: "1800",
     desc: "Maronite Christians from Lebanon, Armenians, and other Christian minorities from the Ottoman Empire began settling in the United States in significant number due to religious persecution."},
    {date: "1800",
     desc: "First major wave of Arab immigration due to civil wars. The majority were Christians. Syrians, Lebanese, and Palestinians were the first pioneers who landed in Manhattan, NY"},
    {date: "1890",
     desc: "Syrians and Lebanese began to move west. Some were attracted to Arizona during a mining boom."},
    {date: "1892",
     desc: "The first Arabic language newspaper in America (Kawkab America - Star of America) begins publication."},
    {date: "1896",
     desc: "Dr.Ibrahim Awad Qaloush Arbeely published the first Arabic-English grammar book to help Syrian immigrants learn English."},
    {date: "1910",
     desc: "U.S census Bureau classifies Syrians, Palestinians, Armenians, Turks and others from the eastern Mediterranean as “Asiatic.”"},
    {date: "1920's",
     desc: "In the 1920’s, Syrian children, especially Muslims, were called ”camel jockeys” “blacks” dirty Syrians and Turks. Some Arab Americans were able to pass as white but they were considered the ”most undesirable children of the undesirable peoples of Asia Minor.”"},
    {date: "1923",
     desc: "Famous poet Kahlil Gibran, a Lebanese-American authored The Prophet which gained popularity in the 1930s and sold more than 9 million copies in the U.S. Gibran is the third best-selling poet of all time, behind Shakespeare and Laozi."},
    {date: "1924",
     desc: "Asian Exclusion Act federal law bans immigration of people from Asia and the Middle East."},
    {date: "1932",
     desc: "Dr. Michael DeBakey, a Lebanese American, invented the heart pump which allowed for open heart surgeries. Dr.Debakey was also Chairman of the Department of Surgery at Baylor College of Medicine and served as Chancellor from 1979 to 1996."},
    {date: "1939-1945",
     desc: "It is estimated that at least 30,0000 GIs of Arab heritage fought for the United States against Hitler, Mussolini, and General Tojo of Japan."},
    {date: "1959",
     desc: "The American Arabic Association (AMARA) is founded in Boston to help find sponsors for Palestinian children.10"},
    {date: "1960s",
     desc: "90% of Arab immigrants were Christians and the prominent sects were Maronite Christians from Lebanon, Coptic Christians from Egypt, and Chaldeans from Iraq."},
    {date: "1962",
     desc: "Danny Thomas, a Christian Lebanese born as Amos Kairouz, founded St. Jude Children’s Research Hospital in Memphis, Tennessee. Thomas was also a comedian, singer and television actor."},
    {date: "1965",
     desc: "The Immigration and Naturalization Act of 1965, also known as the Hart-Celler Act, abolished quota systems based on national origins. This led to the second major wave of migration. The oil boom and anti-elitist and populist-socialist policies of Egypt, Syria, and Iraq lead minority populations like Jews, Greeks, Italians, Armenians, and Arab Christians to come to the United States."},
    {date: "1971",
     desc: "The Arab Community Center for Economic and Social Services (ACCESS) is founded as a nonprofit organization helping the large Arab immigrant population in Dearborn, Michigan. ACCESS helped create the Arab American National Museum, Center for Arab American Philanthropy, and the National Network for Arab American Communities."},
    {date: "1972",
     desc: "The National Association of Arab Americans (NAAA) is founded to act as a political lobby in Washington, D.C. on behalf of Arab Americans."},
    {date: "1973",
     desc: "James G. Abourezk becomes the first Arab elected to the U.S Senate. He was elected to the U.S house of Representatives from 1971-1973 and elected to the U.S Senate from 1973-1979. Founder and former national chairman of the 25,000 memberAmerican Arab Anti Discrimination Committee (ADC)."},
    {date: "1976",
     desc: "Steven ‘Steve’ Jobs, who is half Syrian, cofounds Apple Computers. Over his lifetime he serves as the chairman and CEO of the multinational technology company."},
    {date: "1979",
     desc: "Victor Atiyeh becomes the first Arab American elected governor in the U.S. and serves as governor of Oregon from 1979-1987."},
    {date: "1980",
     desc: "The American-Arab Anti-Discrimination Committee (ADC) was founded in Washington, D.C. by former U.S. Senator James Abourezk. In an attempt to inform the Arab and American public about anti-Arab propaganda, the ADC announced its winter 1980 program to combat media stereotyping and discrimination against Americans of Arab descent."},
    {date: "1981",
     desc: "The American-Arab Anti Discrimination Committee (ADC) announces a national campaign to protest ABC-TV’s anti-Arab bias, which was manifested in both news reporting and feature programs. The campaign was prompted by a number of recent ABC-TV news productions that displayed a clear anti-Arab bias. On August 6th 1981, ABC-TV’s “20/20” airs a special segment entitled “If You Were the President,” a staged study in crisis management at the White House. The ‘crisis’ to be managed is a fictitious Palestinian hijacking of an oil tanker in New York Harbor. The Palestinians threaten to blow up the tanker unless the U.S supports the creation of a Palestinian West Bank and gives the state $1 Billion. ADC regards this as toying with Palestinians by ABC [and] the most recent illustration of the deep and multilayered anti-Arab bias that prevails at ABC-TV."},
    {date: "1986",
     desc: "Public Radio, WDET-FM disseminates Arab culture programming across America. Arabesque: Insights into Arab Culture seeks to portray a positive image of the Arab American Community. Jack Shaheen, Professor of Communication at Southern Illinois University and author of numerous articles and books on the Arab stereotype in mass media, announced the national satellite distribution."},
    {date: "1987",
     desc: "Several Arab American organizations including the Washington based American-Arab Anti-Discrimination Committee (ADC) join in a successful protest against the manufacture and sale of the “Nomad” doll, a war toy in the Rambo doll collection manufactured by Coleco Industries. According to an ADC Action Alert, the series of Rambo dolls are based on a TV cartoon series which features Rambo as the “Force of Freedom” in a battle against a group of terrorists which includes the “Nomad.” The doll, wearing a headdress, is portrayed as a terrorist. The company halted the manufacture of the “Nomad” doll after the ADC said that it was racist and unfairly portrayed Arabs as terrorists."},
    {date: "1987",
     desc: "Representatives of major Arab American organizations including the American-Arab Anti-Discrimination Committee (ADC), the National Association of Arab Americans, the Arab American Press Guild, and others meet at the Arab Community Center in Los Angeles. A discussion is conducted about “Arab American Activism,” a historical perspective meeting the challenge of how to survive being an Arab American. The panel was coordinated by Sam Niazi, president of the Council of Arab American Organizations of Southern California."},
    {date: "1987",
     desc: "A report released by the American-Arab Anti-Discrimination Committee (ADC) places California second in the nation in the number of acts of ‘political hate andviolence’ against Arab Americans."},
    {date: "1987",
     desc: "Dr.James Zogby, President of the Arab American Institute (AAI), appears before the House Subcommittee on Census and Population to present long-standing Arab American concerns about U.S. Census reports regarding the number of people of Arab descent in the United States. The 1980 census, for example, significantly undercounted Arab Americans, reporting only 900,000 out of a total of over 2 million. The AAI’s testimony described the impacts that this undercount has on various Arab American communities including denying them access to government officials and services from government agencies."},
    {date: "1987",
     desc: "A suspicious fire is set at the Washington headquarters of the American-Arab Anti Discrimination Committee (ADC). Two people die in attacks on ADC offices: a police officer was fatally injured on August 16, 1987 when a bomb exploded outside the ADC’s Boston office and on October 11th 1985, a bomb at the ADC’s Santa Ana, California office killed Alex Odeh the organization’s Palestinian American regional director on the West Coast."},
    {date: "1990",
     desc: "The 1990 U.S. Census shows a high percentage of Arab men (79%) and women (73%) are intermarried. The first wave of Arab Americans included individuals from countries that were facing religious persecution, such as Christians. Since these Arabs had fair skin, blond hair and blue eyes, they had an easier time being accepted by the dominant groups in American culture."},
    {date: "1998",
     desc: "President Bush signed into law the Hate Crime Statistics Act, requiring the Justice Department to maintain statistics on acts of violence directed against members of racial, ethnic, and religious groups. This act was passed due to the efforts of a broad coalition of groups including the ADC, the American Psychological Association, the National Council of Churches, and the American Jewish Congress. At the ADC’s initiative, mosques were added to the list of institutions covered by the Hate Crimes Act."},
    {date: "1998",
     desc: "Hate crimes against Arab Americans increased when the U.S. and the Allied Forces launched a war against Iraq’s military, cities, and infrastructure, in its efforts to liberate Kuwait."},
    {date: "1993",
     desc: "Donna Shalala, the first Arab American appointed to a Cabinet secretary post by president Bill Clinton and the nation’s longest serving Secretary of Health and Human Services, becomes President of the University of Miami."},
    {date: "1997",
     desc: "The Office of Management and Budget revises the federal standard for the classification of race and ethnicity; it noted the lack of consensus about the definition of an Arab ethnic category and suggested that further research be done in order to improve data on this population group."},
    {date: "1999",
     desc: "Dr. Leila Ahmed, an Egyptian American, became the first Professor of women’s studies in religion at the Harvard Divinity School and was appointed to the Victor S. Thomas chair in 2003. Her latest book, A Quiet Revolution: The Veil's Resurgence, from the Middle East to America, has been widely acclaimed and was the winner of the Grawemeyer Award in Religion for 2012."},
    {date: "2001-09-11",
     desc: "The extremist terrorist group Al-Qaeda attacks the U.S. using hijacked airplanes. The first hijacked airplane flew into the North Tower of the World Trade Center, the second hijacked plane flew into the South Tower of the World Trade Center, the third hijacked plane flew into the Pentagon, and the last hijacked plane crashed into the ground near Shanksville, Pennsylvania."},
    {date: "2001-09-15",
     desc: "Start of attacks against persons who only appear, at least to some Americans, to be Middle Eastern, Arab, or Muslim. People who “appear” Muslim have also been attacked even though Muslims are found among all races, ethnic groups, and nationalities. In the context of U.S. hate-violence, however, “Muslim” has been equated with Middle Eastern or Arab. Sikh men who wear turbans have also been lumped with “Arab” terrorists and victimized. In short, a confluence of events in U.S. history leads to the construction of a new racial stereotype and target for bias, fear, and hate crimes: persons who are or appear to be “Middle Eastern, Arab or Muslim.”"},
    {date: "2001-09-15",
     desc: "Balbir Singh Sodhi, a Sikh, is shot in Mesa, Arizona at the gas station he owned. "},
    {date: "2001-09-15",
     desc: "Waqar Hasan, a Pakistani, is shot dead in his grocery store by Mark Anthony Stroman, a white supremacist, in Dallas, Texas."},
    {date: "2001-09-19",
     desc: "Ali Almansoop, a U.S. citizen of Yemeni descent, is shot in the back while escaping from his attacker who had broken into his home in Lincoln Park, Michigan."},
    {date: "2001-10-04",
     desc: "Vasudev Patel, a gas station owner from India, is killed during an armed robbery in Mesquite, Texas."},
    {date: "2001-10",
     desc: "In the first month after the 9/11 attacks, the Sikh Coalition documents over 300 cases of violence and discrimination against Sikh Americans throughout the United States. Sikhs practice a different religion than Muslims but due to the Sikh turban, beard, and appearing ‘brown’, which are some characteristics these two groups share, people often misidentify and conflate the two groups together. The victims of this violence are not limited to one nationality or religion."},
    {date: "2001-09-18",
     desc: "According to the organization South Asian American Leaders of Tomorrow (SAALT), 645 bias incidents were reported in metropolitan newspapers across the country in the week after 9/11. Many Arab and Muslim American individuals and organizations received threats, Arab Americans were denied entry on planes and had home loan applications rejected."},
    {date: "2001-09-11-2004-02-11",
     desc: "904 charges are filed with the Equal Employment Opportunity Commission (EEOC) alleging post-September 11-backlash discrimination. The charges in this category include national origin discrimination claims by an individual who are or who are perceived to be Muslim, Arab, Afghani, Middle Eastern or South Asian or individuals alleging retaliation related to the terror events."},
    {date: "2001-09-17",
     desc: "Immigration and Naturalization services changes the regulation regarding detentions. An alien can be detained without charge for 48 hours or “an additional reasonable period of time” if there was an “emergency or other extraordinary circumstance.” Many people draw a parallel between the internment of over 110,000 Japanese Americans after the Pearl Harbor attack with the detention and deportation of MENA people after 9/11."},
    {date: "2001-10-07-2014-12-28",
     desc: "War in Afghanistan in response to the September 11 attacks. The aim was to dismantle Al-Qaeda and remove the Taliban from power."},
    {date: "2001-11-07",
     desc: "President Bush creates the first foreign Terrorist Tracking Task Force, which will deny entry, detain, prosecute and deport anyone suspected of terrorist activity."},
    {date: "2001-11-16",
     desc: "The Department of Justice declares that identities and locations of 9/11 detainees will not be disclosed. By this time, it is believed there are at least twelve hundred such detainees, mostly Arab and Muslim men."},
    {date: "2002-01",
     desc: "Guantanamo Bay Detention Camp is established by Secretary of Defense, Donald Rumsfeld, to detain ‘extraordinarily dangerous people and prosecute detainees for war crimes’. Obama proposes to close Guantanamo Bay but it remains open. So far thre have been en through the Obamadespite president Obama’s proposal to close it. Since 2001, there have been about 800 detainees, all of whom were males aged 13-80 years old from countries including Afghanistan, Saudi Arabia, Yemen, Pakistan, Algeria, China, Algeria, and Russia.  More than 2,000 FBI agents havereported abusive treatment of Guantanamo prisoners.  Torture techniques included sexual assault/humiliation techniques such as being somodized with broomsticks, forcing undress, rape, threatening rape, being anally probed. Other torture techniques included sleep and sensory deprivation, sensory bombardment, solitary confinement/isolation, mock execution, forced medication, the use of dogs to scare detainees, temperature extremes, waterboarding, and watching others being tortured."},
    {date: "2014-12-31",
     desc: "The Pentagon has spent $5.242 billion on Guantanamo Bay Detention Camp so far."},
    {date: "2016",
     desc: "35 men are still imprisoned at Guantanamo after being cleared for release, and the number of prisoners the U.S. has said it lacks evidence to prosecute but claims are too dangerous to release is 28.  It costs approximately $454 million per year to keep Guantánamo open."},
    {date: "2002-01",
     desc: "The Department of Justice announces the Alien Absconder Initiative, purporting to identify and deport 315,000 undocumented people who have ignored court orders to leave the United States. Although theoretically applicable to all immigrants, the government announced that the program would begin with six thousand immigrants from Muslim countries."},
    {date: "2002-03-19",
     desc: "The Department of Justice announces interviews with three thousand more Arabs And Muslims in the United States as visitors or students."},
    {date: "2002",
     desc: "Tony Shalhoub, a Lebanese American, is the leading character named Adrian Monk in the TV show “Monk”. Shalboub also had roles in Men in Black and Men in Black II. The series made him a star and earned him four straight Emmy Award nominations between 2003 and 2006, for Outstanding Lead Actor in a Comedy Series which he won in 2003, 2005 and 2006."},
    {date: "2002-09-09",
     desc: "The Department of Justice asks more than two hundred colleges to provide information on their Middle Eastern students."},
    {date: "2002-09-11",
     desc: "New registration requirements are put into effect for noncitizens from Iraq, Iran, Syria, Libya, and Sudan."},
    {date: "2002-12-18",
     desc: "Hundreds of individuals from Iran and other Middle Eastern nations are arrested and held in Southern California when they come forward to comply with registration requirements. Immigrant groups estimate that more than five hundred people are jailed in Los Angeles, Orange County, and San Diego."},
    {date: "2003-04-29",
     desc: "A list of fifty-four nationalities is subject to port of entry ID procedures used by Bureau of Customs and Border Control inspectors. They are Afghanistan, Algeria, Angola, Argentina, Armenia, Bahrain, Bhutan, Brazil, Congo, Cyprus, Democratic Republic of Congo, Egypt, Eritrea, Ethiopia, Georgia, India, Indonesia, Iran, Iraq, Israel, Jordan, Kazakhstan, Kenya, Kuwait, Kyrgyzstan, Lebanon, Liberia, Malaysia, Mongolia, Morocco, Myanmar, Nepal, Oman, Pakistan, Panama, Paraguay, Philippines, Qatar, Republic of Yemen, Saudi Arabia, Somalia, Sri Lanka, Sudan, Syria, Tajikistan, Tunisia, Turkey, Turkmenistan, United Arab Emirates, Uruguay, Uzbekistan, and Venezuela. Of the fifty-four countries subjected to port of entry ID procedures, twenty-two are MENA countries."},
    {date: "2003",
     desc: "Zaha Hadid becomes the first Iraqi woman to design a major American art museum, Cincinnati’s $34 million Contemporary Art Center. She becomes the first woman recipient of the Pritzker Architecture Prize in 2004 and receives the Stirling Prize in 2010 and 2011. She dies March 31, 2016 at the age of 65."},
    {date: "2004-11",
     desc: "The National Network for Arab American Communities (NNAAC) is formed due to 9/11 backlash against Arab Americans with goals of understanding their needs and concerns at a local and national levels. The NNAAC will grow to 24 members in eleven different states including California, Massachusetts, Michigan, New York, Minnesota, Florida, Georgia, Texas, Illinois, Ohio and Pennsylvania. They also develop a partnership with ACCESS."},
    {date: "2005",
     desc: "The Arab American National Museum (AANM) is the first and only museum in the United States devoted to Arab history and culture.  Dr.Ameri Anan, a Palestinian American who emigrated from Amman, Jordan, is the director of the museum."},
    {date: "2006",
     desc: "Dalia Mogahed, an Egyptian American becomes Director of Research at the Institute for Social Policy and Understanding, a Washington D.C. and Dearborn, MI based research organization that supports American Muslim communities.  From 2006-2012 she chairs the Gallup Center for Muslim Studies and is selected by President Obama as an advisor to the White House Office of Faith-Based and Neighborhood Partnerships."},
    {date: "2006-10",
     desc: "In October, President Bush authorized the Military Commissions Act, further subjecting Guantanamo Bay detainees to laws that significantly deviate from the traditional U.S. standards of justice. By December 2006, over 750 individuals all labeled ‘enemy combatants’ were being held on the base without having been tried or even formally charged."},
    {date: "2007",
     desc: "The annual Boston Palestine Film Festival (BPFF) starts, attempting to bring Palestine-related cinema and culture to New England audiences."},
    {date: "2007",
     desc: "Preventing Violent Extremism (aka \"Prevent\"), is launched in the United Kingdom, targeting Muslims who were perceived as being radicalized through actions such as wearing a headscarf, having a beard, or praying five times a day; all of which are basic principles in Islam. In an effort to prevent extremism, government officials partner with local police enforcements, schools, hospitals but countering violent extremism (CVE) programs may violate First Amendment by targeting and surveilling people who express criticism towards U.S. policies and threaten American Muslims’ religious self-determination. Under Prevent, a lack of government transparency and accountability, heavy focus on gathering intelligence on Muslim communities and the policing of radical dissent have all resulted in diminished youth confidence in democracy. Prevent has also compromised Muslims’ ability to safely use social services, as its “Channel Program” has been extended to the health sector, eroding practices of doctor-patient confidentiality."},
    {date: "2011",
     desc: "The Japanese American Citizen League (JACL) joins with organizations including SAALT in objecting to hearing on “The Extent of Radicalization in the American Muslim Community” in the U.S. House of Representatives that targeted South Asian, Arab, Sikh, and Muslim Americans. Instead, Congress was called on to engage in objective dialogue about national security."},
    {date: "2011-08",
     desc: "The White House releases Empowering Local Partners to Prevent Violent Extremism in the United States, the first national strategy to prevent violent extremism domestically. The underlying premise of the approach to countering violent extremism (CVE) in the United States is that (1) communities provide the solution to violent extremism; and (2) CVE efforts are best pursued at the local level, tailored to local dynamics, where local officials continue to build relationships within their communities through established community policing and community outreach mechanisms. The pilot programs for CVE are in Greater Boston, Los Angeles, and the Twin Cities."},
    {date: "2013-04-15",
     desc: "Two pressure cooker bombs are detonated at the finish line during the Boston Marathon, killing 3 civilians and injuring an estimated 264 others. The suspects were identified later that day as Chechen brothers who were radicalized by extremist Islamist beliefs."},
    {date: "2013",
     desc: "A letter on behalf of a broad coalition of advocates and scholars was sent to the Office of Management and Budget in July to create a MENA category on the U.S Census because there is no ethnic category for Arab Americans. While the Census Bureau estimates the number of Arab Americans in the United States at 1.8 million, the Arab American Institute Foundation estimates that the total is actually closer to 3.7 million."},
    {date: "2014",
     desc: "The Muslim Justice League (MJL) is founded in Boston to defend human and civil rights against erosion in the ongoing ‘war on terror’."},
    {date: "2014",
     desc: "A meeting is held with the Director of the U.S. Census Bureau, John Thompson to put MENA on the 2020 U.S. Census."},
    {date: "2014",
     desc: "Take On Hate, a multi-year campaign is established. Its purpose is to challenge this country’s growing prejudice and stereotypes of Arab and Muslim Americans, including refugees of Arab and Muslim descent. The organization is led by the National Network for Arab American Communities (NNAAC)."},
    {date: "2014-10",
     desc: "The U.S. Census Bureau announces it will begin testing of a Middle East and North Africa (MENA) category in 2015 for possible inclusion on the 2020 Census. at the meeting of the National Advisory Committee, the Bureau states they have received a record number of positive comments in response to the Federal Register posting announcing the testing of the category."},
    {date: "2015-11-16",
     desc: "Many governors release statements refusing to accept refugees. Senator Ted Cruz (R-Texas) and Jeb Bush tell “CBS This Morning” that the U.S. screening process should only grant refugee status to Syrian Christians. Governors of Alabama, Arizona, Arkansas, Florida, Illinois, Indiana, Louisiana, Massachusetts, Michigan, North Carolina, New Hampshire, Ohio, Wisconsin, and others issue similar statements, promising to block Syrian refugees from entering their states."},
    {date: "2015-02-10",
     desc: "Deah Shaddy Barakat, Yusor Mohammed Abu-Salha, and Razan Mohammad Abu-Salha are shot execution-style outside their home. The case is debated as a hate crime or a dispute over a parking space."},
    {date: "2015-02-13",
     desc: "President Barack Obama issued a statement on the murders of Yusor Salha, Razan Salha, and Deah Barakat."},
    {date: "2015",
     desc: "Mariah Idrissi, half Moroccan becomes the first hijab-wearing model featured by H&M, the second largest retailer in the world."},
    {date: "2016-01-22",
     desc: "Outcry from residents of Flint, Michigan that the city water had toxic levels of lead from corrosive aging pipes. Levels of the heavy metal measured in city drinking water at the height of the crisis rose above the threshold for hazardous waste. Dr.Mona Attisha, an Iraqi immigrant, is credited for blowing the whistle on the Flint water crisis because she took the unconventional step of sharing the findings at a press conference."},
    {date: "2016-02-28",
     desc: "In Huntington Beach, California, Karam Jarrah and his brother-in-law, Asem Dghem, were speaking Arabic while walking home when they were approached and confronted by three adults. The situation escalated, and Karam was stabbed twice. Jarrah later told KABC-TV, \"Was it like a racial issue? Is it because we were speaking Arabic or it can be like just the way we look\"."},
        {date: "2016-02-17",
         desc: "Mayor Marty Walsh announces that the city of Boston would be receiving a $17.7 million grant from the U.S. Department of Homeland Security through the Urban Area Security Initiative (UASI) grant program. \"Whether natural or man-made, emergencies can happen anytime. This funding allows us to enhance the capabilities of our first responders, ensuring they are trained and prepared for any potential emergency or disaster,\" said Rene Fielding, OEM Director. UASI program funding addresses the unique multi-disciplinary planning, organization, equipment, training and exercise needs of high-threat, high-density urban areas, and assists them in building capabilities to prevent, protect against, respond to, and recover from threats or acts of terrorism. The City of Boston was designated as an UASI site in 2003."}]});
