/*global app */
/*jslint browser, white, fudge */

app.timelines.push(
  {timeline: "Native American", prefix: "N",
   credit: "Compiled by: Karen L. Suyemoto, Ph.D. – UMass (Boston) Psychology and Asian American Studies. Updated 2005/2006 by Claudia Fox Tree and Elli Stern for EMI Empowering Multicultural Initiatives. Updated 2014 by Emily Davis, for K. Suyemoto.",
   resources: [
       "The Native American Almanac: A Portrait of Native America Today. Arlene Hirschfelder & Martha Kreipe de Montano. Prentice Hall: New York, 1993",
       "A People’s History of the United States. Howard Zinn. New York: Harper-Collins, 1980",
       "BRIDGE: Building a Race and Immigration Dialogue in the Global Economy. Eunice Hyunhye Cho, Miriam Ching Yoon Louie & Sasha Khokha. National Network for immigrant an refugee rights, Oakland, CA, 2004 (BRIDGE)",
       "Native American FAQ’s Handbook. George Russell. Russell Publications: Phoenix, AZ, 2000 (FAQ)",
       "http://www.csulb.edu/projects/ais American Indian History and Related Issues",
       "http://www.indiancountry.com/",
       "http://teeksaphoto.org/Writing/WinterCount.html A Winter’s Count. Skip Schiel, 1992",
       "http://www.college.emory.edu/culpeper/BAKEWELL/chronology.html Colonial Latin America Chronology",
       "http://www.wsu.edu/%7Edee/CIVAMRCA/TIMELINE.HTM Civilizations in America"],
entries: [
    {date: "1200 BCE",
     desc: "The earliest civilization in Central America—and possibly the earliest civilization in the Americas—was the Olmec civilization which arose sometime between 1200 and 1000 BCE. They originally lived in the Gulf Coast region of southern Mexico, but soon expanded into Guatemala."},
    {date: "1000 BCE",
     desc: "Mayan civilization flourishes in the Yucatan peninsula and Guatemala. The earliest urban culture on the South American continent was the Chavín culture, so-called because its major site was found in the area of Chavín de Huantar. The Chavín culture arose in the highlands of northern Peru around 1000 BCE—about the same time as the Olmecs in Central America and thrived until 500 BCE."},
    {date: "600",
     desc: "After the decline of the Chavín civilization in northern Peru, the Andean regions were dominated by local urban cultures. In the Middle Horizon period (600-1000), a new culture, the Huari-Tiahuanaco dominated the region and enforced cultural conformity. Scholars believe that the architecture and the social and political structure of the Incas ultimately derive from Huari-Tiahuanaco."},
    {date: "700",
     desc: "Teotihuacán is conquered by northern tribes/Nations and begins to rapidly decline in its influence over the Mexican peoples. For two hundred years following the decline of Teotihuacán, the region had no centralized culture or political control. Beginning around 950, the Toltec culture based in northern Mexico at Tula began to dominate Central America. They were a war-like people and expanded rapidly throughout Mexico, Guatemala, and the Yucatán peninsula. At the top of their society was a warrior aristocracy which attained mythical proportions in the eyes of Central Americans long after the demise of their power. Around 1200, their dominance over the region fades."},
    {date: "900",
     desc: "Decline of classic Maya culture."},
    {date: "1000",
     desc: "Norsemen reach North America."},
    {date: "1000-1400",
     desc: "After the decline of the Huari-Tiahuanaco culture, the northern area of Peru was dominated by the Chimmu empire during the Late Intermediate period. The Chimmu produced many innovations in South American urban life: irrgation systems, canals, and highways, all of which would be adopted by the Incas when they ascended to regional dominance in the sixteenth century."},
    {date: "1320- 1350",
     desc: "Tenochtitlan-Tlatelolco, the Aztec capital, begins to rise."},
    {date: "1426-1428",
     desc: "Formation of the Triple Alliance, the basis of Aztec imperial expansion."},
    {date: "1440’s",
     desc: "Start of Inca imperial expansion."},
    {date: "1393",
     desc: "Castilian exploration of Canaries."},
    {date: "1492",
     desc: "Columbus lands on Caribbean island which he names San Salvador. There Native American population is over 5 million."},
    {date: "1494",
     desc: "Columbus initiated the enslavement of Native Americans by Europeans by sending more than 500 of them to Spain to be sold."},
    {date: "1501-1502",
     desc: "East coast of South America surveyed by Amerigo Vespucci.. Portuguese exploration of Brazilian coast."},
    {date: "1511",
     desc: "First Spanish town on the American mainland: Santa María la Antigua de Darién. Conquest of Cuba, from Hispaniola."},
    {date: "1511",
     desc: "Sermon of Antonio de Montesinos, O.P., in Santo Domingo, criticizing colonists' treatment of Native Americans."},
    {date: "1512",
     desc: "Arrival of first bishop (of Caparra, Hispaniola) in America."},
    {date: "1512",
     desc: "Laws of Burgos, the first code regulating Spanish treatment of Native People."},
    {date: "1512",
     desc: "The Jeronymite Fathers in La Espanola decide to save the decimated Arawak population by gathering them into missions. Soon, missions spread throughout the Spanish Empire."},
    {date: "1513",
     desc: "Juan Ponce de León claims Florida for Spain."},
    {date: "1510",
     desc: "Diego Velazquez de Cuellar departs with more than three hundred men to conquer Cuba, and lands at Puerto Escondido. He is successful in defeating Arawak chieftain Hatuey’s guerilla raids"},
    {date: "1600’s",
     desc: "Genocide of Native Americans begins, resulting in the death of over nine million Native Americans by 1700. Methods used to kill Native Americans during this genocidal period included lynching and the deliberate and inadvertent introduction of diseases by the colonists, forced migration and other tactics. This treatment of Native Americans continued into the 1700s, when many were captured and made to work on plantations with African American slaves."},
    {date: "1605-1619",
     desc: "English ships visit the New England coast, trading with and sometimes kidnapping Algonquins."},
    {date: "1607",
     desc: "Jamestown is founded."},
    {date: "1616",
     desc: "The English in VA, unable to raise their own food, tried to collect tribute from Native Americans, but the Chickahominy refused. The English invaded, captured, and killed several leaders, and forced the payment of tribute."},
    {date: "1620",
     desc: "Pilgrims land in Plymouth. MA."},
    {date: "1622",
     desc: "First major Native American retaliation. Chief Opechancanough of the Powhatan Confederacy, led the assault on the nearly 350 English settlers around Jamestown, Virginia."},
    {date: "1637",
     desc: "Pequot War between Pequots and European settlers, aided by some other Native American nations."},
    {date: "1649",
     desc: "The English Assembly at Jamestown (VA) ordered that Native American town boundaries be clearly marked and defined. This was a device whereby the whites would not have to recognize Native American title to any lands beyond the town boundaries."},
    {date: "1661",
     desc: "Spanish authorities raid Pueblo kivas (sacred ceremonial chambers) and destroyed hundreds of sacred Kachina masks and other sacred objects in an effort to destroy Native American “religion.”"},
    {date: "1675-1676",
     desc: "Southern New England Nations/tribes tried to halt English expansion. Metacomet gathered some 20,000 Native Americans who fought for a year against the New England colonists, but failed to win back their country. King Philip’s War was one of the bloodiest and most costly in the history of America. One in ten soldiers on both sides was injured or killed. Hundreds of Natives who fought with Philip were sold into slavery abroad. Others, especially women and children, were forced to become servants locally."},
    {date: "1675",
     desc: "Captain Benjamin Church of the Plymouth Colony militia led colonial forces against the Narragansetts in RI who were slaughtered or sold into slavery."},
    {date: "1680-1683",
     desc: "Aided by some Shawnee, the English in SC destroyed all but fifty of their allies, the Westos, in order to get slaves and better access to the interior. The survivors eventually joined the Creek."},
    {date: "1680",
     desc: "The Pueblo Rebellion, incited by eighty years of harsh treatment by the Spanish, results in the massacre of over four hundred soldiers, officers, and priests; the Southwest reverts to Native American country until 1692 when it is reconquered."},
    {date: "1681",
     desc: "William Penn’s “Noble Experiment”, the Quaker policy treating Native Americans fairly in the colony of Pennsylvania, lasts about 40 years."},
    {date: "1691",
     desc: "English people who married Native Americans, Blacks, or mulattos are banished from VA."},
    {date: "1717-1718",
     desc: "The English, French, and Spanish all tried to win over the Creek confederacy to secure its trade, but the Creek were not dominated by any European groups and became a powerful independent force."},
    {date: "1737",
     desc: "In Philadelphia, the “Walking Purchase Treaty” was signed by Penn. Colonists and Delaware’s Lappawinzo, Nutimus, and Sassoonan. According to convention, land was ceded by the Native Americans in terms of the distance a man could walk in a day. The English used trained ”walkers” who covered 67 miles in a day and a half, a distance far in excess of the Delawares’ intent."},
    {date: "1744",
     desc: "The Treaty of Lancaster. Virginia negotiators convinced the Six Nations to surrender their land to the \"setting sun\", which the Confederacy interpreted as the crest of the Alleghenies and the British interpreted as all of western Virginia. Following the Treaty of Lancaster and the end of King George's War (1748) between England and France, Virginia pioneers pushed west of the Alleghenies."},
    {date: "1750’s",
     desc: "Distilled liquor (fire water) is used by traders to entice agreements."},
    {date: "1763",
     desc: "The Ottawa leader Pontiac, and his pan-Native American confederacy, launched its attack on the English in the Great Lakes region with a surprise assault on Detroit. The alliance captured all British forts west of Niagara except for Fort Detroit and Fort Pit (Pittsburgh). At General Jeffrey Amherst’s suggestion, Henry Bouquet ordered the distribution of smallpox-infected blankets to the Native Americans near Fort Pitt."},
    {date: "1763",
     desc: "The British proclaim a boundary line between their “civilization” and “Native American Territory”— defined as “any lands beyond the heads or sources of any of the rivers which fall into the Atlantic Ocean from the West or Northwest.” By 1840, this line, inherited by the U.S., the Permanent Boundary, separates white controlled, “civilized” lands from the “Great American Desert”. It runs approximately from the Gulf of Mexico to Lake Michigan via the Mississippi River."},
    {date: "1765",
     desc: "Pontiac signs peace treaty with the British."},
    {date: "1769-1834",
     desc: "The first Spanish mission is constructed in California. By 1830, disease, brutality and other dietary and cultural changes had reduced the coastal native population from seventy thousand to twenty-four thousand. By 1840, six thousand Mission Native Americans were left, most of them serfs on large ranches."},
    {date: "1775",
     desc: "The first of 374 treaties is signed, recognizing the rights of Native Americans to land they occupy (the last, in 1869, forced Chief Joseph and his Nez Perce people off their lands)."},
    {date: "1775",
     desc: "Massachusetts legislation was signed that promised a bounty for every male “Indian” scalp obtained."},
    {date: "1776",
     desc: "Signing of the Declaration of Independence. The rationales for separating from England included that the King was inciting Indian attacks."},
    {date: "1776-1860’s",
     desc: "By 1800, the number of Native Americans had been reduced to about 600,000, due to policies of forced displacement and war. The white population of the U.S., however, increased to over 6 million in 1810, and the black population reached approximately one and half million."},
    {date: "1779",
     desc: "George Washington, because of his scorched earth campaign against Iroquois towns, becomes known as the \"town destroyer\". Upon his inauguration, he is the richest man in the new U.S., based on taking advantage of Indian land deals."},
    {date: "1783",
     desc: "American Revolutionary War ends."},
    {date: "1787",
     desc: "The Northwest Ordinance created the basis for the settlement of whites beyond the Alleghenies. It provided that the Native Americans’ land should never be taken from them without their consent."},
    {date: "1789",
     desc: "The U.S. War Department is created, in part, to handle all Native American matters."},
    {date: "1791",
     desc: "Nations/tribes in Ohio led by Miami Little Turtle annihilated the army of General Arthur Saint Clair, Governor of the Northwest Territory, near present-day Fort Wayne, Indiana."},
    {date: "1795",
     desc: "The Treaty of Greenville (Ohio) cedes nearly two-thirds of Ohio, part of Indiana, and other sites, including those of Chicago, Detroit, and Toledo. For this, the Native Americans receive $20,000 worth of goods and the promise of $9500 in annuities. Alcohol, hunger, and the threat of military force hasten the Native Americans’ decision."},
    {date: "1803",
     desc: "U.S. Louisiana purchase for $15 million."},
    {date: "1804",
     desc: "Over the course of the Lewis and Clark Expedition, the Corps of Discovery would come into contact with nearly 50 Native American Nations/tribes with diverse language, culture, and experiences with Europeans."},
    {date: "1810",
     desc: "Tecumtha, a Shawnee born in the Ohio region, tries to organize his people, saying,\"The way, and the only way, to check and to stop this evil [of white encroachment], is for all the red men to unite in claiming a common and equal right in the land, as it was at first, and should be yet; for it never was divided, but belongs to all, for the use of each... We must be united; we must smoke the same pipe; we must fight each other's battles; and more than all, we must love the Great Spirit; he is for us; he will destroy our enemies, and make all his red children happy."},
    {date: "1810",
     desc: "Under duress, the Cherokee, Choctaw, Creek, and Chickasaw of the Southeast and the Seminoles of Florida are forced to turn over their lands to Whites and relocate west."},
    {date: "1811",
     desc: "Native Americans defeated in Battle of Tippecanoe in Indiana Territory"},
    {date: "1812",
     desc: "First Seminole War"},
    {date: "1814",
     desc: "Creek Native American War"},
    {date: "1819",
     desc: "Congress sets up a program for the “civilization” of Native Americans. The funds are distributed among mission groups, enabling them to widen education programs"},
    {date: "1823",
     desc: "The U.S. Supreme Court upholds the concept of \"right of discovery\", claiming \"discovery gave exclusive title to those who made it\", providing legal justification for the confiscation of Native American lands. In Johnson v. McIntosh, the Supreme Court concludes that tribal sovereignty, although impaired by European colonization, cannot be dismissed."},
    {date: "1824",
     desc: "The War Department subsumes the newly created Bureau of Native American Affairs."},
    {date: "1830-1838",
     desc: "The Trail of Tears: At the request of President Jackson, Congress passes the Indian Removal Act, forcing 92 percent of all Native Americans living east of the Mississippi River to Native American territory west of the Mississippi. The Cherokees, Chickasaws, Yuchis, Creeks, Choctaws, and Alabamas are forced to give up their lands in the southeast Over 30% of the Cherokees die from disease and exposure in forced migration at gun point as they are moved from their homes in Georgia, the Carolinas, Alabama, Mississippi and Tennessee to Native American Territory (Oklahoma); the reservation system begins."},
    {date: "1831",
     desc: "Nat Turner leads a slave rebellion, inspiring fear of Native Americans and Blacks."},
    {date: "1831",
     desc: "George Catlin and Karl Bodmer both paint Native American portraits and landscapes showing the people as they were before White contact."},
    {date: "1831",
     desc: "The U.S. Supreme Court establishes that, in the words of Chief Justice John Marshall, \"(the Native Americans') relations to the United States resembles that of a ward to his guardian.\"\nIn Cherokee Nation v. Georgia, the court rules that Native American Nations/tribes are \"a distinct political society, separated from others, capable of managing [their] own affairs and governing [themselves].\""},
    {date: "1832",
     desc: "In Worcester v. Georgia, the third case of the trilogy, the court holds that tribal sovereign powers were not relinquished when Native American Nations/tribes exchanged land for peace or protection."},
    {date: "1835",
     desc: "Second Seminole War in Florida"},
    {date: "1842",
     desc: "Seminoles moved to Native American Territory"},
    {date: "1842",
     desc: "The opening of the Oregon Trail, the first interstate highway, brings thousands of settlers, with cattle, wagons, and other environmental effects that disrupt the buffalo migrations and spread disease."},
    {date: "1845-1870",
     desc: "Before the gold rush, Native Americans outnumbered whites by nearly ten to one. In the quarter century between 1845 and 1870, the California Native Americans population had declined from approximately 150,000 (which was only half the number of Native Americans before white contact) to 30,000. Between 1848 and 1880, whites killed at least 4,500 Native Americans. These numbers do not include the Native Americans who were driven away, died by disease, or starved to death. Exploitation of the Native Americans labor force in mines, destruction of their food supply by hunting and mining, and murder for racial and economic motives were the main reasons for the severe decline of the Native Americans."},
    {date: "1849-1885",
     desc: "Buffalo decimation. By 1885 the two great herds of 15 million buffalo are almost exterminated by white hunters seeking hides for money"},
    {date: "1851",
     desc: "The Treaty of Fort Laramie with the Plains Native Americans defined their territories. In return for ending hostilities, Native Americans were promised annuities, later cut down by the U.S. Senate. All Sioux land in Iowa is given to the United States"},
    {date: "1854",
     desc: "Chief Seattle (or Sealth, of the Suquamish) speaks of the interconnectedness of all life:\nTeach your children what we have taught our children, that the earth is our mother. Whatever befalls the earth befalls the people of the earth. If you spit upon the ground, you spit upon yourselves. This we know. The earth does not belong to people; people belong to the earth. His teaching becomes one of the most quoted 150 years later. But his land is taken by the Army, promised return when the military establishment to be built there is no longer needed. The land is never returned. It is developed later into private residences."},
    {date: "1854",
     desc: "Indian Appropriation Act: Congress has the authority to establish reservations (move specific nations to specific places-mostly south central area (representing Oklahoma)."},
    {date: "1856",
     desc: "Connecticut sells off 600 acres of the Pequot reservation without permission."},
    {date: "1861",
     desc: "The Paiutes in the Great Basin country (Nevada) are forced onto reservations, as Whites stream into the gold-rich lands."},
    {date: "1861",
     desc: "Native American units fought on both sides during the Civil War"},
    {date: "1862",
     desc: "The Santee Sioux of Minnesota, having suffered massive loss of land, rise up against white settlers, killing approximately 800 in one month. Some Sioux flee to Canada, others move or are forced west."},
    {date: "1862",
     desc: "The Homestead Act brings vast numbers of settlers on to public domain lands in KS and NE. Many settled on land belonging to Native American Nations/tribes and were certified as owners of the illegally taken land."},
    {date: "1863",
     desc: "Beginning in 1863 Christopher \"Kit\" Carson begins an economic war against the Navajo, leading marches through Navajo country to destroy crops, orchards, and livestock, leaving the Navajo vulnerable to attacks from the Utes, Pueblos, Hopis, and Zunis (Navajo traditional enemies)."},
    {date: "1864",
     desc: "Most Navajo surrender to Carson, who forces the “Long Walk” where 8,000 men, women, and children are marched 300 miles from Arizona to New Mexico. They were imprisoned until 1868, and then allowed to return to their homeland, now reduced to 1/5 the size of the original territory"},
    {date: "1864",
     desc: "Reversing previous policies, a federal law is passed allowing Native Americans to testify in trials involving white people."},
    {date: "1864",
     desc: "The Sand Creek massacre: over two hundred Cheyenne in Colorado are killed by the Cavalry."},
    {date: "1867",
     desc: "The U.S. buys Alaska from Russia."},
    {date: "1868",
     desc: "The Fort Laramie Treaty establishes the Great Sioux Reservation, from the Missouri River west to about the middle of what is now Wyoming, including the Black Hills, sacred lands of the Lakota, \"as long as the grass is green and the waters flow\"."},
    {date: "1869-1876",
     desc: "200 pitched battles between Native Americans and U.S. Cavalry"},
    {date: "1870’s",
     desc: "Quakers, among other Christian groups, supervise missions, establish boarding schools, and provide money for Native Americans."},
    {date: "1871",
     desc: "Congress ends treaty making with the Indian Appropriation Act.. Simultaneously, Congress voices its responsibility to honor all already \"lawfully made\" treaties."},
    {date: "1874",
     desc: "Gold is verified in the Black Hills by Custer's expedition."},
    {date: "1874",
     desc: "The federal government breaks the Fort Laramie Treaty to remove the Black Hills from Native American control, a reduction of the reservation to one quarter the original size."},
    {date: "1876",
     desc: "The Battle of the Little Big Horn, led by Crazy Horse, Two Moons, and other war chiefs, a combined force of between twelve and fifteen thousand Teton, Santee and Yankton Sioux, Cheyenne, Arapaho, Gros Ventre, and Assiniboine successfully resist forced removal to a reservation and kill Custer and about 200 of his Seventh Cavalry. Sitting Bull is present as a medicine man, and Black Elk as a 12 year old boy."},
    {date: "1877",
     desc: "Crazy Horse is murdered by Native American police, instigated by the U.S. government."},
    {date: "1877",
     desc: "Chief Joseph and his Nez Perce people surrender at Bear Paw Mountain in Montana. Nez Perce leave Idaho for Canada"},
    {date: "1877",
     desc: "A 500 mile forced march by the Poncas in Nebraska is the first Native American grievance to receive sympathetic national attention."},
    {date: "1877-09-28",
     desc: "In the East Room of the White House, Arapaho Chief Sharp Nose presents a pipe and tobacco pouch to President Rutherford Hayes. This was President Hayes's first meeting with a Native American delegation, which consisted of three Arapaho and twenty Sioux people."},
    {date: "1878",
     desc: "U.S. government establish Native American police forces for reservation supervision."},
    {date: "1879",
     desc: "Captain Richard Henry Pratt founded Carlisle Native American School in Penn with the aim to immerse Native Americans in European American culture. During vacations Pratt sent students to live and work with white families to increase assimilation."},
    {date: "1880’s",
     desc: "The last of the buffalo are shot from trains, killed for tongues and hides; over three and a half million buffalo are slaughtered in two years. ."},
    {date: "1883",
     desc: "Sarah Winnemucca publishes her book, Life Among the Paiutes, a tough-speaking chronicle of her dealings with Native American agents in Oregon and Nevada. She lectures widely throughout the East, detailing duplicity and greed."},
    {date: "1886",
     desc: "Federal policy forbids Native American language books or instruction."},
    {date: "1886",
     desc: "Geronimo (Apache) surrenders after 15 years"},
    {date: "1887",
     desc: "The General Allotment or Dawes Act, introduces private ownership of land to Native Americans, breaking up tribally-owned lands and dividing them among individuals, with the “surplus” sold to whites, sometimes at very low prices, by public officials. 118 reservations were divided; 38 million acres taken outright by the government, and 22 million declared 'surplus' and opened for settlement. An additional 23 million acres were sold between 1887 and 1934 by Native Americans in order to alleviate poverty or pay debts (including taxes on the now individually held land). In total, the Allotment Act cost Native Americans almost two-thirds of the land they had owned in 1887."},
    {date: "1890",
     desc: "The Ghost Dance appears, an attempt to resist white incursion through a combination of Christian and traditional Native American beliefs, non-violently, through a special form of dancing and singing that aims to roll back the earth, taking with it the settlers and their Iron Horses and Cavalry, and bringing back the buffalo, ancestors and native ways."},
    {date: "1890",
     desc: "The U.S. government again changes the treaty to reduce the Sioux Reservation to about 1/5 its original size."},
    {date: "1890",
     desc: "Sitting Bull, a Lakota chief, is killed by Native American Police under the direction of the Army. His people flee their homes for Pine Ridge Agency to counsel with Red Cloud and others. They are intercepted by the Seventh Cavalry and forced to camp at Wounded Knee Creek. Nearly 300 Lakota are murdered, mostly women, children, elders. This is the last of the outright massacres. The U.S. awards Medals of Honor to 18 soldiers for this action."},
    {date: "1892",
     desc: "Cherokee land in Indiana is opened for settlement."},
    {date: "1893",
     desc: "The 400th anniversary of Columbus’s landing: Columbus Day is proclaimed a national holiday, and in honor of the celebration, the Pledge of Allegiance is written."},
    {date: "1900",
     desc: "3% of the U.S. population is considered Native American/Indigenous – 87.9% is considered white"},
    {date: "1901",
     desc: "Five Civilized Tribes granted U.S. citizenship"},
    {date: "1902",
     desc: "The U.S. Commissioner of Native American Affairs prohibits “wearing of long hair by the male Native American population”"},
    {date: "1903",
     desc: "The descendents and community of Wounded Knee victims erect a memorial at the grave site."},
    {date: "1907",
     desc: "Edward Curtis publishes his first volumes of photographs of North American Natives, a nostalgic and elegiac view."},
    {date: "1910",
     desc: "The National Association for the Advancement of Colored People (NAACP) is formed."},
    {date: "1911",
     desc: "\"Pan-Native Americanism\" begins, October 12th, in Columbus Ohio, as fifty Native Americans launch the Society of American Indians. The Society later strongly opposed the segregation of 12,000 Native American soldiers during World War I."},
    {date: "1918",
     desc: "The Native American Church, blending Native American and Christian spirituality and using peyote, is organized and spreads rapidly. It advocates family cooperation and pan-Native American unity."},
    {date: "1924",
     desc: "U.S. citizenship was granted to Native Americans, giving them dual citizenship as members of Nations/tribes and as citizens of the United States."},
    {date: "1934",
     desc: "The Indian Reorganization Act of 1934, also known as the Wheeler-Howard Act or informally, the Indian New Deal, was U.S. federal legislation which secured new rights for Native Americans, including Alaskan natives. This included a reversal of the Dawes Act's privatization of common holdings of American Indians and a return to local self-government on a tribal basis. It also restored to Native Americans management of their assets, mostly land, and included provisions for building a sound economic foundation for Indian reservation inhabitants.\nThe act did not require tribes to select a constitution. However, if the tribe chose to, the constitution had to; (1) allow the tribal council to employ legal counsel, (2) prohibit the tribal council from engaging any land transitions without majority approval of the tribe, and, (3) authorize the tribal council to negotiate with the Federal, State, and local governments. Evidently some of these restrictions were eliminated by the Native American Technical Corrections Act of 2003. The act slowed a practice of assigning tribal lands to individual tribal members, and reduced the divestiture of native holdings that were being lost through a practice of checkerboard land sales to non-members within tribal areas."},
    {date: "1937",
     desc: "The Native American Reorganization Act forcibly replaces traditional tribal governance (by consensus) with representative democracy (by majority vote). Rivalries between traditional and assimilated Native American people are thereby fueled."},
    {date: "1942",
     desc: "The Aleuts of Pribilof Islands are forced to evacuate for military reasons, after the Japanese land on Kiska and Attu. The Aleuts often had 2 hours to evacuate and returned to villages vandalized by occupying American forces."},
    {date: "1942-1945",
     desc: "The end of World War II—the 25,000 Native Americans of the various branches of the military (numbering among them Navajos serving as \"code talkers\" using transmissions derived from Navajo language phrases) return home."},
    {date: "1944",
     desc: "About 100 Native American people met to create the nation’s first large-scale national organization designed to monitor federal policies, the National Congress of American Indians (NCAI)."},
    {date: "1948",
     desc: "The Corps of Engineers begins construction of the 245-foot-high Oake Dam in SD. The Standing Rock and Cheyenne Sioux Reservations lose a total of 160,889 acres."},
    {date: "1948",
     desc: "Federal court in New Mexico protects the Native Americans right to vote under the 15th Amendment."},
    {date: "1950’s",
     desc: "\"Termination\" legislation seeks to end the Federal Government’s support for native people that is stipulated by 372 treaties and more than 5000 laws and presidential edicts. Native Americans are to be again “relocated” from reservations to urban areas to assimilate Native American people into White society. By 1960 one third of 525,000 Native Americans are in cities. Between 1948 and 1957 Native Americans lose approximately 3,300,000 acres."},
    {date: "1954",
     desc: "Congress passes Public Law 280, empowering any state legislature to take over civil and criminal jurisdiction on Native American reservations without tribal consent, ending Native Americans’ authority to police themselves."},
    {date: "1954",
     desc: "United States Department of Interior begins implementing termination and relocation phases of Indian Reorganization Act of 1934. Among other effects, the termination results in the legal dismantling of 61 tribal nations within the United States."},
    {date: "1960",
     desc: "A meeting of over 500 Native Americans representing more than 65 Nations/tribes is held at the University of Chicago to discuss what the Kennedy Administration might do for and with Native Americans. And another meeting later at Gallup, New Mexico, where more activist-oriented leaders meet. They form the National Native American Youth Council which responds to local crises while speaking out and acting with a Pan-Native American awareness."},
    {date: "1960",
     desc: "3% of the population is considered Native American/Indigenous – 88.6% is considered white."},
    {date: "1961",
     desc: "Basil Williams, President of the Allegany Seneca, appealed to President John F. Kennedy to stop the Kinzua Dam. His plea was ignored. The building of the dam floods ~10,000 acres of habitable Seneca lands along the Allegheny River in NY and forced 1/3 of the population to relocate, violating , the government’s oldest active treaty (1794) with the Six Nations."},
    {date: "1961",
     desc: "Nearly 800 Native American people from 90 Nations/tribes gathered at the Native American Chicago Conference and prepared the Declaration of Native American Purpose which addressed the inherent right of all people to retain spiritual and cultural values, and called for action toward formulating and adopting policies and programs empowering Native American people."},
    {date: "1963",
     desc: "President Johnson presents Annie Dodge Wauneka with the Medal of Freedom, the nation’s highest civilian award, for her accomplishments in eradicating tuberculosis among Native people. To date, she is the 1st and only Native American so honored."},
    {date: "1964",
     desc: "The first takeover in a series by Native Americans of the newly-closed prison on Alcatraz Island."},
    {date: "1968",
     desc: "Native American Civil Rights Act. This Act of Congress revised Public Law 280 by requiring states to obtain tribal consent prior to extending any legal jurisdiction over an Native American reservation."},
    {date: "1969",
     desc: "Four hundred treaties that had been signed to protect Native Americans have been broken by this year. The newly formed American Indian Movement (AIM), organized in midwestern cities by Dennis Banks, Clyde Bellecourt, and others, represents a militant voice for Native American rights. One program, modeled after the Black Panthers, monitors police."},
    {date: "1969",
     desc: "Members of Native Americans of All Nations/tribes occupied Alcatraz Island in San Francisco, claiming the right under an 1868 Sioux Treaty that said unused federal land would revert to Native Americans. The Native Americans stayed on the island until June 1971. The Alcatraz occupation brought together hundreds of Native American people who came to live together on the island and thousands more who identified with the call for self-determination, autonomy, and respect for Native American Culture."},
    {date: "1969",
     desc: "The Navajo Community College on the Navajo Reservation in AZ is the first 4-year college established and controlled by a Native American Nation/tribe."},
    {date: "1970",
     desc: "President Richard M. Nixon delivered a speech to Congress, which denounced past federal policies, pronounced the end of termination, and called for a new era of self-determination for Native American peoples.\nPresident Nixon signs the law restoring the sacred Blue Lake to the people to Taos Pueblo, 64 years after it was taken from them and made part of Carson National Forest."},
    {date: "1970",
     desc: "The Black Hills Alliance is formed."},
    {date: "1970",
     desc: "Plymouth MA officials invite a Wampanoag man, Frank James, to speak at Thanksgiving festivities. He condemns white destruction of native culture, and the National Day of Mourning, a yearly observance commemorating the social and political struggles of native people, is started."},
    {date: "1971",
     desc: "President Nixon signed into law the Alaska Native Claims Settlement Act, granting Alaska's 60,000 Native Americans, Inuits, and Aleuts title to 44 million acres of their ancient homeland and $962.5 million in settlement of the century-old question of Native land rights"},
    {date: "1972",
     desc: "Indian Education Act authorizes funding for bilingual and bicultural programs and teaching materials, and training and hiring of counselors and creates an office of Native American Education in the U.S. Department of Education."},
    {date: "1972",
     desc: "The Trail of Broken Treaties, a cross-country motor caravan to advocate Native American sovereignty, results in the occupation of the Bureau of Native American Affairs offices in Washington DC when discussions between B.I.A. officials and caravan leaders break down."},
    {date: "1973",
     desc: "Many people from the Pine Ridge Reservation and supporters, led by AIM, occupy Wounded Knee to bring attention to corrupt and unjust treatment by tribal, state and federal governments. Wounded Knee is again ringed by high-tech weaponry, this time in the hands of the combined forces of local and federal agencies. Several die, several are wounded, the violence on Lakota lands intensifies."},
    {date: "1973-1976",
     desc: "At least sixty-one violent deaths occur on the Pine Ridge reservation. Most are AIM activists or supporters. Using only the (conservative) figure of documented deaths, the death rate was 170 per 100,000."},
    {date: "1975",
     desc: "Shootout between American Indian Movement members and FBI agents on the Pine Ridge Reservation in South Dakota. Two FBI agents entered the Pine Ridge Reservation claiming they were looking for a tribal member on theft and assault charges. Shots were fired under confusing circumstances, resulting in the death of two FBI agents and one AIM member. AIM activist Leonard Peltier is arrested, tried, and convicted for the deaths of the FBI agents."},
    {date: "1975",
     desc: "President Ford signs the Indian Self-Determination and Education Assistance Act, which mandates that the federal government permit Native Americans to administer their own federal programs if they desired to do so and re-establishes the development of reservations."},
    {date: "1976",
     desc: "A lawsuit filed to recover the 600 acres of the Pequot reservation sold without permission in 1856, results in a $700,000 settlement."},
    {date: "1978",
     desc: "The American Indian Religious Freedom Act officially guarantees First Amendment religious freedom protection for Native Americans."},
    {date: "1978",
     desc: "The Longest Walk begins in San Francisco when 180 Native Americans set out to walk to Washington, DC to commemorate the forced walks Native Americans made in the past"},
    {date: "1978",
     desc: "President Carter signs the Indian Child Welfare Act, protecting the integrity of Native American families by eliminating child welfare practices that result in unwarranted Native American parent-child separations. By this Act, Nations/tribes are given the authority to care for Native American children, to intercede in court cases regarding adoptive placement of Native American children, and to place Native American children with tribal members or with members of other Nations/tribes."},
    {date: "1980",
     desc: "6% of the U.S. population is considered Native American/Indigenous, 6.4% Hispanic – 79.6 is considered white Not Hispanic"},

    {date: "1975-12-23 ",
     desc: "Penobscot and Passamaquoddy Nations/tribes oblige the federal government to bring a land claim on their behalf for approximately 60% of the state of Maine."},
    {date: "1980",
     desc: "The Maine Indian Claims Settlement Act allocates $81.5 million for the benefit of the Passamaquoddy and Penobscot, in part allowing them to purchase lands in Maine, and extinguishing all aboriginal title in Maine. This leads to recovery of more than 300,000 acres and a $27 million trust fund."},
    {date: "1992",
     desc: "Native people and their supporters close the Dickson Mounds, in Illinois, which were open grave sites previously on display to the public."},
    {date: "1982",
     desc: "Seminole Tribe v. Butterworth Supreme Court decision. The Court rules that Nations/tribes have the right to create gambling enterprises on their land, even if such facilities are prohibited by the state. The ruling enabled reservations to establish casinos and gave greater authority for tribal governments to levy taxes, own assets and create judiciaries."},
    {date: "1983",
     desc: "The U.S. 7th Circuit Court of Appeals found that the Lac Courte Oreilles Band of Chippewas of WI retained their hunting, fishing, trapping, and gathering rights when they signed the treaties of 1937, 1842, 1854. The U.S. Supreme Court refused to hear an appeal of what became known as the Voight decision"},
    {date: "1983",
     desc: "Federal recognition is received by the Narragansett and the Mashantucket Pequots, who own Foxwoods"},
    {date: "1987",
     desc: "President Reagan signs a bill establishing the Trail of Tears as a National Historic Trail"},
    {date: "1987",
     desc: "The Wampanoag gain the status of federal recognition, the only federally recognized Nation/tribe in Massachusetts."},
    {date: "1988",
     desc: "Indian Gaming Regulatory Act. This statute affirmed the right of Nations/tribes to conduct gaming on Native American lands, but made it subject to tribal/state compact negotiations for some types of gaming."},
    {date: "1990",
     desc: "President Bush signs the Native American Language Act into law, reversing past policy that suppressed and exterminated Native American languages and cultures."},
    {date: "1990",
     desc: "President Bush signs the Native American Graves Protection and Repatriation Act which requires federal agencies and private museums receiving federal funding to inventory their collections. Ancestral remains and objects must be returned to requesting Native American Nations/tribes proving ownership. The law represents a major shift away from viewing Native American human remains as “archaeological resources” or “federal property”."},
    {date: "1990",
     desc: "The Indian Arts & Crafts Act prohibits misrepresentation in marketing of American Indian or Alaska Native arts and crafts products within the United States."},
    {date: "1991",
     desc: "San Carlos Apache Tribal Council members launched an international campaign to voice their opposition to the telescope project on their sacred Mount Graham, located in Coronado National Forest near the reservation in AZ"},
    {date: "1992",
     desc: "500 years of Columbus. Many spiritually-based walks and runs commemorate the Quincentennial. "},
    {date: "1992",
     desc: "After a successful bingo operation, the Mashantucket Pequot open Foxwoods Casino, becoming the wealthiest group of Native Americans in the United States."},
    {date: "1994",
     desc: "Congress enacts the American Indian Trust Fund Reform Act in an effort to correct the long record of disregard for the rights, and funds of Native American tribal members."},
    {date: "1996",
     desc: "President Clinton authorizes a White House Initiative on Tribal Colleges and Universities within the U.S. Department of Education to continue the support and development of tribal colleges into the 21st Century.\nPresident Clinton issues Executive Order on Native American Sacred Sites to affirm the American Indian Religious Freedom Act policy and protection of Native American sacred sites.\nClinton also declares November of each year to be National American Indian Heritage Month"},
    {date: "1998",
     desc: "Carl Gorman, the oldest of the 400 Navajo code talkers, dies."},
    {date: "2000",
     desc: "1% of the U.S. population is considered Native American/Indigenous, 1% is considered Pacific Islander/Native Hawaiian, 12.5% Hispanic – 75.1 is considered white Not Hispanic"},
    {date: "2000",
     desc: "Sand Creek National Monument Act authorizes a national monument at the site of the Sand Creek Massacre of Cheyenne and Arapaho people by U.S. and Colorado soldiers. An earlier law apologized for the Massacre."},
    {date: "2001",
     desc: "The Connecticut Supreme Court unanimously ruled that the Mohegan Tribe of Indians of Connecticut, owners of the enormously profitable Mohegan Sun casino, could not claim their name as a trademark. The federally recognized Mohegans were suing another faction called the Mohegan Tribe and Nation Inc., which is unrecognized but has a petition pending with the BIA. The case left open the question of whether a non-Mohegan or non-Indian could appropriate the tribal name."},
    {date: "2001",
     desc: "A Justice Department study of violent crime among different races shows a high rate of violence against American Native Americans, while crime against other groups has fallen. Native Americans were twice as likely to be victims of violent crime as blacks, whites or Asians. Native American women experience the highest rate of violence of any group in the United States."},
    {date: "2003",
     desc: "On Dec.2, the first Female Chief Justice of the Navajo Nation is sworn in"},
    {date: "2004",
     desc: "The BIA turns down two Nipmuc (or Nipmuck) petitions for recognition as a nation, one from the Nipmuc Nation headquartered in Sutton and the other from the Webster/Dudley Band of Chaubunagungamaug Nipmuck Indians, which split from the first filing in 1996."},
    {date: "2005",
     desc: "The National Collegiate Athletic Association prohibits the use of 19 schools’ Native American mascots during post-season games, including Division 1 athletic icons Florida State (Seminoles), Illinois (Fighting Illini), and Utah (Utes). Regardless of stature, each institution will also be barred from hosting future NCAA postseason tournaments. Schools already selected as tournament sites would be asked to cover any offensive logos. NCAA then backpedals and allowed some schools to use their mascot names."},
    {date: "2005",
     desc: "Kamehameha Schools defends its \"Hawaiians-only\" admissions policy, saying it has \"a legitimate remedial reason for a preference\" under historic civil rights legislation. In a petition asking the 9th Circuit of Appeals to reconsider its decision striking down the policy (John Doe v. Kamehameha Schools/Bernice Pauahi Bishop Estate), Kamehameha attorneys argue that the ruling is “unprecedented.” “It is the first in our nation's history to invalidate a remedial education policy by a private school for the benefit of any minority group, much less an indigenous people.\" Kamehameha loses the suit."},
    {date: "2006",
     desc: "Viking publishes, “Where the Lightning Strikes: The Lives of American Indian Sacred Places,” by Peter Nabokov."},
    {date: "2006",
     desc: "Richard Milanovich, the chairman of Agua Caliente Band of Cahuilla Indians apologized to other tribal leaders for a scandal that tied Milanovich to Jack Abramoff. Abramoff collected $66 Million from 6 American Indian tribes seeking influences in Washington D.C."},
    {date: "2007",
     desc: "The Bureau of Justice Statistics, U.S. Department of Justice, found that 70% of violent victimizing crimes against Native Americans is done by an offender that is not of the same race or ethnicity. This is a higher rate than violent crimes against any other sub-ethnic group."},
    {date: "2008",
     desc: "A CDC Survey found that 39% of Native American women suffer from intimate partner violence in their lifetime. This is the greatest percentage among all ethnicities."},
    {date: "2009",
     desc: "Work place discrimination following the recession took a toll on the Native American community. Research and polls showed that Whites in areas such as Alaska, the Northern Plains, and the Southwest, had higher employment rates, compared to the Native American counterparts. Native Americans in this area were doing very poorly. One example was Alaska’s unemployment rates for Native Americans, which was 51%."},
    {date: "2010-2012",
     desc: "22% of the 5.2 Million Native Americans live on tribal lands. The living conditions can be compared to “Third World Conditions.”"},
    {date: "2010-04-20",
     desc: "The Havasupai Indian tribe wins a 7-year lawsuit against Arizona State University. Researchers from ASU had collected blood samples, claiming that it was for diabetes research. They used these samples in studies for schizophrenia, inbreeding, and ancient population migration. Members of the Tribe claimed this was a violation of genetic privacy."},
    {date: "2013",
     desc: "Obama agrees that NFL needs to change the name of the Washington Redskins name. The team resists."},
    {date: "2014",
     desc: "Oklahoma governor’s daughter Christina Fallin publicized a photo of herself wearing a Native American headdress with the caption “appropriate culturation” which was a play on words for promotion of her new song about to release. The Native American community felt targeted and was outraged. Fallin apologized in a press conference, but it felt like an empty declaration, making the community more distraught."},
    {date: "2015",
     desc: "The United States Board on Geographic names admits that names with ‘squaw’ in them is offensive after Native Americans in Grant County, Ore tribe fought against white officials for years to receive name changes."},
    {date: "2015",
     desc: "Secretary of the Interior Sally Jewell announced that the highest mountain in the United States and North America, formerly known as Mount McKinley, will now be officially designated by the name Denali, returning to its original name."},
    {date: "2015",
     desc: "Addidas offers free design resources and financial support to high schools looking to rebrand and change from Native American mascots, nicknames, imagery or symbolism. While laudatory, this sparks accusations of hypocrisy given that Addidas sponsors Washington Redskin’s quarterback and profits from uniform and fan sales for teams such as the Chicago Blackhawks, the Cleveland Indians, and the Atlanta Braves."},
    {date: "2015",
     desc: "Faculty at Amherst College, in Amherst Massachusetts, vote to remove Lord Jeffrey Amherst as the schools “mascot.” Lord Jeffrey was an 18th century military commander who encouraged the distribution of smallpox infected blankets as a means of biological warfare."},
    {date: "2016-04-2016-12",
     desc: "Resistance to the Dakota access pipeline by water protectors and their allies who endure pepper spray, teargas, rubber bullets, trained dogs, percussion grenades, sonic attacks, and water cannon in sub freezing termperatures.  Activists are arrested, stripped, and kept in dog kennels with numbers written on their arms. Video footage of shootings by reporters on the scene contradict official police statements. Growing support from a variety of sources eventually leads to the Army Corps of Engineers to call for a full environmental impact statment."}]});
