app.cite = {
    N7: ["https://en.wikipedia.org/wiki/Norse_colonization_of_North_America",
         "http://www.historyofinformation.com/expanded.php?id=3750"],
    N10: ["https://en.wikipedia.org/wiki/Aztec_Empire"],
    B1: ["https://en.wikipedia.org/wiki/History_of_Cape_Verde"],
    B2: ["https://en.wikipedia.org/wiki/Portuguese_colonization_of_the_Americas"],
    N14: ["https://en.wikipedia.org/wiki/Hispaniola"],
    L2: ["https://en.wikipedia.org/wiki/Hispaniola",
         "https://en.wikipedia.org/wiki/Juan_Ponce_de_Le%C3%B3n",
         "https://simple.wikipedia.org/wiki/Juan_de_Esquivel",
         "https://en.wikipedia.org/wiki/Diego_Vel%C3%A1zquez_de_Cu%C3%A9llar",
         "https://en.wikipedia.org/wiki/Santa_Mar%C3%ADa_la_Antigua_del_Dari%C3%A9n"],
    L3: ["https://en.wikipedia.org/wiki/Antonio_de_Montesinos"],
    B3: ["https://en.wikipedia.org/wiki/San_Miguel_de_Gualdape"],
    N16: ["http://www.smithsonianmag.com/people-places/what-became-of-the-taino-73824867"],
    L6: ["http://www.smithsonianmag.com/people-places/what-became-of-the-taino-73824867"],
    B6: ["http://library.brown.edu/haitihistory/1sr.html"],
    N40: ["http://treatiesportal.unl.edu/earlytreaties/",
          "http://avalon.law.yale.edu/subject_menus/ntreaty.asp"],
    B34: ["Zinn, pg. 29"],
    A57: ["http://chnm.gmu.edu/courses/ncc375/rp/index.html",
          "http://scholarship.law.berkeley.edu/cgi/viewcontent.cgi?article=1164&context=aalj"],
    L33: ["https://zinnedproject.org/materials/ludlow-massacre/",
          "https://en.wikipedia.org/wiki/Ludlow_Massacre"],
    A75: ["http://scholarship.law.berkeley.edu/cgi/viewcontent.cgi?article=1164&context=aalj"],
    A79: ["Hare-Hawes-Cutting Act sec 8(a)(1)"],
    L43: ["http://digitalcommons.ilr.cornell.edu/cgi/viewcontent.cgi?article=1561&context=articles",
          "https://en.wikipedia.org/wiki/Cannery_and_Agricultural_Workers%27_Industrial_Union",
          "https://www.jstor.org/stable/25157372?seq=1#page_scan_tab_contents",
          "https://www.kcet.org/history-society/bittersweet-fruit-el-montes-berry-strike-of-1933"],
    N106: ["Disciplined Hearts, Theresa DeLeane O'Nel. LA: University of California Press, 1996"],
    A101: ["Infamy by Richard Reeves"],
    M10: ["Haiek, 2010, p. 48",
          "http://www.bostonhistorycollaborative.com/BostonFamilyHistory/ancestors/syrian-lebanese/syr_1950.html",
          "http://www.zihniozdil.info/wp-content/uploads/2014/04/Arab-American-Identity.pdf"],
    N125: ["https://academic.evergreen.edu/g/grossmaz/bha.html"],
    L81: ["http://www.dallasnews.com/news/news/2013/07/21/40-years-after-santos-rodriguezs-murder-scars-remain-for-family-neighbors-and-dallas",
          "http://www.npr.org/sections/codeswitch/2013/07/24/205121429/How-The-Death-Of-A-12-Year-Old-Changed-The-City-Of-Dallas"],
    B184: ["http://biotech.law.lsu.edu/cphl/history/reports/tuskegee/report1.pdf"],
    A136: ["The Good Immigrants: How the Yellow Peril Became the Model Minority
By Madeline Y. Hsu"],
    R97: ["http://www.presidency.ucsb.edu/ws/index.php?pid=41904"],
    M22: ["http://articles.chicagotribune.com/1985-11-30/news/8503220803_1_alex-odeh-ray-alfred-arab-group",
          "http://www.nytimes.com/1985/12/03/us/arab-americans-seek-protection.html"],
    M24: ["http://www.nytimes.com/1986/12/10/nyregion/about-new-york-insult-piles-upon-calumny-an-arab-objects.html",
          "http://articles.chicagotribune.com/1987-07-12/news/8702200711_1_arabs-fear-sami-odeh-american-arab-anti-discrimination-committee/2",
          "http://articles.latimes.com/1986-12-03/news/mn-511_1_arabs"],

};
