app.cite = {
    N7: ["https://en.wikipedia.org/wiki/Norse_colonization_of_North_America",
         "http://www.historyofinformation.com/expanded.php?id=3750"],
    N10: ["https://en.wikipedia.org/wiki/Aztec_Empire"],
    B1: ["https://en.wikipedia.org/wiki/History_of_Cape_Verde"],
    B2: ["https://en.wikipedia.org/wiki/Portuguese_colonization_of_the_Americas"],
    N14: ["https://en.wikipedia.org/wiki/Hispaniola"],
    L2: ["https://en.wikipedia.org/wiki/Hispaniola",
         "https://en.wikipedia.org/wiki/Juan_Ponce_de_Le%C3%B3n",
         "https://simple.wikipedia.org/wiki/Juan_de_Esquivel",
         "https://en.wikipedia.org/wiki/Diego_Vel%C3%A1zquez_de_Cu%C3%A9llar",
         "https://en.wikipedia.org/wiki/Santa_Mar%C3%ADa_la_Antigua_del_Dari%C3%A9n"],
    L3: ["https://en.wikipedia.org/wiki/Antonio_de_Montesinos"],
    B3: ["https://en.wikipedia.org/wiki/San_Miguel_de_Gualdape"],
    N16: ["http://www.smithsonianmag.com/people-places/what-became-of-the-taino-73824867"],
    L6: ["http://www.smithsonianmag.com/people-places/what-became-of-the-taino-73824867"],
    B6: ["http://library.brown.edu/haitihistory/1sr.html"],
    N40: ["http://treatiesportal.unl.edu/earlytreaties/",
          "http://avalon.law.yale.edu/subject_menus/ntreaty.asp"],
    B34: ["Zinn, pg. 29"],
    A57: ["http://chnm.gmu.edu/courses/ncc375/rp/index.html",
          "http://scholarship.law.berkeley.edu/cgi/viewcontent.cgi?article=1164&context=aalj"],
    L33: ["https://zinnedproject.org/materials/ludlow-massacre/",
          "https://en.wikipedia.org/wiki/Ludlow_Massacre"],
    A75: ["http://scholarship.law.berkeley.edu/cgi/viewcontent.cgi?article=1164&context=aalj"],
    A79: ["Hare-Hawes-Cutting Act sec 8(a)(1)"],
    L43: ["http://digitalcommons.ilr.cornell.edu/cgi/viewcontent.cgi?article=1561&context=articles",
          "https://en.wikipedia.org/wiki/Cannery_and_Agricultural_Workers%27_Industrial_Union",
          "https://www.jstor.org/stable/25157372?seq=1#page_scan_tab_contents",
          "https://www.kcet.org/history-society/bittersweet-fruit-el-montes-berry-strike-of-1933"],
};
