/*jslint white, fudge */

BlackTimeline = {name: "African American", ident: "Black", code: "B",
   credit: "Compiled by: Karen L. Suyemoto, Ph.D. – UMass (Boston) Psychology and Asian American Studies. Updated 2005/2006 by Claudia Fox Tree and Elli Stern for EMI Empowering Multicultural Initiatives. Updated 2014 by Emily Davis, for K. Suyemoto.",
   resources: [
       "The African American Almanac, 7th edition L. Mpho Mabunda, ed. Gale Research: Detroit, 1997",
       "BRIDGE: Building a Race and Immigration Dialogue in the Global Economy. Eunice Hyunhye Cho, Miriam Ching Yoon Louie & Sasha Khokha. National Network for immigrant an refugee rights, Oakland, CA, 2004 (BRIDGE)",
       "American Chronicles, L. Gordon & A. Gordon: New Haven & London, 1999",
       "http://lcweb2.loc.gov/ammem/aap/timeline.html Time Line of African American History",
       "http://www.infoplease.com/spot/civilrightstimeline1.html Civil Rights Timeline",
       "http://www.college.emory.edu/culpeper/BAKEWELL/chronology.html Colonial Latin America Chronology",
       "GLBXT chronology for experiences of GLBXT African Americans which are relevant to the African American population"],
  entries: [
    {date: "1444",
     desc: "Portuguese reach Cape Verde, westernmost point of Africa."},
    {date: "1492",
     desc: "Blacks are among the first explorers to the New World. Pedro Alonzo Nino, identified by some scholars as a Black man, arrives with Christopher Columbus."},
    {date: "1501",
     desc: "The Spanish throne officially approves the use of African slaves in the New World."},
    {date: "1502",
     desc: "Portugal brings its first shipload of African slaves to the Western Hemisphere, selling them in what is now Latin America."},
    {date: "1526",
     desc: "The first group of Africans to set foot on what is now the U.S., are brought by a Spanish explorer to SC to erect a settlement. However, they soon flee to the interior and settle with Native Americans."},
    {date: "1562",
     desc: "Britain enters the slave trade when John Hawkins sells a large cargo of African slaves to Spanish planters."},
    {date: "1600",
     desc: "By the year 1600, over 900,000 slaves have been brought to Latin America. In the next century, 2,750,000 are added to that total. Slave revolts in the 16th century are reported in Hispaniola, Puerto Rico, Panama, Cuba, and Mexico."},
    {date: "1629-1637",
     desc: "African slaves are imported into CT, MD, and New Amsterdam (now New York)."},
    {date: "1601",
     desc: "A law protecting Black slaves from abusive owners is passed in MA."},
    {date: "1640",
     desc: "Beginning of large-scale sugar planting in non-Spanish Caribbean islands"},
    {date: "1641",
     desc: "MA becomes the first colony to legalize slavery."},
    {date: "1651",
     desc: "Anthony Johnson, a Black man, imports 5 servants and qualifies to receive a 200-acre land grant along the Puwgoteague River in VA. Others soon join Johnson and attempt to launch an independent African community. At its height, the settlement has 12 African homesteads with sizable holdings."},
    {date: "1663",
     desc: "MD settlers pass a law stipulating that all imported Africans are to be given the status of slaves. Free White women who marry Black slaves are also considered slaves during the lives of their spouses; children of such unions are also to be classified as slaves. In 1681, a law is passed which stipulates that children born from a union of a White servant woman and African are free citizens."},
    {date: "1688",
     desc: "Mennonites in PA sign an anti-slavery resolution, the first formal protest against slavery in the Western Hemisphere."},
    {date: "1696",
     desc: "Quakers importing slaves are threatened with expulsion from the society."},
    {date: "1700",
     desc: "The population of Black slaves in the English Colonies is estimated at 28,000. 23,000 reside in the South."},
    {date: "1711",
     desc: "The colonial legislature in PA, after being pressured from the Mennonites and Quakers, outlaws slavery in PA but is overruled by the British Crown."},
    {date: "1712",
     desc: "The Maiden Lane slave revolt in NY city claims the lives of 9 Whites and results in the execution of 21 Black slaves. Six others commit suicide."},
    {date: "1739",
     desc: "3 Black slave revolts occur in SC, resulting in the death of 51 Whites and many more slaves."},
    {date: "1744",
     desc: "The colony of VA amends its 1705 law, now allowing “any free Negro, mulatto, or Indian being a Christian,” as a witness in a criminal or civil suit involving another Black, mulatto, or Indian."},
    {date: "1750",
     desc: "The Black slave population in the English Colonies reaches 236,400 with over 206,00 living south of PA. Slaves comprise about 20% of the colonies’ population."},
    {date: "1754",
     desc: "Benjamin Banneker, a 22-year old free Black man, becomes the first person in the North American colonies to construct a clock."},
    {date: "1769",
     desc: "In the VA house of Burgesses, Thomas Jefferson unsuccessfully presses for a bill to emancipate African slaves."},
    {date: "1770",
     desc: "The Quakers open a school for Blacks in Philadelphia, PA."},
    {date: "1773",
     desc: "The first Baptist Church for Blacks is organized in Savannah, GA."},
    {date: "1774",
     desc: "The Continental Congress demands elimination of the trans-Atlantic slave trade and economic embargoes on all countries participating in it. RI enacts a law prohibiting slavery (not applying to slaves already in RI before 1774)."},
    {date: "1775",
     desc: "The Continental Congress bars Blacks from serving the army during the American Revolution. When the British governor of VA offers freedom to all male slaves who join the loyalist forces, General George Washington reverses his position and orders acceptance of free Blacks for military service."},
    {date: "1775",
     desc: "The first abolitionist society in the U.S. is organized in Philadelphia, PA."},
    {date: "1776",
     desc: "The amended form of the Declaration of Independence, which does not include Jefferson’s proposal denouncing slavery, is adopted."},
    {date: "1780",
     desc: "The PA assembly enacts a law providing for the gradual emancipation of slaves."},
    {date: "1783",
     desc: "Slavery in MA is abolished by the MA Supreme Court. Blacks in taxable categories are granted suffrage."},
    {date: "1787",
     desc: "Congress passes the Northwest Ordinance which forbids the extension of slavery into this area."},
    {date: "1787",
     desc: "The Constitution is adopted. In it, importation of slaves cannot be prohibited before 1808, and five slaves are considered the equivalent of three free men in congressional apportionment."},
    {date: "1790",
     desc: "According to the first census, there are 757,000 Blacks in the U.S., comprising 19% of the total population. 9% of Blacks are free."},
    {date: "1793",
     desc: "Eli Whitney patents the cotton gin, which strengthens slavery by increasing profits in growing cotton. Congress passes the Fugitive Slave Act, which makes it a criminal offense to harbor a slave or prevent his or her arrest."},
    {date: "1793",
     desc: "VA passes a law which forbids free Blacks from entering the state."},
    {date: "1800",
     desc: "Congress rejects a petition to free Blacks in PA to gradually end slavery in the U.S."},
    {date: "1803",
     desc: "The SC state legislature, which had been trying limit importation of slaves, reopens the slave trade with Latin American and the West Indies."},
    {date: "1804",
     desc: "NJ passes an emancipation law. All states north of the Mason-Dixon Line now have laws forbidding slavery or providing for its gradual elimination."},
    {date: "1808",
     desc: "Congress bars the importation of any new slaves into the U.S. The law is widely ignored."},
    {date: "1810",
     desc: "LA courts declare that a Black is free unless it is otherwise proven."},
    {date: "1816",
     desc: "The African Methodist Episcopal Church is organized in Philadelphia, PA."},
    {date: "1817",
     desc: "Mississippi enters the union as a slave state. NY passes a gradual slavery abolition act."},
    {date: "1819",
     desc: "Alabama enters the Union as a slave state."},
    {date: "1820",
     desc: "The Missouri Compromise is enacted. It provides for Missouri’s entry into the Union as a slave state and Maine’s entry as a free state, making 12 of each in the U.S. All territory north of 36 30’ latitude declared free, and south of that latitude is open to slavery."},
    {date: "1822",
     desc: "The Denmark Vesey conspiracy in Charleston, SC, one of the most elaborate slave revolts on record, fails. Vesey and 36 collaborators are hanged. In response, slave states adopt laws to further restrict the mobility of Blacks."},
    {date: "1823",
     desc: "Mississippi enacts a law prohibiting the teaching of reading and writing to Blacks and meetings of more than 5 slaves or free Blacks."},
    {date: "1826",
     desc: "Jefferson dies, emancipating only 5 of his slaves."},
    {date: "1830",
     desc: "The first National Negro Convention meets in Philadelphia, launching a church-affiliated program to improve the social status of American Blacks."},
    {date: "1830",
     desc: "In an attempt to counter the increasing strength of the abolitionists, a number of states pass laws restricting the education, legal safeguards, and citizenship rights of slaves and free Blacks. Many states require the deportation of free Blacks, slave codes are enforced more strictly, and the number of slave emancipations decline."},
    {date: "1830",
     desc: "The U.S. census reports that 3,777 Black heads of families own slaves, mostly in LA, MD, VA, NC, and SC."},
    {date: "1831",
     desc: "Nat Turner leads the greatest slave rebellion in history. Some 60 Whites are killed in VA and the entire South is thrown into panic. Turner is hanged."},
    {date: "1834",
     desc: "Parliament abolishes slavery in the British empire. 700,000 slaves are liberated at a cost of 20 million British pounds sterling."},
    {date: "1836",
     desc: "U.S. House of Rep. adopts the “gag rule,” which prevents congressional action on anti-slavery resolutions of legislation."},
    {date: "1840",
     desc: "MA repeals its anti-miscegenation law."},
    {date: "1840",
     desc: "Pope Gregory XVI declares his opposition to slavery and the slave trade."},
    {date: "1841",
     desc: "Throughout the country, increasingly restrictive segregation statutes are enacted. NY grants schools the right to segregate education. SC forbids White and Black mill hands from looking out the same window. Whites and Blacks in Atlanta are required to swear on different Bibles in court."},
    {date: "1843",
     desc: "MA and VT state legislatures defy the Fugitive Slave Act and forbid state officials from imprisoning or assisting federal authorities in the recapture of escaped slaves."},
    {date: "1845",
     desc: "U.S. Congress overturns the gag rule. Texas is admitted to the Union as a slave state."},
    {date: "1848",
     desc: "Roberts v. the City of Boston. Benjamin Roberts, an African American father sued the city of Boston to allow his five year old daughter to attend a school closer to her home. This lawsuit was part of an organized effort by the African American community to end racially segregated schools. When the Massachusetts Supreme Judicial Court ruled against Sarah Roberts the ideology of “separate but equal” was born. The case was defended by Robert Morris who was the first Black lawyer in America to argue a jury case. \nAlthough the case lost in the courts. the Black community was determined and did not give up the fight. The Black-led Equal School Association began to look towards legislature to end segregated public schools. With the unwavering efforts of the Black community, through boycotts, protests and the support of White allies a victory was finally achieved. In 1855, a law abolishing school segregation was passed. Boston became the first major city in America to open its public schools to African Americans. This successful effort led to other victories such as the opening of theaters and railway cars, the opening of government jobs, a memorial honoring Crispus Attucks and the formation of African American Union regiments to fight in the Civil War."},
    {date: "1849",
     desc: "Harriet Tubman escapes from slavery in MD. She later returns to the South no less than 19 times to help transport more than 300 slaves to freedom."},
    {date: "1852",
     desc: "Harriet Beecher Stowe’s novel Uncle Tom’s Cabin is published. The novel focuses national attention on the cruelties of slavery."},
    {date: "1855",
     desc: "MA abolishes school segregation."},
    {date: "1857",
     desc: "Supreme Court rules on the Dred Scott case. On March 6, the Supreme Court decides that an African American cannot be a citizen of the U.S. and thus has no rights of citizenship. The decision sharpens the national debate over slavery."},
    {date: "1859-10-16",
     desc: "John Brown raids the federal arsenal at Harper’s Ferry, Virginia. Brown’s unsuccessful mission to obtain arms for a slave insurrection stirs and divides the nation. Brown is hanged on December 2."},
    {date: "1859",
     desc: "During this year, the last ship to bring slaves to the U.S., the Clothilde, arrives in Mobile Bay, Alabama."},
    {date: "1860",
     desc: "As the Civil War approaches, the U.S. is sharply divided. VA passes a law stipulating that free Blacks can be sold into slavery for committing imprisonable offenses. MD forbids emancipation of slaves. President Buchanan advocates a constitutional amendment confirming the fugitive slave acts. Lincoln is elected president. SC secedes from the Union."},
    {date: "1861",
     desc: "Civil War."},
    {date: "1862",
     desc: "Congress abolishes slavery in the District of Columbia – an important step on the road for freedom for all African Americans."},
    {date: "1863",
     desc: "Lincoln’s Emancipation Proclamation takes effect January 1, legally freeing slaves in areas of the South in rebellion."},
    {date: "1863-07-18",
     desc: "The Fifty-Fourth Massachusetts Volunteers – the all Black unit of the Union army charges Fort Wagner in Charleston, South Carolina. Sergeant William H. Carney becomes the first African American to receive the Congressional Medal of Honor for bravery under fire."},
    {date: "1864",
     desc: "On June 15, Congress passes a bill authorizing equal pay, equipment, arms, and health care for African American troops."},
    {date: "1865",
     desc: "The Confederacy surrenders. (Of the 179,000 Blacks who served in the Union army, 3,000 were killed in battle, 26,000 died from disease, and 14,700 deserted. Blacks represented 9-10% of the Unions armed forces.)"},
    {date: "1865-03-03",
     desc: "Congress establishes the Freedmen’s Bureau to provide health care, education and technical assistance to emancipated slaves."},
    {date: "1865",
     desc: "Lincoln is assassinated."},
    {date: "1865",
     desc: "The 13th Amendment abolishing slavery is ratified."},
    {date: "1866",
     desc: "The Ku Klux Klan, an organization to intimidate Blacks and other ethnic and religious minorities is formed. The Klan is the first of many secret terrorist organizations organized in the South for the purpose of reestablishing White authority."},
    {date: "1866",
     desc: "Police in New Orleans storm a Republican meeting of Blacks and Whites on July 30, killing more than 40 and wounding more than 150."},
    {date: "1866-02-02",
     desc: "A Black delegation led by Frederick Douglass meets with president Andrew Johnson at the White House to advocate Black suffrage. The president expresses his opposition, and the meeting ends in controversy."},
    {date: "1867",
     desc: "Reconstruction begins. Congress passes Reconstruction Acts. These acts call for the enfranchisement of former slaves in the South."},
    {date: "1868",
     desc: "9 states grant suffrage to Blacks, but 2 deny it."},
    {date: "1868",
     desc: "The 14th Amendment is ratified, establishing the concept of “equal protection: for all citizens under the Constitution. President Johnson vetoes the bill granting vote to Blacks in Washington, DC--the veto is overridden by Congress."},
    {date: "1868-09-28",
     desc: "An estimated 200 to 300 Black Americans are killed in Lousiana in the Opelousas Massacre."},
    {date: "1870",
     desc: "The 15th Amendment, guaranteeing African American males the right to vote, is ratified"},
    {date: "1875",
     desc: "Congress passes civil rights legislation guaranteeing equal rights to Black Americans in public accommodations and jury duty. The legislation was invalidated by the Supreme Court in 1883"},
    {date: "1875",
     desc: "Blanche Kelso Bruce (Republican) of Mississippi becomes the first African American to serve a full six- year term. Not until 1969 will another Black American begin a Senate term."},
    {date: "1875",
     desc: "On September 4-6, more than 20 Black Americans are killed in a massacre in Clinton, Mississippi."},
    {date: "1877",
     desc: "The end of Reconstruction. A deal with Southern Democratic leaders makes Rutherford B. Hayes (Republican) president, in exchange for the withdrawal of federal troops from the South and the end of federal efforts to protect the civil rights of African Americans."},
    {date: "1878",
     desc: "The United States Supreme Court rules that states cannot prohibit segregation on public transportation."},
    {date: "1879",
     desc: "The United States Supreme Court rules that the 14th Amendment insures Blacks all rights that are enjoyed by Whites under law. In a separate case, the Court rules that one of the purposes of both the 13th and 14th Amendments is to raise the condition of Blacks to one of perfect equality with Whites."},
    {date: "1883",
     desc: "The United States Supreme Court declares the Civil Rights Act of 1875 unconstitutional."},
    {date: "1890",
     desc: "Mississippi constitutional convention begins the systematic exclusion of Blacks from politics by adopting literacy and other complex “understanding” tests as prerequisites to voting. 7 other southern states follow suit."},
    {date: "1896",
     desc: "The United States Supreme Court upholds the doctrine of separate but equal, paving the way for segregation of Blacks in all arenas. The Roberts decision was used to establish the “separate but equal” standard that formally legalized segregation in the U.S. until 1960. The court ruled that as long as equivalent facilities were provided, classification by race was not an abridgment of a person’s rights."},
    {date: "1900",
     desc: "11.6% of the U.S. population is considered African American – 87.9% is considered White"},
    {date: "1901",
     desc: "George H. White gives up his seat on March 4. No African American will serve in Congress for the next 28 years."},
    {date: "1901",
     desc: "One hundred and five Black Americans are known to have been lynched in 1901."},
    {date: "1902",
     desc: "Eighty-five Black Americans are known to have been lynched in 1902."},
    {date: "1903",
     desc: "Eighty-four Black Americans are known to have been lynched in 1903."},
    {date: "1904",
     desc: "Seventy-six Black Americans are known to have been lynched in 1904."},
    {date: "1905",
     desc: "African American intellectuals and activists, led by W. E. B. Du Bois and William Monroe Trotter, begin the Niagara Movement."},
    {date: "1905",
     desc: "Fifty-seven Black Americans are known to have been lynched in 1905."},
    {date: "1906",
     desc: "Sixty-two Black Americans are known to have been lynched in 1906."},
    {date: "1908",
     desc: "Eighty-nine Black Americans are known to have been lynched in 1908"},
    {date: "1909",
     desc: "The National Association for the Advancement of Colored People is founded in New York. This organization was formed to promote use of the courts to restore the legal rights of Black Americans."},
    {date: "1909",
     desc: "Admiral Peary, African American Mathew Henson, and four Eskimos, became the first men known to reach the North pole."},
    {date: "1909",
     desc: "Sixty-nine Black Americans are known to have been lynched in 1909."},
    {date: "1910",
     desc: "On December 19, the City Council of Baltimore approves the first city ordinance designating the boundaries of Black and White neighborhoods. Similar ones in Dallas, Texas, Greensboro, North Carolina, Louisville, Kentucky, Norfolk, Virginia, Oklahoma City, Oklahoma, Richmond, Virginia, Roanoke, Virginia and St. Louis, Missouri follow this ordinance. The Supreme Court declares the Louisville ordinance to be unconstitutional in 1917."},
    {date: "1911",
     desc: "The National Urban League is founded. The organization is created to help African Americans secure equal employment. Eugene Kinckle Jones serves as the first executive secretary. Professor Kelly Miller is a founding member."},
    {date: "1911",
     desc: "Sixty Black Americans are known to have been lynched in 1911."},
    {date: "1912",
     desc: "Sixty-one Black Americans are known to have been lynched in 1912."},
    {date: "1913",
     desc: "The fiftieth anniversary of the Emancipation Proclamation is celebrated throughout the year."},
    {date: "1913",
     desc: "The Wilson administration begins government-wide segregation of work places, rest rooms and lunch rooms."},
    {date: "1914",
     desc: "Fifty-one Black Americans are known to have been lynched in 1914."},
    {date: "1915",
     desc: "Spurred by boll weevil devastation of cotton crops, the Great Migration of Blacks to the North begins. 1 million African Americans migrate to escape lynchings, Jim Crow laws, and economic hardship. Fifty-six Black Americans are known to have been lynched in 1915."},
    {date: "1916",
     desc: "Fifty Black Americans are known to have been lynched in 1916."},
    {date: "1917",
     desc: "The United States enters World War I. In October, over 600 Blacks are commissioned officers, and 700,000 Blacks register for the draft. 370,000 African Americans were in military service – more than half in the French war zone."},
    {date: "1917",
     desc: "One of the bloodiest race riots in the nation’s history takes place in East St. Louis, Illinois, on July 1-3. A Congressional committee reports that 40-2000 people were killed, hundreds more injured, and 6,000 driven from their homes."},
    {date: "1917",
     desc: "Thirty-six Black Americans are known to have been lynched in 1917."},
    {date: "1918",
     desc: "Sixty Black Americans are known to have been lynched in 1918."},
    {date: "1919",
     desc: "Seventy-six Black Americans are known to have been lynched in 1919."},
    {date: "1920",
     desc: "The decade of the Twenties witnesses the Harlem Renaissance, a remarkable period of creativity for Black writers, poets and artists."},
    {date: "1920",
     desc: "Fifty-three Black Americans are known to have been lynched in 1920."},
    {date: "1921",
     desc: "On May 31-June 1, in a race riot in Tulsa, Oklahoma, 21 Whites and 60 Blacks are killed. The violence destroyed a thriving African American neighborhood and business district."},
    {date: "1921",
     desc: "Fifty-nine Black Americans are known to have been lynched in 1921."},
    {date: "1922",
     desc: "Republicans in the Senate vote to abandon the Dyer Anti-Lynching Bill, which imposes severe penalties and fines on “any state or municipal officer convicted of negligence in affording protection to individuals in custody who are attacked by a mob bent on lynching, torture, or physical intimidation.” The bill, which was approved by the House of Representatives, also provided for compensation to the families of victims. A filibuster in the United States Senate kills this bill."},
    {date: "1922",
     desc: "Fifty-one Black Americans are known to have been lynched in 1922."},
    {date: "1923",
     desc: "Twenty-nine Black Americans are known to have been lynched in 1923."},
    {date: "1924",
     desc: "Congress passes the Immigration Act which excludes Blacks of African descent from entering the country."},
    {date: "1924",
     desc: "Sixteen Black Americans are known to have been lynched in 1924."},
    {date: "1925",
     desc: "On August 2, the Brotherhood of Sleeping Car Porters is organized. A. Philip Randolph is chosen president."},
    {date: "1925",
     desc: "Seventeen Black Americans are known to have been lynched in 1925."},
    {date: "1926",
     desc: "President Coolidge tells Congress that the country must provide “for the amelioration of race prejudice and the extension to all of the elements of equal opportunity and equal protection under the laws, which are guaranteed by the Constitution.”"},
    {date: "1926",
     desc: "Twenty-three Blacks are reported lynched during 1926."},
    {date: "1934",
     desc: "A bill that prohibits lynching fails, as President Roosevelt refuses to support it."},
    {date: "1936",
     desc: "Jesse Owens wins four gold medals in the 1936 Olympics, but is snubbed by the Chancellor of Germany, Adolf Hitler."},
    {date: "1939",
     desc: "Intimidation and cross-burning by the Ku Klux Klan in the Black ghetto of Miami fail to discourage over 1,000 of the city’s registered Blacks from appearing at the polls. The Klan parades with effigies of Blacks who will allegedly be slain for daring to vote."},
    {date: "1940",
     desc: "Eighty thousand Blacks vote in eight southern states. Five percent of voting age Blacks are registered."},
    {date: "1941",
     desc: "Dr. Charles R. Drew, a Black physician, sets up the first blood bank."},
    {date: "1941",
     desc: "The threat by Blacks to stage a massive protest march on the nation’s capital results in the issuance of Executive Order No. 8802, prohibiting discrimination in the defense establishment."},
    {date: "1942",
     desc: "The Tuskegee Airmen took their place in the Army Air Corps, making history as the first Black military pilots. The “Tuskegee Experiment” was expected to “prove” racial deficiencies in intelligence and concentration, yet the Tuskegee Institute graduated 926 African-American pilots. The 332nd Fighter Group was comprised of the 99th, 100th, 301st, and 302nd Fighter Squadrons of the U.S. Army Air Corps. The Red Tail Angels of the 332nd would end the war as the only fighter group in over 1,578 missions throughout Europe and North Africa to never lose a bomber while escorting over 200 bombing missions. \nAmerican pilots were not expected to fly more than 50 missions or so before returning home, yet the Black American pilots - due to “lack of replacements” flew closer to 100 missions. They returned home the finest pilots in the U.S. and found themselves back in “Colored Only” lines. In one case, more than a hundred Tuskegee Airmen Officers were arrested and court martialed for refusing to leave the segregated Officer’s Club at Freeman Field in Indiana. Three years later (1948), President Truman officially desegregated the Armed Forces."},
    {date: "1942",
     desc: "The Congress of Racial Equality (CORE), a civil rights group dedicated to a direct-action, nonviolent program, is founded. "},
    {date: "1943",
     desc: "The Congress of Racial Equality (CORE) stages its first “sit-in” in a Chicago restaurant."},
    {date: "1944",
     desc: "On June 6, 500 Blacks land on Omaha Beach as part of the D-Day invasion of northern France. Among them is the 761st Tank Battalion which spends 183 days in action and is cited for conspicuous courage."},
    {date: "1945",
     desc: "Despite efforts by some enlightened naval officers, over 90 percent of Blacks in the Navy are still messmen when the war ends."},
    {date: "1945",
     desc: "The War Brides Act allows foreign-born wives of U.S. citizens who had served in the U.S. armed forces to enter the U.S. "},
    {date: "1945",
     desc: "African American, Mexican, and Asian veterans of World War II return to face racism and segregation."},
    {date: "1946",
     desc: "The United States Supreme Court rules, in Morgan v. Virginia, that segregation on interstate buses is unconstitutional."},
    {date: "1947",
     desc: "Statistics indicate that 3,426 Blacks have been lynched in the United States in the period 1882-1947. Of these, 1,217 were lynched in the decade 1890-1900. From 1947 to 1962, 12 Blacks are lynched."},
    {date: "1952",
     desc: "In a series of legal maneuvers, the National Association for the Advancement of Colored People and other Black groups succeed in desegregating a number of colleges and high schools in southern and border areas. In addition, public housing projects are opened to Blacks in some northern and western cities and desegregation is achieved in several businesses and unions."},
    {date: "1954",
     desc: "By a unanimous vote, the United States Supreme Court, in the case of Brown v. Board of Education of Topeka, Kansas, declares that “separate but equal” educational facilities are “inherently unequal” and that segregation is therefore unconstitutional. The decision paves the way for large scale desegregation. This is a victory for NAACP attorney Thurgood Marshall"},
    {date: "1954",
     desc: "In Hawkins v. Board of Control, the Court rules that the Univ of FL must admit Blacks regardless of “public mischief” it might cause."},
    {date: "1954",
     desc: "The Department of Defense reports the end of “all-Negro” units in the Army. However, some bases still refuse to integrate."},
    {date: "1955",
     desc: "Two White men are arrested in Greenwood on charges of kidnapping, beating, and shooting 15-year-old Emmett Till. Till, who was from Chicago, was visiting family in Mississippi when he was kidnapped, brutally beaten, shot and dumped in the Tallahatchie River for allegedly whistling at a White woman. Two White men, J.W. Milam and Roy Bryant, are arrested for the murder and acquitted by an all White jury. Jurors acquit the defendants on grounds that the body could not be positively identified. The two men accused of this crime later boast about committing the murder in a Look magazine interview. The case becomes a cause celebre of the civil rights movement."},
    {date: "1955",
     desc: "Rosa Parks, a NAACP member takes a seat in the front of a city bus on Dec. 1, refuses to surrender it to a White man, and is arrested. In response to her arrest the Montgomery Black community launches a bus boycott, which will last for more than a year, until the buses are desegregated on December 21, 1956. As newly elected president of the Montgomery Improvement Association (MIA), Reverend Martin Luther King Jr.is instrumental in leading the boycott."},
    {date: "1957",
     desc: "The Southern Christian Leadership Conference is formed by Martin Luther King, Jr., Charles K. Steele and Fred Shuttlesworth. King is made the first president. The SCLC becomes a major force in organizing the civil rights movement and bases its principles on nonviolence and civil disobedience. According to King, it is essential that the civil rights movement not sink to the level of the racists and hate mongers who oppose them. “We must forever conduct our struggle on the high plane of dignity and discipline,” he urges."},
    {date: "1957",
     desc: "Nine Black students in Little Rock, Ark (Little Rock Nine) are turned away from formerly all-White Central High School by a White mob and the Arkansas National Guard when they arrive for classes on September 4. The National Guard, which was called to Little Rock by Governor Orval Faubus, is forced by court order to withdraw on September 20. As mobs of angry Whites assemble outside of the school and the threat of mob violence escalates, President Dwight Eisenhower issues a proclamation on September 23 ordering an end to any obstruction to court-ordered integration. On September 24, the President issues Executive Order No. 10730 authorizing the use of federal troops to assist in the integration of Central High School."},
    {date: "1960",
     desc: "Four Black students from North Carolina Agricultural and Technical College begin a sit-in at a segregated Woolworth's lunch counter in Greensboro, N.C.. Although they are refused service, they are allowed to stay at the counter. The event triggers many similar nonviolent protests throughout the South. Six months later the original four protesters are served lunch at the same Woolworth's counter. Student sit-ins would be effective throughout the Deep South in integrating parks, swimming pools, theaters, libraries, and other public facilities."},
    {date: "1960",
     desc: "The Student Non-Violent Coordinating Committee is formed to organize student protest activities. Church “kneel-ins” and beach “wade-ins” soon join lunch counter and bus station “sit-ins” as effective means of protesting segregation."},
    {date: "1960",
     desc: "As of August 1, “sit-ins” have led to successful desegregation of lunch counters in 15 American cities."},
    {date: "1960",
     desc: "10.5% of the U.S. population is considered Black – 88.6 is considered White"},
    {date: "1960+",
     desc: "Throughout the 1960’s, lawsuits challenging segregation in all areas are brought to the Supreme Court and other courts. Segregation is usually found to be unconstitutional."},
    {date: "1961",
     desc: "The Congress of Racial Equality (CORE) begins sending student volunteers on bus trips to test the implementation of new laws prohibiting segregation in interstate travel facilities. One of the first two groups of \"freedom riders,\" as they are called, encounters its first problem two weeks later, when a mob in Alabama sets the riders' bus on fire. The program continues, and by the end of the summer 1,000 volunteers, Black and White, have participated."},
    {date: "1961",
     desc: "James Meredith becomes the first Black student to enroll at the University of Mississippi. Violence and riots surrounding the incident cause President Kennedy to send 5,000 federal troops"},
    {date: "1963",
     desc: "Mississippi's NAACP field secretary, 37-year-old Medgar Evers, is murdered outside his home in Jackson, Miss.. Byron De La Beckwith is tried twice in 1964, both trials resulting in hung juries. Thirty years later he is convicted for murdering Evers."},
    {date: "1963",
     desc: "Some 250,000 people gather at the Lincoln Memorial to demonstrate on behalf of the civil rights bill pending in Congress. Dr. Martin Luther King, Jr., one of many scheduled speakers, gives what will become his most famous oration: “I Have a Dream.”"},
    {date: "1963",
     desc: "Four young girls (Denise McNair, Cynthia Wesley, Carole Robertson, and Addie Mae Collins) attending Sunday school in Birmingham, Ala. are killed when a bomb explodes at the Sixteenth Street Baptist Church, a popular location for civil rights meetings. Riots erupt in Birmingham, leading to the deaths of two more Black youths."},
    {date: "1963",
     desc: "Martin Luther King is arrested and jailed during anti-segregation protests in Birmingham, Ala.; he writes his seminal \"Letter from Birmingham Jail\" arguing that individuals have the moral duty to disobey unjust laws. \nKing targets Birmingham for a drive against discrimination. The protesters are driven back by police armed with water hoses and attack dogs. The confrontation, which has been captured on film, awakens public opinion across the country."},
    {date: "1964",
     desc: "Malcolm X leaves the Black Muslim organization, Nation of Islam, to form the Organization for Afro- American Unity–an organization emphasizing Black nationalism and social action."},
    {date: "1964",
     desc: "The 24th Amendment abolishes the poll tax, which originally had been instituted in 11 southern states after Reconstruction to make it difficult for poor Blacks to vote."},
    {date: "1964",
     desc: "The Council of Federated Organizations (COFO), a network of civil rights groups that includes CORE and SNCC, launches a massive effort to register Black voters during what becomes known as the Freedom Summer."},
    {date: "1964",
     desc: "On July 18, riots erupt in the Harlem section of New York City. One person is killed, 140 injured, and 500 arrested. This is considered the first of many large riots that are to strike urban Black neighborhoods during the sixties. Shortly after the Harlem disturbances, riots erupt in Brooklyn, New York; Rochester, New York; Jersey City, New Jersey; and Paterson, New Jersey."},
    {date: "1964",
     desc: "Three young civil rights volunteers, James Chaney, Michael Schwerner, and Andrew Goodman, are murdered. A number of arrests of federal charges, less severe than murder, follow. Among the 19 suspects are the sheriff and a deputy sheriff of Neshoba County. But no convictions are obtained and charges are dismissed in December."},
    {date: "1964",
     desc: "Dr. Martin Luther King, Jr. is awarded the Nobel Prize for Peace."},
    {date: "1964",
     desc: "President Johnson signs the Civil Rights Act of 1964. The most sweeping civil rights legislation since Reconstruction, the Civil Rights Act prohibits discrimination of all kinds based on race, color, religion, or national origin. The law also provides the federal government with the powers to enforce desegregation."},
    {date: "1965",
     desc: "A federal grand jury hands down indictments for the June 1964 slaying of three civil rights workers– James Chaney, Andrew Goodman and Michael Schwerner in Philadelphia, Mississippi. The following day eighteen men, including two law enforcement officers, are arrested. On February 25th, United States District Court Judge W. Harold Cox dismisses a federal indictment against seventeen of the accused."},
    {date: "1965",
     desc: "Malcolm X, a 39-year-old Black nationalist leader and former member of the Black Muslim sect, is shot to death in the Audubon Ballroom as he is about to deliver an address before a rally of several hundred followers. Following the murder, Black Muslim headquarters in New York and San Francisco are burned, and most Muslim leaders are placed under heavy police guard."},
    {date: "1965",
     desc: "President Lyndon Johnson announces the arrest of four Ku Klux Klan members in connection with the murder of Viola Gregg Liuzzo. Liuzzo, a 39-year-old White civil rights worker from Detroit, was slain at Lowndes County highway during the Selma-to-Montgomery Freedom March. The president declares war on the Klan, calling it a “hooded society of bigots.” Robert M. Shelton Jr., Imperial Wizard of the United Klans of America, Inc., answers the President’s charges by branding him “a damn liar.” On March 30th, the House Un-American Activities Committee votes to open a full investigation of the activities of the Klan. The Committee chairman, a Louisiana Democrat, asserts that the Klan is committing “shocking crimes.”"},
    {date: "1965",
     desc: "Blacks begin a march to Montgomery in support of voting rights but are stopped at the Pettus Bridge by a police blockade. Fifty marchers are hospitalized after police use tear gas, whips, and clubs against them. The incident is dubbed \"Bloody Sunday\" by the media. The march is considered the catalyst for pushing through the voting rights act five months later."},
    {date: "1965",
     desc: "Congress passes Voting Rights Act of 1965, making it easier for Southern Blacks to vote. Literacy tests, poll taxes, and other such requirements that were used to restrict Black voting are made illegal."},
    {date: "1965",
     desc: "Asserting that civil rights laws alone are not enough to remedy discrimination, President Johnson issues Executive Order 11246, which enforces affirmative action for the first time. It requires government contractors to \"take affirmative action\" toward prospective minority employees in all aspects of hiring and employment."},
    {date: "1965",
     desc: "The arrest and alleged mistreatment of a Black youth by White policemen sparks looting, burning, and rioting in the predominantly Black section of Watts. Thousands of National Guardsmen and state police are rushed in to quell the violence. The rioting, which lasts six days, claims the lives of thirty-five people and causes nearly 46 million dollars in property damage. On August 20, President Johnson denounces the Los Angeles rioters, comparing them to Ku Klux Klan extremists. He declares that the existence of legitimate grievances in Watts is no justification for lawlessness. “We cannot...in one breath demand laws to protect the rights of all our citizens, and then turn our back...and...allow laws to be broken that protect the safety of our citizens.”"},
    {date: "1966-1970",
     desc: "Riots in urban centers, with shootings, looting, etc., occur in Ohio, Illinois, Massachusetts (Boston), New Jersey, New York, Michigan and Connecticut."},
    {date: "1966",
     desc: "The militant Black Panthers are founded by Huey Newton and Bobby Seale."},
    {date: "1967",
     desc: "Thurgood Marshall is appointed the first Black associate justice of the United States Supreme Court."},
    {date: "1967",
     desc: "An all-White federal jury of five men and seven women returns verdicts in a retrial for the 1964 murder of three civil rights workers near Philadelphia, Mississippi. Seven men are convicted of conspiracy, eight are acquitted, and three trials end in mis-trial. Among the guilty are Chief Deputy Sheriff Cecil Price and Sam Bowers, Imperial Wizard of the Ku Klux Klan."},
    {date: "1967",
     desc: "Major race riots take place in Newark (July 12–16) and Detroit (July 23–30)."},
    {date: "1967",
     desc: "Stokely Carmichael, a leader of the Student Nonviolent Coordinating Committee (SNCC), coins the phrase \"Black power,\" defining it as an assertion of Black pride and \"the coming together of Black people to fight for their liberation by any means necessary.\" The term's radicalism alarms many who believe the civil rights movement's effectiveness and moral authority crucially depend on nonviolent civil disobedience."},
    {date: "1968",
     desc: "President Johnson’s National Advisory Commission on Civil Disorders reports on the causes of the civil disorders that disrupted the nation in 1967, identifying the major cause of the rioting as the existence of two separate bodies in America, “one Black, one White, separate and unequal.” It charges that White racism was the chief catalyst that ignited so many urban ghettos in 1967: “White institutions created it, White institutions maintain it, and White society condones it.” To overcome this terrible and crushing legacy, the commission implores the nation to initiate a massive and sustained commitment to action and reform, and appeals for unprecedented levels of “funding and performance” in housing, education, employment, welfare, law enforcement, and the mass media."},
    {date: "1968",
     desc: "The United States Senate passes the Civil Rights Bill of 1968. Among its major provisions are sweeping housing and anti-riot measures which go far beyond the federal protection offered to civil rights workers in the 1967 House version of the bill."},
    {date: "1968",
     desc: "The world is shocked by the assassination of Dr. Martin Luther King, Jr. The assassination moves the United States House of Representatives to submit to President Johnson a Senate-passed civil rights bill prohibiting racial discrimination in the sale or rental of 80 percent of the nation’s housing. Johnson signs the measure on April 11."},
    {date: "1968",
     desc: "Senator Robert Kennedy, a champion of civil rights, is shot and killed moments after leaving a rally celebrating his victory over Eugene McCarthy in the California Democratic primary."},
    {date: "1968",
     desc: "James Earl Ray, alleged assassin of Dr. Martin Luther King, Jr. is arrested."},
    {date: "1968",
     desc: "Black Panther Huey P. Newton is tried and convicted of manslaughter in the October 28, 1967 shooting death of a White policeman. Nearly three weeks later, Newton is sentenced to 2-15 years imprisonment. The trial and the conviction introduce the nation at large to a new and formidable Black Panthers."},
    {date: "1971",
     desc: "President Nixon meets with the Congressional Black Caucus, which had been trying to schedule a meeting with him for several months. The Black members of Congress request increased attention to welfare services, desegregation, housing, and social justice programs. President Nixon reportedly promises stronger enforcement of Black civil rights laws."},
    {date: "1971",
     desc: "The Supreme Court, in Swann v. Charlotte-Mecklenburg Board of Education, upholds busing as a legitimate means for achieving integration of public schools. Although largely unwelcome (and sometimes violently opposed) in local school districts, court-ordered busing plans in cities such as Charlotte, Boston, and Denver continue until the late 1990s."},
    {date: "1972",
     desc: "Some 8,000 Blacks representing a wide spectrum of political views, attend the first National Black Political Convention."},
    {date: "1972",
     desc: "Blacks achieve a number of electoral successes–the number of Blacks in Congress increases from 12 to 15."},
    {date: "1973",
     desc: "A government panel releases its final report determining whether the Tuskegee Syphilis Study, conducted between 1932 and 1972 by the Public Health Service, was justified. The study involved observing the effects of untreated syphilis of 430 Black men living in rural Macon County, Alabama. The panel found no evidence that participants in the study had been given any type of informed consent. The panel concluded that the study was unjustified on both scientific and humanitarian grounds and that all policies regarding research on humans be reformed."},
    {date: "1974",
     desc: "The Department of Justice releases memos revealing that in the 1960’s and early 1970’s, the Federal Bureau of Investigation had waged a campaign designed to disrupt, discredit, and neutralize Black nationalist groups, including the Black Panther Party. A major objective of the effort, according to the memo, was to prevent the emergence of a Black leader capable of uniting disparate factions and inspiring violence. Reverend Jesse Jackson remarks that the documents implicate the FBI in the deaths of the Reverend Dr. Martin Luther King, Jr., Malcolm X, and Fred Hampton."},
    {date: "1974",
     desc: "Violence erupts between supporters and opponents of public school integration."},
    {date: "1977",
     desc: "Author Alex Haley receives a Pulitzer Prize for his book Roots."},
    {date: "1978",
     desc: "Hearing the case University of California v. Bakke, the United States Supreme Court, in a 5 to 4 decision, orders that White student Allan P. Bakke be admitted to the medical school at the University of California, Davis. The Court rules that the refusal to admit Bakke is tantamount to reverse discrimination and that the use of racial or ethnic quotas is an improper means of achieving racial balance. The Court also holds that the college’s affirmative action program is invalid, since it had the effect of discriminating against qualified White applicants, although the Court perceived the goal of attaining a diverse student body constitutional and permissible."},
    {date: "1980",
     desc: "11.7% of the U.S. population is considered Black – 79.6 is considered White not Hispanic (BRIDGE)"},
    {date: "1980",
     desc: "The Black Liberty City area and predominantly Black Coconut Grove section of Miami erupt into riotous violence, ending with 9 dead and 163 injured, following the acquittal of four White Dade County police officers in the beating death of a Black man."},
    {date: "1980",
     desc: "A ruling authorizing Congress to impose racial quotas to remedy past discrimination against minority contractors in federal jobs programs is upheld by the Supreme Court."},
    {date: "1981",
     desc: "A bill which prohibits the use of numerical quotas devised to increase the hiring or school enrollment of minorities and women is introduced. Entitled the “Equal Employment Opportunity Act,” it seeks to amend the Civil Rights Act of 1964 and prevents the federal government from imposing rules on employers or schools to hire workers or to admit students on the basis of race, sex, or national origin. In effect, the proposal no longer requires companies and educational institutions to make up for past discrimination by taking on a set number of minorities and women within a specified time frame."},
    {date: "1981",
     desc: "The Justice Department announces it will no longer continue its vigorous pursuit of mandatory busing and the use of racial quotas in employment discrimination cases. It also considers amendments which would make “reverse discrimination” illegal under the Civil Rights Acts of 1964."},
    {date: "1983",
     desc: "In an 8 to 1 decision, the Supreme Court rules that private schools which discriminate on the basis of race are not eligible for tax exemptions."},
    {date: "1985",
     desc: "The United States Commission on Civil Rights gives enthusiastic support to a Supreme Court decision giving existing seniority systems preference over affirmative action programs even though the Blacks were hired to remedy previously contended discriminatory hiring practices."},
    {date: "1986",
     desc: "The Supreme Court in Wygant v. Jackson Board of Education (first of three major affirmative action decisions, rules 5 to 4 that broad affirmative action plans including hiring goals are permissible if carefully tailored to remedy past discrimination. In a ruling involving teachers laid off in Jackson, Michigan, the court sends a mixed signal by deciding that public employers cannot give affirmative action plans as a substitute for seniority when reducing their work forces."},
    {date: "1986",
     desc: "The United States Supreme Court ruling on an action regarding Cleveland printers and New York sheet- metal workers upholds the use of affirmative action plans designed to remedy past discrimination. The decision, Sheet Metal Workers International v. EEOC, rejects the Reagan administration’s argument that only specific victims of discrimination are entitled to such relief."},
    {date: "1987",
     desc: "New regulations are issued to strengthen the federal government’s authority to reject changes in local election laws that have a discriminatory result. No longer does the legal process have to prove that the intent of the local law was to discriminate, it needs only to demonstrate that it could have a discriminatory result."},
    {date: "1987",
     desc: "A federal grand jury indicts ten White supremacists on charges of conspiring to assassinate federal officials, including a judge, and kill members of ethnic groups through bombings."},
    {date: "1988",
     desc: "Overriding President Reagan’s veto, Congress passes the Civil Rights Restoration Act, which expands the reach of non-discrimination laws within private institutions receiving federal funds."},
    {date: "1989",
     desc: "FBI Director William Sessions orders sweeping changes in the Bureau’s affirmative action program after finding that the bureau had discriminated against minority employees. Ironically, the FBI is the agency charged with enforcing the nation’s civil rights laws."},
    {date: "1989",
     desc: "The United States Supreme Court toughens the requirements for proof of discriminatory impact in job discrimination suits. The Court also declared that in such cases, an employer might justify policies which have a discriminatory impact by providing a reasonable business explanation. In a second case, the Supreme Court rules by a 5 to 4 majority that White workers claiming unfair treatment due to affirmative action settlements can seek compensation under civil rights legislation."},
    {date: "1990",
     desc: "The Quality Education for Minorities Project releases its report and recommendations aimed at making schools more responsive to the needs of minority students. The project concludes that minority students are taught in “separate but decidedly unequal” schools resulting in a “gap between minority and non-minority educational achievements.”"},
    {date: "1990",
     desc: "President George Bush vetoes the Civil Rights Act of 1990. On October 16, the Senate passes the bill by a vote of 62 to 34; the House of Representatives passes the bill on October 17, by a 273 to 154 vote. The legislation is designed to reverse the Court’s 1989 decision in the case of Wards Cove Packing Co. v. Antonio, which made it more difficult for minorities and women to prove job discrimination. Bush cites his fear of the introduction of quotas in the workplace as his reason for rejecting the act. On October 24, an attempt to override the veto in the Senate falls one vote short of the two-thirds majority needed."},
    {date: "1991",
     desc: "Results from a nationwide survey sponsored by the National Science Foundation reveal that White Americans continue to hold negative stereotypes of Blacks and Hispanics. Three-quarters of the Whites surveyed felt that Blacks and Hispanics are more likely to prefer welfare to work. A Census Bureau report shows the household worth of White families average eight times that of Hispanic households and ten times that of Black households."},
    {date: "1991",
     desc: "Black motorist Rodney King is severely beaten by several White police officers after being stopped for a speeding violation."},
    {date: "1991",
     desc: "After two years of debates, vetoes, and threatened vetoes, President Bush reverses himself and signs the Civil Rights Act of 1991, strengthening existing civil rights laws and providing for damages in cases of intentional employment discrimination."},
    {date: "1991",
     desc: "Washington, DC: The creation of a National African American Museum is approved within the Smithsonian Institution."},
    {date: "1992",
     desc: "President George Bush signs a proclamation officially declaring January 20, Martin Luther King Jr.’s birthday, as a holiday."},
    {date: "1992",
     desc: "Spike Lee’s film Malcolm X starts a renewed interest in the slain civil rights leader."},
    {date: "1992",
     desc: "Carol Mosely Braun becomes the first Black woman elected to the United States Senate."},
    {date: "1992",
     desc: "Riots erupt in Los Angeles following the acquittal of four White police officers in the beating of Black motorist Rodney King."},
    {date: "1992",
     desc: "A study conducted by the Federal Reserve’s regional bank shows evidence of bank discrimination against minorities applying for mortgages. The study measures Black, Hispanic, and White rejection rates when all applicants had similar application criteria. The findings show 17 percent rejection of minorities compared to 11 percent rejection of Whites."},
    {date: "1993",
     desc: "Dr. Joycelyn Elders is sworn in as U.S. Surgeon General."},
    {date: "1994",
     desc: "Denny’s Restaurants agree to pay $54 million to settle lawsuits by African Americans who claim they were discriminated against by the restaurant chain."},
    {date: "1994",
     desc: "Civil rights activist Rosa Parks is beaten and robbed in her home."},
    {date: "1995",
     desc: "After 130 years, Mississippi lawmakers ratify the 13th Amendment abolishing slavery."},
    {date: "1995",
     desc: "The University of California votes to eliminate affirmative action policies in the admission of students."},
    {date: "1995",
     desc: "The Million Man March, organized by the Nation of Islam leader Louis Farrakhan, draws African American men to the nation’s capital."},
    {date: "1995",
     desc: "O.J. Simpson is acquitted of the murder of his ex-wife Nicole Brown Simpson and her friend, Ron Goldman. The O.J. Simpson trial was televised daily throughout the United States and fueled extensive debate regarding race relations in America."},
    {date: "1995-2001",
     desc: "Typical families of color saw their net worth (assets minus debts) fall 7%, while typical White families’ net worth grew 37% to $120,900"},
    {date: "1996",
     desc: "Proposition 209, introduced as a ballot initiative, is passed by the California voters. The initiative bars preferential treatment based on race or gender, virtually eliminating affirmative action in state hiring, public contracts, and education. Although challenged in the court, the U.S. Supreme Court refuses to hear the appeal, and Proposition 209 eventually takes effect in California."},
    {date: "1997",
     desc: "President Clinton offers a national apology to the Black men and their families who were victims of the Tuskegee study."},
    {date: "1998",
     desc: "James Byrd Jr., 49, a Black salesman, is dragged to death by 3 racists in Jasper, Texas; his body is dismembered."},
    {date: "1998",
     desc: "The median net worth for Hispanic, African American, Asian and other minority families was $16,400, less than one-fifth the $94,900 median net worth for non-Hispanic White families"},
    {date: "1998",
     desc: "KKK leader Samuel Bowers is convicted in Mississippi for the 1966 murder of Civil Rights Leader Vernon Dahmer."},
    {date: "2000",
     desc: "12.3% of the U.S. population is considered Black – 75.1% is considered White not Hispanic"},
    {date: "2001",
     desc: "Colin Powell sworn in by president George Bush as Secretary of State."},
    {date: "2003",
     desc: "In the most important affirmative action decision since the 1978 Bakke case, the Supreme Court (5–4) upholds the University of Michigan Law School's policy, ruling that race can be one of many factors considered by colleges when selecting their students because it furthers \"a compelling interest in obtaining the educational benefits that flow from a diverse student body.\" \nIn separate decisions the high court strikes down a point system used by the University of Michigan’s undergraduate programs but approves a separate policy used by the University of Michigan law school that gives race less prominence in the admissions decision-making process."},
    {date: "2005",
     desc: "Condoleezza Rice sworn in by president George Bush as Secretary of State."},
    {date: "2005",
     desc: "The ringleader of the Mississippi civil rights murders, Edgar Ray Killen, is convicted of manslaughter on the 41st anniversary of the crimes."},
    {date: "2005",
     desc: "U.S. Senate approved a civil rights “cold case” unit. The Unsolved Crimes Section would target pre-1970 homicides motivated by racial hatred that remained unsolved, often because of lax state and federal prosecution at the time they occurred."},
    {date: "2005",
     desc: "Hurricane Katrina devastates New Orleans and other parts of the South. Issues of classism and racism are exposed in the aftermath of the governments’ response to victims of the Hurricane. National television coverage portrays images that mirror those of third world countries."},
    {date: "2005",
     desc: "Civil rights leader, Rosa Parks, dies at age 92"},
    {date: "2006",
     desc: "Civil rights leader and wife of Martin Luther King, Jr., Coretta Scott King, dies at age 78"},
    {date: "2006",
     desc: "Shani Davis wins the gold medal in speedskating 1000 meters, becoming the first African American to win an individual gold medal at the Winter Olympics."},
    {date: "2006",
     desc: "In Parents v Seattle and Meredith v Jefferson the Supreme Court ruled, 5 to 4, that programs in Seattle, WA and Louisville, KY, which tried to maintain diversity and integration in schools by considering race when assigning students to schools, are unconstitutional"},
    {date: "2007",
     desc: "Tuskegee Airmen, first all Black aerial units, bestowed Congressional Gold Medals at US Capitol"},
    {date: "2007",
     desc: "Tony Dungy is the first African American or Black person to win the Super Bowl as both a player and a coach."},
    {date: "2008",
     desc: "Barack Obama is elected the first African American President of the United States of America. Lieutenant Governor David Paterson becomes first African American governor of New York, and the first legally blind governor of any US state."},
    {date: "2008",
     desc: "Cullen Jones becomes 2nd African American to win an Olympic Gold medal in swimming as part of the US swim team."},
    {date: "2008",
     desc: "Actor, director and screenwriter, Tyler Perry becomes first African American to own a major film and television studio"},
    {date: "2008",
     desc: "California Democrat, Karen Bass, becomes the first African American woman elected as Speaker of a state House of Representatives"},
    {date: "2009",
     desc: "Pop icon, Michael Jackson, dies at age 50."},
    {date: "2009",
     desc: "Foreign policy advisor, Susan Rice, becomes first African American woman to be the United States UN ambassador"},
    {date: "2009",
     desc: "Barack Obama is inaugurated the first African American President of the United States of America. Michelle Obama becomes the first African American First Lady in US history."},
    {date: "2009",
     desc: "Eric Holder becomes the 82nd Attorney General of the United States , and the first African American to hold the position"},
    {date: "2009",
     desc: "Disney unveils The Princess and the Frog, the studio’s first animated film featuring an African American princess"},
    {date: "2010",
     desc: "Kamala Harris elected Attorney General of California, becoming the first woman, the first African American, and the first Indian American in California history to hold this position"},
    {date: "2010",
     desc: "President Obama signs legislation to pay Black farmers about $4.6 billion to compensate for decades of discrimination suffered at the hands of the United States government"},
    {date: "2011",
     desc: "On September 21, Troy Davis was executed by lethal injection. The was despite compelling evidence, as well as support from former president Jimmy Carter, Pope Benedict XVI, NAACP, and 600,000 people worldwide pleading for his innocence. The act was thought of as a racial hate crime and caused public uproar."},
    {date: "2011",
     desc: "Over 50% of unemployed Black Americans were out of work for more than six months following the recession. This was the largest long-term unemployment period among all ethnic groups."},
    {date: "2012",
     desc: "On February 26, 17-year old Trayvon Martin was fatally shot by George Zimmerman while walking home from the store. Martin was unarmed, and Zimmerman expressed Martin looked suspicious with a hooded sweatshirt on. This lead to the March 21 “Millions for Hoodies” in New York City"},
    {date: "2012-04-20",
     desc: "Cumberland County Senior Resident Superior Court Judge Gregory Weeks issued the first decision under North Carolina’s Racial Justice Act. He ruled that there was racial bias against Marcus Robinson during his 1991 trial. Despite the ruling made by Weeks, State legislature passed measures that weakened the racial Justice Act."},
    {date: "2012",
     desc: "51% of American claimed anti-black sentiments. This is a 3% increase from 2008."},
    {date: "2012",
     desc: "Barack Obama was inaugurated for his second term as the first Black president of the U.S."},
    {date: "2013",
     desc: "Merrill Lynch settled a $160 million dollar racial discrimination law suit brought on by African American brokers at the firm. According to employment records there was no African American brokers in 552 of the 639 offices owned by Lynch. 75% of the African American brokers were not asked to further employment after the training period. In addition, the brokers were invited to golf outings on courses that refused Black people service, as well as endured constant racial slurs provided by their peers."},
    {date: "2013",
     desc: "A federal court awarded a White police officer $620,000 for a “reverse racism” lawsuit. The officer claimed that a Black woman was hired for a job position over him because “the academy needed more color”. The all White jury only took hours to come deem this a “reverse racism” act. Due to the circumstances, the Black woman hired for the job resigned."},
    {date: "2013",
     desc: "Bank of America was fined for discriminating against African American job candidates. 1,100 African Americans were refused various positions in the company over the years 1993-2005, in Charlotte, North Carolina."},
    {date: "2013",
     desc: "The activist movement Black Lives Matter is founded after George Zimmerman’s acquittal."},
    {date: "2014",
     desc: "On August 9th, Michael Brown was fatally shot in Ferguson, Missouri. The unarmed 18-year old African American man was shot at by a White officer after a shop lifting event."},
    {date: "2014",
     desc: "Poet and Author Maya Angelou dies on May 28"},
    {date: "2014",
     desc: "My Brother’s Keeper”, is launched by President Obama. This initiative aims to improve the lives of young boys and men of color by offering better opportunities, as well as aiding in better life outcomes. $200 Million dollars will be donated by ten different investment firms over the next five years."},
    {date: "2014",
     desc: "54% of African Americans claim to be victims in bullying scenarios compared to the 44% of white correspondents in a Workplace Bullying Survey. An example of this bullying made headlines when two current and two former African American employees sued Daimler trucks North America, in Portland, Oregon. The African American men claimed that a dozen White employees threatened them with physical violence, graffiti of “hangman’s nooses” drawn on lockers, as well as placing rotten food in the back of their lockers."},
    {date: "2014",
     desc: "Eric Garner is killed by New York police"},
    {date: "2015",
     desc: "Loretta Lynch becomes the first African American female Attorney General, winning to a 56-63 vote. Her nomination was delayed due the the Republican party urging Democrats to revise abortion language in an unrelated bill."},
    {date: "2015-03-07",
     desc: "Obama speaks with 20,000 other people to commemorate the 50 years since Dr. Martin Luther King Jr.’s march in Selma, Alabama. In his speech, Obama explained that African Americans have come a long way but “the march isn’t finished yet.”"},
    {date: "2015",
     desc: "Further investigation in Ferguson, Missouri’s crimes over the past two years show that black people were being targeted for various crimes. 85% of traffic stops, 90% of tickets issued, and 93% of arrests were of African American citizens. Even in jaywalking incidents, African Americans made up 90% of the violation populations."},
    {date: "2015",
     desc: "According to a 2015 report titled “Black Girls Matter: Pushed Out, Overpoliced and Underprotected” analyzed data pulled from New York City and Boston school districts. It found that 12% of black girls were subjected to suspension compared to 2% of white girls. 90% of all female students that experienced expulsion were black."}]};

module.exports = BlackTimeline;
