/*jslint white, fudge */

MultiTimeline = {name: "Multiracial", ident: "Multi", code: "R",
   credit: "Compiled by: Karen L. Suyemoto, Ph.D. – UMass (Boston) Psychology and Asian American Studies. Updated 2005/2006 by Claudia Fox Tree and Elli Stern for EMI Empowering Multicultural Initiatives. Updated 2014 by Emily Davis, for K. Suyemoto.",
   resources: [
       "Children of Conflict. Fernando Henriques. NY: E.P. Dutton & Co, Inc., 1975 (CC)",
       "Disciplined Hearts, Theresa DeLeane O'Nel. LA: University of California Press, 1996 (DH)",
       "Marriage in Black and White. Joseph R. Washington, Jr. Boston: Beacon Press, 1970 (MBW)",
       "The Multiracial Experience. Maria P. P. Root (ed.). CA: Sage Publications, Inc., 1996 (ME)",
       "Race and Mixed Race, Naomi Zack. Philadelphia, PA: Temple University Press, 1993 (R&MR)",
       "Racially Mixed People in America. Maria P. P. Root (ed.). CA: Sage Publications, Inc., 1992 (RMP)",
       "White By Law, Haney López. NY: New York University Press, 1996 (WBL)",
       "Who is Black? F. James Davis. PA: The Pennsylvania State University, 1991 (WIB)",
       "http://www.eugenic-watch.com/roots/chap07.html Laws Against Mixing Races",
       "http://www.oah.org/pubs/magazine/family/cruz-berson.html The American Melting Pot? Miscegenation Laws in the United States by Barbara C. Cruz and Micahel J. Berson, Organization of American Historians",
       "http://lovingday.org/map.htm",
       "http://www.allbusiness.com/government/government-bodies-offices-legislative/8893132-1.html"],
   entries: [
    {date: "1492",
     desc: "Columbus “discovers” the Americas. Although in the U.S. this is commemorated as Columbus Day, in parts of Latin American, they celebrate El Día de la Raza (the Day of the [New Mixed] Race)."},
    {date: "1614",
     desc: "The first recorded interracial marriage in North American history between John Rolfe and Pocahontas."},
    {date: "1630",
     desc: "A Jamestown, Virginia court order states that \"a White man... be soundly whipped before an assemblage of Negroes and others for abusing himself to the dishonor of God and the shame of Christians by defiling his body in lying with a Negro, which fault he is to acknowledge next Sabbath day.\""},
    {date: "1662",
     desc: "Virginia is the first state (actually, a colony at this time) to establish anti-miscegenation laws because “sexual intercourse between a White and a Black was twice as evil as fornication between two White adults.” If law was broken, punishment could have been a public whipping."},
    {date: "1664",
     desc: "The first anti-miscegenation law in Maryland is passed."},
    {date: "1691",
     desc: "Virginia enacts legislation to prohibit marriage and fornication between Whites and non-Whites. The legislation states that: \"...for the prevention of that abominable mixture and spurious issue which may hereafter increase in this dominion with English, or White women, as well as by their unlawful accompanying with one another. Be it enacted... that for the time to come whatsoever English or White man or woman being free shall intermarry with a Negro, mulatto, or Indian man or woman, bound or free, shall within three months thereafter be banished and removed from the dominion forever...and be it further enacted... that if any English or White woman shall have a bastard child by a Negro or mulatto, she shall pay the sum of fifteen pounds sterling, within one month after the child is born, to the wardens of the parish, where she shall be delivered of such child, and in default of such payment, she shall be taken into possession of the said church wardens and disposed of for five years... and such bastard child shall be found out as a servant by the said church wardens until he or she shall attain the age of thirty years.\""},
    {date: "1705",
     desc: "Massachusetts follows VA and prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1715",
     desc: "North Carolina prohibits intermarriage between Whites and Negroes or mulattos"},
    {date: "1717",
     desc: "South Carolina prohibits intermarriage between Whites and Negroes or mulattos"},
    {date: "1724",
     desc: "Louisiana prohibits intermarriage between Whites and Negroes or mulattos"},
    {date: "1725",
     desc: "Pennsylvania prohibits intermarriage between Whites and Negroes or mulattos"},
    {date: "1741",
     desc: "Tennessee prohibits intermarriage between Whites and Negroes or mulattos"},
    {date: "1750",
     desc: "Georgia prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1780",
     desc: "Pennsylvania legalizes interracial marriage."},
    {date: "1784",
     desc: "Patrick Henry presents a Bill to the Virginia Legislature reflecting the philosophy that racial mixing will address social problems stating that: \"...every White man who married an Indian woman should be paid ten pounds, and five for each child born of such a marriage; and that if any White woman married an Indian she should be entitled to ten pounds with which the county court should buy them livestock; that once each year the Indian husband of this woman should be entitled to three pounds with which the county court should buy clothes for him; that every child born to the Indian man and White woman should be educated by the state between the ages of ten and twenty-one years...\""},
    {date: "1785",
     desc: "Virginia draws a genetic line, legally defining a Negro as a person with a Black parent or grandparent."},
    {date: "1792",
     desc: "Kentucky prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1798",
     desc: "Rhode Island prohibits intermarriage between Whites and Negroes, Indians, or mulattos."},
    {date: "1792",
     desc: "Kentucky prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1807",
     desc: "Delaware prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1808",
     desc: "The Louisiana Civil Code prohibits \"free people of color\" from marrying Blacks or Whites."},
    {date: "1818",
     desc: "Indiana prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1820's-1860's",
     desc: "John Ross, only one-eighth Cherokee by blood, utilized his knowledge of the White man’s system to fight against outside encroachment on his tribe’s property and forced removal of his people from the Southeast to Indian territory"},
    {date: "1821",
     desc: "Maine prohibits intermarriage between Whites and Negroes, Indians, or mulattos."},
    {date: "1822",
     desc: "Mississippi prohibits intermarriage between Whites and Negroes or mulattos. In 1892 the law is expanded to explicitly include Mongolians."},
    {date: "1829",
     desc: "Illinois prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1832",
     desc: "Florida prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1835",
     desc: "Missouri prohibits intermarriage between Whites and Negroes or mulattos. In 1909 the law is expanded to include Mongolians."},
    {date: "1836",
     desc: "In South Carolina, Judge Harper rejects the criterion of racial visibility and declares a person to be White based on acceptance by Whites."},
    {date: "1837",
     desc: "Texas prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1838",
     desc: "Michigan and Arkansas prohibit intermarriage between Whites and Negroes, Indians, or mulattos."},
    {date: "1839",
     desc: "Iowa prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1840",
     desc: "Mulatto is provided as a category on the census, but is not defined as a term."},
    {date: "1843",
     desc: "Massachusetts legalizes interracial marriage."},
    {date: "1850",
     desc: "California prohibits intermarriage between Whites and Negroes or mulattos. In 1880, they will expand the law to include \"Mongolians\""},
    {date: "1850-1860",
     desc: "Mulatto slave population increases by 66.9 percent while Black slave population increases by 19.8 percent. As a result, many states enforce a “one drop” rule which said that anyone with even a distant African ancestor was Black and therefore prohibited from “co-mingling” with other races."},
    {date: "1851",
     desc: "Iowa legalizes interracial marriage."},
    {date: "1852",
     desc: "Alabama and Utah prohibit intermarriage between Whites and Negroes or mulattos. In 1888, Utah expands their law to include “Mongolians.”"},
    {date: "1854",
     desc: "Henry Hughs of Mississippi states: \"Impurity of the races is against the law of nature. Mulattos are monsters. The law of nature is the law of God. The same law which forbids consanguineous amalgamation forbids ethnical amalgamation. Both are incestuous. Amalgamation is incest.\""},
    {date: "1855",
     desc: "Kansas, Nebraska and Washington prohibit intermarriage between Whites and Negroes, Indians (in Washington), or mulattos. Nebraska adds Chinese and Japanese to the prohibition in 1913."},
    {date: "1853",
     desc: "Joseph Arthur de Count Gobineau, a well known anthropologist and French diplomat Persia and Brazil publishes The Inequality of the Human Races, where he argues for the supremacy of the White race, further stating that racial mixing degenerates the White race and causes problems because different (and confllicting) characteristics are carried in different races’ blood."},
    {date: "1857",
     desc: "New Mexico prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1851",
     desc: "Kansas legalizes interracial marriage."},
    {date: "1861",
     desc: "Mulattos form a Negro regiment to defend Louisiana but are disarmed by White officers."},
    {date: "1861",
     desc: "In response to Chinese immigration, Nevada passes the first anti-miscegenation laws explicitly targeting Asian Americans, prohibiting marriage between Blacks, mulattos, Indians, and Chinese. Other western states follow the next few decades."},
    {date: "1861",
     desc: "Ohio prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1862",
     desc: "Oregon prohibits intermarriage between Whites and Negroes, Indians, or mulattos. In 1866 they expand this to include Chinese, and in 1893 they include all Mongolians."},
    {date: "1863",
     desc: "West Virginia prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1864",
     desc: "Colorado and Idaho prohibit intermarriage between Whites and Negroes, mulattos, or Chinese (in Idaho). In 1921 Idaho expands the law to include all Mongolians."},
    {date: "1865",
     desc: "Arizona prohibits “All marriages of white persons with negroes, mulattoes, Indians, or Mongolians.” This is the first use of the term “Mongolian” as a racialized term for Asian Americans in anti-miscegenation laws."},
    {date: "1866",
     desc: "New Mexico legalizes interracial marriage."},
    {date: "1868",
     desc: "Washington legalizes interracial marriage."},
    {date: "1870",
     desc: "1870, 1880 Census Mulattos are officially defined to include \"quadroons, octoroons, and all persons having any perceptible trace of African blood.\""},
    {date: "1871",
     desc: "In The Descent of Man, Charles Darwin concludes that races are not sub-species, but all people are one species, challenging the basis of \"scientific\" objections to racial mixing."},
    {date: "1874",
     desc: "Illinois legalizes interracial marriage."},
    {date: "1870+",
     desc: "The U.S. Government, seeks the signatures of mixed blood Indians to satisfy the three-fourths approval of tribal adult males prerequisite to the distribution. In a later reversal of stance, when strong antigovernment stances by tribes were partially instigated by mixed bloods or when the U.S. government wanted to cut expenditures for Native Americans, the government has tried to categorize as non-Indian those with lesser blood quantum (less than one-half blood quantum)."},
    {date: "1868",
     desc: "Rhode Island legalizes interracial marriage."},
    {date: "1883",
     desc: "Maine and Michigan legalize interracial marriage."},
    {date: "1887",
     desc: "Allotment Act - Federal Act which implements \"blood quantum\" restrictions as well as formal enrollment into Native American tribes."},
    {date: "1887",
     desc: "Ohio legalizes interracial marriage."},
    {date: "1890",
     desc: "Census takers are told to record the exact proportion of the \"African blood\" - relying solely on visibility."},
    {date: "1896",
     desc: "Plessy v. Ferguson - the precedent-setting \"separate-but-equal\" case - the U.S. Supreme Court dispensed with Plessy's contention that because he was only one-eighth Negro and could pass as White, he was entitled to ride in the seats reserved for Whites. The Court states that a Negro or Black is any person with any Black ancestry. This formalized the “one-drop” rule or the rule of hypodescent."},
    {date: "1897",
     desc: "Oklahoma prohibits intermarriage between Whites and Negroes or mulattos."},
    {date: "1898",
     desc: "U.S. v. Wong Kim Ark - The U.S. Supreme Court rules that native-born children of aliens, even those permanently barred by race from acquiring citizenship, were birthright citizens of the United States."},
    {date: "1900s",
     desc: "In the early 1900's, the eugenics movement supplied a new set of arguments to support existing restrictions on interracial marriage. These arguments incorporated a \"scientific\" brand of racism, emphasizing the supposed biological dangers of mixing the races – also known as miscegenation."},
    {date: "1900",
     desc: "Booker T. Washington states social reality: \"It is a fact that, if a person is known to have one percent of African blood in his veins, he ceases to be a White man. The ninety-nine percent of Caucasian blood does not weigh by the side of the one percent of African blood. The White blood counts for nothing. The person is a Negro every time.\""},
    {date: "1900",
     desc: "By 1900, the mestizos (Spanish and Native American heritage) have become the largest ethnic group in Mexico."},
    {date: "1900",
     desc: "Census specifies that \"pure Negroes\" be counted separately from Mulattos. Mulatto is defined as \"all persons with some trace of Black blood.\""},
    {date: "1881-1906",
     desc: "Compilation of the Devil's Dictionary, in which Mulatto is defined as \"n. A child of two races, ashamed of both.\""},
    {date: "1909",
     desc: "South Dakota, North Dakota, and Montana, prohibit intermarriage between Whites and Negroes, mulattos, or Chinese and Japanese (in Montana). South Dakota expands their law in 1913 to include Mongolians."},
    {date: "1910",
     desc: "Census indicates that 21 percent of the Black population is of visible mixed race."},
    {date: "1912",
     desc: "Nevada updates its anti-miscegenation law to address Filipino immigration and add “color” language: “It shall be unlawful for any person of the Caucasian or white race to intermarry with any person of the Ethiopian or black race, Malay or brown race, Mongolian or yellow race, or the American Indian or red race, within the State of Nevada”"},
    {date: "1913",
     desc: "The first study on passing is done by Dr. Charles B. Davenport."},
    {date: "1913",
     desc: "South Dakota prohibits marriage of \"persons belonging to the African, Corean [sic], Malayan, or Mongolian race with any person of the opposite sex belonging to the Caucasian or White race\". Wyoming prohibits \"all marriages of white persons with Negroes, Mulattoes, Mongolians or Malays\""},
    {date: "1913-1947",
     desc: "The 30 to 48 states maintain anti-miscegenation laws."},
    {date: "1916",
     desc: "Eugenicist, Madison Grant writes The Passing of the Great Race. According to Grant, the result of White and non-White racial mixing will always be a race reverting to the \"lower race\" in evolutionary specialization. Therefore, Grant reasoned, the mix of a White man and an Indian was an Indian; a White man and a Negro, a Negro; a White man and a Hindu, a Hindu; and any European race and a Jew, a Jew."},
    {date: "1920",
     desc: "The census drops Mulatto as a category. Black is defined to mean any person with any Black ancestry. (this definition continues until the 2000 Census)."},
    {date: "1920s",
     desc: "Eugenicists pass laws in more than half of the states that prohibited marriages between Blacks and Whites."},
    {date: "1922",
     desc: "Cable Act declares that any American female who marries “an alien ineligible to citizenship” would lose her citizenship."},
    {date: "1924",
     desc: "Virginia expands its anti-miscegenation law, prohibiting the marriage of whites to \"Negroes, Mongolians, American Indians, Asiatic Indians, and Malays\""},
    {date: "1924",
     desc: "The Racial Integrity Act passes in Virginia, proclaiming the existence of only two racial categories: \"pure\" White and everybody else (i.e. colored). The act made interracial marriages illegal and classified many Native Americans as Black. The law strips people of color of their land, voting rights, and legal identity. It emphasized the \"scientific\" basis of race assessment, and the degenerative dangers of race mixing"},
    {date: "1927",
     desc: "Georgia passes all-encompassing anti-miscegenation law: “It shall be unlawful for a white person to marry anyone but a white person. Any marriage in violation of this section shall be void.”"},
    {date: "1931",
     desc: "The Cable Act is amended, allowing U.S. women to retain the citizenship after marriage to aliens ineligible for citizenship. The Act is finally repealed in 1936."},
    {date: "1935",
     desc: "Indian Reorganization Act - tribes are urged to reorganize political structures and to adopt more exclusive enrollment requirements. (DH)"},
    {date: "1948",
     desc: "California legalizes interracial marriage."},
    {date: "1950s-1960s",
     desc: "Civil Rights Movement causes Adoption Industry to open up to and agencies work with Black families for the first time. TRA begin to increase with its “colorblind” placement practices."},
    {date: "1950",
     desc: "By this time, anti-miscegenation legislation had extended beyond unions between Blacks and Whites and included Mongolians, Malayans, Mulattos and Native Americans."},
    {date: "1951",
     desc: "Oregon legalizes interracial marriage."},
    {date: "1953",
     desc: "Montana legalizes interracial marriage."},
    {date: "1955",
     desc: "Virginia State Supreme Court of Appeals upholds anti-miscegenation laws, stating that the laws served legitimate purposes, including: \"to preserve the racial integrity of its citizens\", and to prevent \"the corruption of blood\", \"a mongrel breed of citizens\", and \"the obliteration of racial pride.\""},
    {date: "1955",
     desc: "North Dakota legalizes interracial marriage."},
    {date: "1957",
     desc: "Colorado and South Dakota legalize interracial marriage."},
    {date: "1959",
     desc: "Langston Hughes publishes his poem \"Cross\"\nMy old man's a White old man,\nAnd my old mother's Black,\nIf I ever cursed my White old man,\nI take my curses back.\nIf I ever cursed my Black old ma\nAnd wished she were in hell, I'm sorry for that evil wish,\nAnd now I wish her well.\nMy old man died in a fine White house,\nMy ma died in a shack,\nI wonder where I'm gonna die,\nBeing neither White nor Black."},
    {date: "1959",
     desc: "Idaho and Nevada legalize interracial marriage."},
    {date: "1959",
     desc: "Mildred Jeter and Richard Loving are married in Washington DC and arrested when they return home to Virginia for violating VA’s anti-miscegenation law. Jeter and Loving plead guilty to the charge of miscegenation in Virginia court and are sentenced to a year in jail, which they could avoid by leaving Virginia and staying out for 25 years. They appeal the ruling."},
    {date: "1962",
     desc: "Arizona legalizes interracial marriage."},
    {date: "1963",
     desc: "Nebraska and Utah legalize interracial marriage."},
    {date: "1964",
     desc: "The U.S. Supreme Court, which ruled against Jim Crow laws in the 1954 decision of Brown v. Board of Education, ruled as invalid a Florida statute that allowed harsher penalties for cohabitation and adultery by interracial couples than same-race couples in McLaughlin v. Florida. This case is said to be a predecessor to the Loving v. Virginia case (in 1967)."},
    {date: "1965",
     desc: "Indiana and Wyoming legalize interracial marriage."},
    {date: "1967",
     desc: "Loving v. Virginia (the case involving Mildred Jeter and Richard Loving) is heard by the U.S. Supreme Court which strikes down anti-miscegenation laws as unconstitutional, ruling that distinctions between citizens solely because of their ancestry were \"odious to a free people whose institutions are founded upon the doctrine of equality.\""},
    {date: "1967",
     desc: "17 states still have anti-miscegenation laws: Alabama, Arkansas, Delaware, Florida, Georgia, Kentucky, Louisiana, Maryland, Mississippi, Missouri, North Carolina, Oklahoma, South Carolina, Tennessee, Texas, Virginia and West Virginia. Only 9 states never had anti-miscegenation laws (Alaska, Connecticut, Hawai’i, Minnesota, New Hampshire, New Jersey, New York, Vermont, and Wisconsin)."},
    {date: "1970s",
     desc: "Interracial marriages begin to boom, as do multiracial offspring."},
    {date: "1972",
     desc: "In response to an increase in Black babies being adopted by White people and the Black pride movement, the National Association of Black Social Workers (NABSW) declares that such placements are a form of racial and cultural genocide."},
    {date: "1975",
     desc: "The Vietnam war ends, leaving approximately 30,000 Amerasian children in Vietnam."},
    {date: "1978",
     desc: "The Indian Child Welfare Act (ICWA) mandates that placements of American Indian children can be governed by their tribe."},
    {date: "1982",
     desc: "The Amerasian Act offers top-priority U.S. immigration to children in Korea, Vietnam, Laos, Cambodia, or Thailand who were known to have been fathered by U.S. citizens. The law does not grant admission to mothers or other relatives."},
    {date: "1983",
     desc: "Susie Guillory Phipps unsuccessfully sues the Louisiana Bureau of Vital Records to change her racial classification from Black to White. Phipps was designated as \"Black\" in her birth certificate in accordance with a 1970 state law which declared anyone with at least one-thirty-second \"Negro blood\" to be Black. The court upheld a state law which quantified racial identity, and in so doing affirmed the legality of assigning individuals to specific racial groupings. The appeal reached the U.S. Supreme Court in 1986 but was “dismissed for want of a substantial federal question”."},
    {date: "1984",
     desc: "President Reagan endorses a plan for acceptance for admission of all Amerasians, qualifying mothers, and siblings over the next 3 years through the Orderly Departure Program. Between 1982 and 1988, 4,500 Amerasian children and 7,000 accompanying relatives are brought to the U.S. despite the application process frequently taking years."},
    {date: "1988",
     desc: "Studies estimate that from 30%-70% of the present African American population has partial Indian ancestry [although most don’t identify this way], despite the Indian nations’ earlier institutionalization of slavery and laws forbidding “amalgamation.”"},
    {date: "1991",
     desc: "Gallup Poll finds that more Americans (48%) approved of interracial marriage than disapproved (42%)"},
    {date: "1992",
     desc: "U.S. Bureau of the Census states: For the first time in history, the number of biracial babies is increasing at a faster rate than the number of monoracial babies. There were 39% more Japanese/White births than monoracial Japanese American births. The number of Black/White biracial babies has increased almost 500%. In Native American communities, there are 40% more racially mixed babies than babies born to two parents who identify as Native American. 2% of all marriages or 1.2 million couples are made up of interracial relationships."},
    {date: "1994",
     desc: "At Randolph county High School in the eastern Alabama town of Wedowee, the principal reportedly tells students that the school prom will be canceled if an interracial couple attends. When asked by a student who is of multiracial descent how this applied to her, the principal reportedly said his rule was aimed at preventing \"mistakes\" like her."},
    {date: "1998",
     desc: "Biracial Radmilla \"Millie\" Cody, whose mother is Navajo and father is Black, is crowned Miss Navajo Nation."},
    {date: "1998",
     desc: "Interracial marriages continue to increase: White/Black 9%, White/Native American 12%, White/Asian 19%, White Hispanic 52%, Other 7%. A 1998 Census survey tallied more than 1.3 million racially mixed marriages in the U.S."},
    {date: "1999",
     desc: "At an awards/orientation event, the then Dean Ronald A. Feldman of CU.S.SW describes student body demographics to an audience of a few hundred students, staff, faculty, and benefactors and “jokingly” describes the category of \"other\" as being those students who don’t know who they are."},
    {date: "2000",
     desc: "Alabama voters repeal the long-standing anti-miscegenation law from their state constitution. Although interracial marriage could not be prosecuted due to the Supreme Court decision, Alabama had kept its original laws in the constitution, rather than formally repealing them."},
    {date: "2000",
     desc: "First year that people can identity as more than one race on Census. 2.4% of the U.S. population endorses more than one race."},
    {date: "2001",
     desc: "Companies such as, Benneton and Gap, launch multiracial marketing campaigns, making it “chic” to be multiracial."},
    {date: "2002",
     desc: "Multiracial celebrities such as Keanu Reeves, Angela Bassett, Halle Berry, Lenny Kravitz, Mariah Carey, Benjamin Bratt elevate multiracial identity into pop culture"},
    {date: "2006",
     desc: "Thousands of people boycotted work and school in order to support Day Without Immigrants, whiched showed the contributions of immigrants everyday in society."},
    {date: "2008",
     desc: "Barack Obama is elected President of the United States of America. President Obama identifies as African American, but openly acknowledges and discusses his multiracial heritage"},
    {date: "2008",
     desc: "Lieutenant Governor David Paterson becomes first African American governor of New York, and the first legally blind governor of any US state."},
    {date: "2008",
     desc: "Cullen Jones becomes 2nd African American to win an Olympic Gold medal in swimming as part of the US swim team."},
    {date: "2008",
     desc: "Actor, director and screenwriter, Tyler Perry becomes first African American to own a major film and television studio"},
    {date: "2008",
     desc: "California Democrat, Karen Bass, becomes the first African American woman elected as Speaker of a state House of Representatives"},
    {date: "2009",
     desc: "Barack Obama is inaugurated the first African American President of the United States of America."},
    {date: "2010",
     desc: "The multiracial children and adolescents population is growing in the U.S. It grew to a 32% increase since the year’s prior census. Multiracial groups are the largest demographics group amongst children under the age of 18 in the U.S. This is because interacial marriages and relationships are at an all time high amongst sub ethnic groups."},
    {date: "2015",
     desc: "A new law sponsored by City Councilmember Margaret Chin would allow New Yorkers to identify as more than one race, and check more than one box on citywide documents."},
    {date: "2015",
     desc: "Pew Research Center reports that 55% of multiracial adults report having experienced racial slurs or jokes."}]};

module.exports = MultiTimeline;
