application: usracehistory-195216
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: pycrypto
  version: "2.3"

handlers:
######################################################################
##  API: bracketed params are optional.

## Retrieve the account and an access token.
## GET params: email, password
- url: .*/acctok.*
  script: src.py.appuser.app


## Create account or update if authtok provided.
## POST params: email, [authtok], password, [actcode, name, url, shoutout,
##              lang, settings, remtls, rempts, completed, started, built]
- url: .*/updacc.*
  script: src.py.appuser.app


## Add or update a point (org contributor accounts only)
## POST params: email, authtok, date, text, codes, orgid, source, [keywords,
##              refs, srclang, translations, pic]
- url: .*/updpt.*
  script: src.py.point.app


## Retrieve a point pic
## GET params: pointid
- url: .*/ptpic.*
  script: src.py.point.app



######################################################################
##  General Config

## Structural static directories
- url: .*/img/
  static_dir: docroot/img/
- url: .*/css/
  static_dir: docroot/css/
- url: .*/docs/
  static_dir: docroot/docs/
- url: .*/js/
  static_dir: docroot/js/

## The index page
- url: /index.html
  static_files: docroot/index.html
  upload: docroot
## Trap anything ending with a slash and send it to index.html since
## there is no default processing to figure that out otherwise.
- url: (.*)/
  static_files: docroot/index.html
  upload: docroot
## Catchall is to look in docroot.
- url: /
  static_dir: docroot

